In [37]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine
import os
from pathlib import Path

In [38]:
base_folder = Path(r"/home/varhai/PRIMUS/data/83_IMPC_DATA/Bioimaging/SCREENad.Morpho&BodyComp")
output_file = base_folder / "combined_skull_analysis.xlsx"

In [39]:
# Defining your SQL query
conn = mysql.connector.connect(option_files=os.path.expanduser('~/.my.cnf')) 

sql_query = """
SELECT o.SPECIMEN_ID, s.STRAIN, s.GENDER, e.DATE, m.COHORT_ID,  o.VALUE_CATEGORY
FROM OBSERVATION as o, MOUSE as m, SPECIMEN as s, EXPERIMENT as e, PARAMETER as p
WHERE o.SPECIMEN_ID=m.ID and m.ID=s.ID and e.ID=o.EXPERIMENT_ID and o.PARAMETER_STABLE_ID=p.PARAMETER_STABLE_ID
 and m.COHORT_ID like 'c%' and o.PARAMETER_STABLE_ID='CCP_XRY_001_001'
"""
sql_query = """
SELECT o.SPECIMEN_ID,s.STRAIN,s.GENDER, m.COHORT_ID, e.DATE,o.VALUE_CATEGORY as SkullShape, LEN.VALUE_DATA_POINT as CraniumLength,COM.VALUE_TEXT as Comment
FROM OBSERVATION as o
    INNER JOIN MOUSE as m ON o.SPECIMEN_ID = m.ID
    INNER JOIN SPECIMEN as s ON m.ID = s.ID
    INNER JOIN EXPERIMENT as e ON e.ID = o.EXPERIMENT_ID
    INNER JOIN PARAMETER as p ON o.PARAMETER_STABLE_ID = p.PARAMETER_STABLE_ID
    LEFT JOIN (
        SELECT SPECIMEN_ID, VALUE_TEXT
        FROM OBSERVATION
        WHERE PARAMETER_STABLE_ID = 'CCP_XRY_032_001'
    ) AS COM ON o.SPECIMEN_ID = COM.SPECIMEN_ID

    LEFT JOIN (
        SELECT SPECIMEN_ID, VALUE_DATA_POINT
        FROM OBSERVATION
        WHERE PARAMETER_STABLE_ID = 'CCP_XRY_893_001'
    ) AS LEN ON o.SPECIMEN_ID = LEN.SPECIMEN_ID
WHERE
    m.COHORT_ID LIKE 'c%'
    AND o.PARAMETER_STABLE_ID = 'CCP_XRY_001_001';
"""
# Reading data into a Pandas DataFrame
db_df = pd.read_sql(sql_query, conn)

# Closing the connection
conn.close()

# Displaying the DataFrame

/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [40]:
def file_analysis_f(db_cohorts,cohort_df):
    
    res = []
    indexes= []
    for subj in cohort_df.index:
        try:
            specimen_name = subj.split("_")[2]
            
            abn_df = db_cohorts[(db_cohorts['SPECIMEN_ID'] == specimen_name)][['GENDER','STRAIN','COHORT_ID','DATE','CraniumLength','SkullShape','Comment']].values[0].tolist()
            indexes.append(subj )
            #print(cohort_df.loc[subj].values.tolist())

            res.append(abn_df+ cohort_df.loc[subj].values.tolist())
            
        except Exception as e:
            #print(e)
            pass
    return res,indexes

indexes = []
data = []
for fold_ in base_folder.iterdir():
    if fold_.is_file():
        continue
    file_ = (fold_/"abnormality_automated_combined.csv")
    
    if not file_.exists():
        continue
    #print("q")
    file_analysis = pd.read_csv(file_,index_col=0)
    #print(file_analysis)
    td, ind = file_analysis_f(db_df,file_analysis)
    print(td)
    indexes+= ind
    data+=td

[['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.88, 'abnormal', 'cranial sutures open mild', 554.16913348249, 'normal', 0.0156988586141962, 'normal', 1.0263588251187272, 0.9928081110891888, 0.956010137941444], ['male', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.69, 'normal', 'kyphosis', 473.2844251317543, 'normal', 0.0088966603896852, 'normal', 1.016555998783327, 0.997176365860613, 0.9675078974964], ['female', 'Cd209c', 'c290', datetime.date(2023, 5, 29), 27.06, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open mild', 353.5554759101657, 'normal', 0.0, 'normal', 1.0261306668831185, 1.0027985357576898, 0.9919820237568654], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.87, 'normal', 'T1 not fused, left C7 rib rudiment, pectus excavatum', 450.354122850924, 'normal', 0.0011144844548633, 'normal', 1.0204356556303609, 0.9955758360026, 0.9656873440025074], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.39, 'abnormal', 'cranial sutures open', 548.0890893940611, 'normal', 3.8430498443564814e-05, 'normal', 1.0305658309893957, 1.0039919024078454, 0.9866100003428246], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 25.95, 'abnormal', 'cranial sutures open', 616.6482302065579, 'normal', 0.0058414357634218, 'normal', 0.9967770133747036, 0.980595733531683, 0.944709804931406], ['male', 'Cd209c', 'c290', datetime.date(2023, 5, 29), 27.34, 'normal', 'pectus excavatum', 504.2187530421344, 'normal', 0.0138734099381268, 'normal', 1.0524939703040317, 1.02345970569247, 0.9975407921500314], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.75, 'normal', 'T1 not fused, scoliotic, kyphosis, fusions on caudal vertebrae (26+27, 22+23)', 455.2774787424273, 'normal', 0.0077245301871565, 'normal', 1.0155826162872863, 0.9899245678346068, 0.967863677213131], ['male', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.52, 'normal', 'T1 not fused, L6 = half S0, kyphosis', 440.3121846366421, 'normal', 0.0016332961838515, 'normal', 1.0315314957437474, 1.006770237971078, 0.9853718990951614], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.14, 'normal', 'pectus excavatum', 384.7763948848283, 'normal', 0.0, 'normal', 0.991856876317929, 0.9836283778919176, 0.95617434118541], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.99, 'normal', None, 541.8294045193159, 'normal', 0.0022673994081703, 'normal', 1.0063104852819738, 0.9957665471233446, 0.9643034791522612], ['male', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 28.49, 'abnormal', 'cranial sutures open', 619.9665767365173, 'normal', 0.0129895084739249, 'normal', 1.0074926153975554, 1.000292037221236, 0.9695839054109222], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.01, 'abnormal', 'cranial sutures open', 909.256612987966, 'normal', 0.0045732293147842, 'normal', 0.9944394480964908, 0.9765547023353812, 0.9382214399560294], ['male', 'Cd209c', 'c290', datetime.date(2023, 5, 29), 27.3, 'abnormal', 'kyphosis, cranial sutures open', 383.6274295736449, 'normal', 0.0007109642212059, 'normal', 1.0348152620153543, 1.0076297555461662, 0.9884213759691328], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.03, 'normal', 'T1 not fused', 410.10664689504335, 'normal', 0.0, 'normal', 1.0399568538679267, 1.006705082438654, 0.9881313646863986], ['male', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.47, 'normal', 'scoliotic, T1 not fused', 510.22571765257607, 'normal', 0.0034587448599208, 'normal', 1.0001542747664949, 0.9921683843129612, 0.9451134848607622], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 25.5, 'normal', None, nan, nan, nan, nan, nan, nan, nan], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.95, 'normal', 'T1 not fused, RHp II. Osteoneogenesis', 447.9158253103956, 'normal', 0.000614887975097, 'normal', 1.0365511801687728, 0.998339728002282, 0.9880737475322856], ['female', 'Cd209c', 'c290', datetime.date(2023, 5, 29), 27.12, 'normal', 'T1 not fused, scoliotic mild', 325.4949177310588, 'normal', 0.0001921524922178, 'normal', 1.033101019683888, 0.992201945498149, 0.9897114262802938], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.27, 'normal', None, 478.4702407158274, 'normal', 0.0008070404673148, 'normal', 1.022214802884055, 1.0105272415668187, 0.9873692889301644], ['male', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 27.24, 'normal', 'T1 not fused, scoliotic, S3+S4 vertebrae processi fused', 618.4535625266439, 'normal', 0.0009223319626455, 'normal', 0.9956233479420868, 0.9865090136279124, 0.9550726960754214], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.33, 'abnormal', 'both LHp II. and RHp II. Osteoneogenesis, cranial sutures open', 988.948624673989, 'abnormal', 0.0329733676645786, 'normal', 1.011257390760527, 0.9886028072629224, 0.9527603761765308], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.01, 'normal', 'T1 not fused, pectus excavatum', 565.4203421004199, 'normal', 0.0149686791437684, 'normal', 1.0396775141069765, 0.997322890288924, 0.995035724121406], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.23, 'normal', 'tiny extra process on T1 (not scored), pectus excavatum severe', 317.7598945892907, 'normal', 0.0002882287383267, 'normal', 1.0320852303730104, 1.001075253161364, 0.9767834171536384], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.34, 'abnormal', 'cranial sutures open', 538.2649788347618, 'normal', 0.000172937242996, 'normal', 1.0099210895817612, 0.977328603952066, 0.9590928675286192], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.5, 'normal', 'T1 not fused', 461.3836464789218, 'normal', 0.004150493831905, 'normal', 1.0223294669444154, 1.0008165577464967, 0.969806938017737], ['female', 'Adam7', 'c290', datetime.date(2023, 5, 29), 25.96, 'abnormal', 'processus spinosus small + tiny extra process on T1 (not scored), cranial sutures open', 654.6767106850097, 'normal', 0.0048230275546673, 'normal', 0.9851184778529068, 0.971275656993712, 0.9557626020000598], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 26.63, 'normal', 'T1 not fused, pectus excavatum', 861.3791754349922, 'normal', 0.0196379847046616, 'normal', 1.0179440348994735, 0.9850948906270832, 0.9532097610600864], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 25.8, 'normal', None, 402.9870813740338, 'normal', 0.0, 'normal', 1.0043614677810546, 0.9921218208872006, 0.9581065765927688], ['male', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 26.37, 'normal', 'T1 not fused', 637.5810449521047, 'normal', 0.0001537219937742, 'normal', 0.9802523101671452, 0.9657118142846512, 0.9447531222181756], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.0, 'normal', 'T1 not fused', 720.1941988600311, 'normal', 0.0108374005610852, 'normal', 1.0234385377643975, 0.9909482100785624, 0.9660970519137448], ['female', 'C57Bl/6NCrl', 'c290', datetime.date(2023, 5, 29), 25.36, 'abnormal', 'T1 not fused, kyphosis, shorter rostrum', 2539.658051524281, 'abnormal', 0.2668998116905576, 'abnormal', 1.0439104786893223, 1.0178419319933043, 0.8847150747257067], ['male', 'Cd209c', 'c290', datetime.date(2023, 5, 29), 26.68, 'normal', None, 502.686528381172, 'normal', 9.607624610891204e-05, 'normal', 1.0101325079158263, 0.9896062317404966, 0.9618431080209484], ['male', 'Adam7', 'c290', datetime.date(2023, 5, 29), 27.28, 'normal', 'T1 not fused, pectus excavatum mild', 743.3123782407916, 'normal', 0.0862188232581376, 'normal', 1.049260844951761, 1.009935783449308, 0.9828014748876636]]
[['male', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 26.3, 'normal', 'T1 not fused, kyphosis mild', 401.155502028414, 'normal', 9.607624610891204e-05, 'normal', 1.0210785829017457, 1.006077001127441, 0.9662988561519952], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.99, 'abnormal', 'microphtalmia', 644.172500464835, 'normal', 0.0248645324929864, 'normal', 1.0144338278643696, 1.007553694613691, 0.9766911056107984], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.13, 'abnormal', 'kyphosis, pectus excavatum mild, cranial sutures open', 649.4255451564583, 'normal', 0.0384689289420083, 'normal', 1.0310605891169198, 0.9665435165757308, 0.9525178416506171], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.62, 'normal', 'T1 not fused, pectus excavatum', 879.1621497752499, 'normal', 0.0768033511394642, 'normal', 1.001693844335746, 0.9960968932349564, 0.9675540724247668], ['male', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 27.0, 'normal', 'pectus excavatum mild', 623.0094815244215, 'normal', 0.0248453172437646, 'normal', 1.0278050948639548, 0.9944439313791612, 0.9741513716893122], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.22, 'normal', 'T1 not fused', 363.3328575278154, 'normal', 0.0006341032243188, 'normal', 0.9926735853449608, 0.9888413767947136, 0.9788989062705064], ['female', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 26.9, 'normal', 'scoliotic', 313.7912398298293, 'normal', 0.0, 'normal', 1.009115429381613, 0.9980431787863095, 0.9774965405810642], ['female', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 25.8, 'normal', 'T1 not fused', 367.379952694645, 'normal', 0.0, 'normal', 1.0043917582208417, 0.9843932385339934, 0.9698876210241216], ['male', 'Gcnt1', 'c292', datetime.date(2023, 6, 12), 26.01, 'normal', 'T1 not fused, tail tip cut off (26 Ca)', 695.0774029646348, 'normal', 0.0224434110910418, 'normal', 1.0260534202845744, 0.9766175577609564, 0.9552380019832614], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.62, 'normal', None, 336.06734501503144, 'normal', 0.0, 'normal', 1.0380377545130657, 1.0140339128456854, 0.9838917992478552], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.3, 'abnormal', 'T1 not fused, cranial sutures open', 284.448403287869, 'normal', 0.0, 'normal', 1.0018146812759126, 0.9903108241426752, 0.9705050335425444], ['female', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 24.89, 'abnormal', 'T1 not fused, scoliotic, rostrum malformation + rostrum shorter, cranial sutures open', 1749.5798284116263, 'abnormal', 0.1389262518734868, 'abnormal', 1.00071128668568, 0.9603759053871196, 0.926004477700004], ['female', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 26.17, 'abnormal', 'cranial sutures open', 419.9953428220029, 'normal', 0.0, 'normal', 0.9937857819416944, 0.9786816546527168, 0.9544440518070209], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.87, 'normal', 'scoliotic mild, T1 not fused', 453.5668153275788, 'normal', 0.0, 'normal', 1.0360782369331305, 1.0149779665555052, 0.9893095973191436], ['male', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.91, 'normal', 'pectus excavatum', 786.5591593647243, 'normal', 0.018715652742016, 'normal', 1.0018743276542437, 0.9769667182886618, 0.9507184553419216], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.75, 'normal', None, 641.2623378014085, 'normal', 0.0103378040813189, 'normal', 1.0115809601962165, 1.0043421038531035, 0.9670274567599052], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 23.88, 'abnormal', 'rostrum malformation + malocclusion + cranial sutures open', 3275.111921279477, 'abnormal', 0.3292917259136851, 'abnormal', 1.0061284953430116, 0.9713391888981916, 0.8751393660819087], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.5, 'abnormal', 'fusion of 26th and 27th caudal vertebrae, cranial sutures open severe', 771.1607632344482, 'normal', 0.947734522116752, 'abnormal', 1.2632297361686264, 1.0859997604556797, 0.8933649956099847], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 25.86, 'normal', 'T1 not fused, kyphosis, pectus excavatum', 511.0772392916277, 'normal', 0.0069174897198416, 'normal', 1.0182598337180198, 0.9950286760697244, 0.9625582396432047], ['female', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 25.82, 'normal', None, 671.4766081028965, 'normal', 0.0047845970562238, 'normal', 0.9862720095506536, 0.9586792448579928, 0.9351059661533316], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.76, 'normal', 'T1 not fused', 882.8989352945792, 'normal', 0.0236155412935705, 'normal', 0.9952564915793244, 0.93349869577142, 0.8931809725502284], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.51, 'abnormal', 'T1 not fused, lordosis, cranial sutures open', 809.3835508654372, 'normal', 0.0478844010606817, 'normal', 1.0128860428200837, 0.9546781992601582, 0.9099758533085804], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 27.06, 'abnormal', 'T1 not fused, cranial sutures open', 429.7819350283541, 'normal', 0.0, 'normal', 1.0091131030799911, 0.9918334440927554, 0.9632846118139547], ['male', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 26.48, 'normal', 'pectus excavatum', 342.5782425103745, 'normal', 0.0, 'normal', 1.0108291419538409, 0.9880906283427968, 0.9714299498033824], ['male', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 26.49, 'normal', 'kyphosis mild', 435.8222736992912, 'normal', 0.0001921524922178, 'normal', 1.0063400915520984, 0.9958506391518238, 0.967564708402796], ['male', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 27.06, 'normal', 'T1 not fused', 408.2116108174749, 'normal', 0.0015756504361861, 'normal', 1.019500259968915, 1.0011511993385265, 0.9694461669023304], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.73, 'normal', None, 450.0481550380279, 'normal', 0.0024979823988317, 'normal', 0.9716891121051132, 0.968799474903236, 0.9431938925062908], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 27.18, 'normal', 'shorter tail (22 Ca)', 385.363153825908, 'normal', 0.0, 'normal', 1.006652088843259, 0.9777447155451264, 0.9706005296498788], ['male', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 26.26, 'normal', 'T1 not fused, left C7 rib rudiment, kyphosis', 970.5633558136384, 'normal', 0.0113369970408516, 'normal', 1.012691298233005, 0.9775224334828226, 0.9489091770136402], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.5, 'normal', 'cranial sutures open very mild (not scored), lower enamel', 452.9311505944821, 'normal', 1.9215249221782407e-05, 'normal', 0.9968149807362944, 0.9829616676178428, 0.9701200394706148], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.77, 'abnormal', 'cranial sutures open', 501.4713508953976, 'normal', 0.0004419507321009, 'normal', 0.9965308782773072, 0.9714493128464718, 0.916274714118124], ['male', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.33, 'normal', 'scoliotic + kyphosis, pectus excavatum', 634.304185291313, 'normal', 0.0030552246262634, 'normal', 1.012393385068146, 0.9902418540062586, 0.9802281869990056], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 26.09, 'normal', None, 1414.6281915596448, 'abnormal', 0.0146035894085546, 'normal', 1.0117577998701266, 0.9951760610451998, 0.9489078150984483], ['male', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 26.69, 'normal', 'T1 not fused', 652.3778811261541, 'normal', 0.0236347565427923, 'normal', 1.005920245360236, 0.98320529545248, 0.97105527640985], ['female', 'C57Bl/6NCrl', 'c292', datetime.date(2023, 6, 12), 26.67, 'normal', 'kyphosis, pectus excavatum, cranial sutures open very mild (not scored)', 354.6794786425714, 'normal', 5.764574766534722e-05, 'normal', 1.0031586915907769, 0.9888622577403128, 0.978006060204922], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.96, 'normal', 'T1 not fused', 480.597513990701, 'normal', 0.0, 'normal', 0.9981337741634048, 0.98631609393767, 0.9517014019774456], ['female', 'Tcirg1', 'c292', datetime.date(2023, 6, 12), 25.67, 'normal', None, 468.263093710808, 'normal', 0.0011529149533069, 'normal', 0.9814585029533424, 0.9763938589861856, 0.9526951033159377], ['female', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 27.96, 'abnormal', 'cranial sutures open', 612.2239917639772, 'normal', 0.0128550017293724, 'normal', 0.9829290482438562, 0.9735480244834912, 0.9665160621143328], ['male', 'Pcid2', 'c292', datetime.date(2023, 6, 12), 25.95, 'normal', 'T1 not fused', 577.7265141179419, 'normal', 0.0184466392529111, 'normal', 1.016313625390778, 0.9837055927997402, 0.9555849045879702]]
[['male', 'C57Bl/6NCrl', 'c253', datetime.date(2022, 8, 29), 27.44, 'normal', 'C7 rib rudiment; T1 not fused', 519.2512343366249, 'normal', 0.0519003881480342, 'normal', 1.039672681537092, 1.0228410492421631, 0.9805131328805016], ['female', 'C57Bl/6NCrl', 'c253', datetime.date(2022, 8, 29), 27.38, 'normal', 'pectus excavatum; L6  TP malformed; rib nodes; tail broken - CA23+', 578.729376123612, 'normal', 0.0088197993927981, 'normal', 1.0457002469943932, 1.0140565233016718, 0.9830089587849886], ['male', 'C57Bl/6NCrl', 'c253', datetime.date(2022, 8, 29), 27.02, 'normal', 'C7 rib rudiment; T1 not fused', 505.93363056955593, 'normal', 0.0011721302025287, 'normal', 1.0547592863912425, 1.04417364442707, 1.001583360054831], ['female', 'Brinp3', 'c253', datetime.date(2022, 8, 29), 26.53, 'normal', 'scoliotic', 658.1724127380719, 'normal', 0.0045540140655624, 'normal', 0.990214173238002, 0.9727029488249852, 0.956511465228338], ['female', 'Brinp3', 'c253', datetime.date(2022, 8, 29), 26.28, 'normal', None, 614.9425806949534, 'normal', 0.0002882287383267, 'normal', 0.9843823138672216, 0.971223328420324, 0.9316281949129284], ['female', 'Gm20219', 'c253', datetime.date(2022, 8, 29), 26.2, 'normal', None, 498.3043323916133, 'normal', 0.0147765266515506, 'normal', 1.0071823561985165, 0.9678764719142808, 0.9566668498324814], ['male', 'C57Bl/6NCrl', 'c253', datetime.date(2022, 8, 29), 26.63, 'normal', None, 696.7932464562871, 'normal', 0.0184274240036893, 'normal', 1.0170902225717722, 1.012758129447333, 0.987714050454902], ['female', 'Gm20219', 'c253', datetime.date(2022, 8, 29), 26.9, 'normal', None, 288.440684190454, 'normal', 9.607624610891204e-05, 'normal', 1.0212959706287936, 1.0016971584468286, 0.9668642656882112], ['male', 'Zim1', 'c253', datetime.date(2022, 8, 29), 25.35, 'abnormal', 'scoliotic; kyphosis high; saddle-like nasalia', 888.5717719233539, 'normal', 0.0602013758118442, 'normal', 1.0012452861834291, 0.9543267843854026, 0.9310162759489652], ['female', 'C57Bl/6NCrl', 'c253', datetime.date(2022, 8, 29), 26.72, 'normal', None, 732.81852987531, 'normal', 0.0039391260904653, 'normal', 1.0081274035369685, 0.9907392840911952, 0.9790962862290116], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c253', datetime.date(2022, 8, 29), 25.29, 'abnormal', 'agouti; rostrum malformation; malocclusion; C7 rib - T1 rib fusion; T1 not fused; T2 pr. Spinosus reduced; T12; L1 ribs; cranium sutures open', 2972.0156744207397, 'abnormal', 0.406037431305484, 'abnormal', 1.0011923409835817, 0.9690951602268112, 0.9408311615536876], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c253', datetime.date(2022, 8, 29), 26.8, 'normal', 'agouti; C5+6; L5; lordosis high; CA27 malformation', 1068.980513076832, 'abnormal', 0.0693862649398562, 'normal', 1.0057468049058538, 0.9832591864295632, 0.954949981266118], ['male', 'C57Bl/6NCrl', 'c253', datetime.date(2022, 8, 29), 27.13, 'normal', 'pectus excavatum - sternum malformation; Femoris tendon osification; T1 not fused', 483.75008906391446, 'normal', 0.0111640597978555, 'normal', 1.070212547192625, 1.0188365142978206, 1.0086213216790925]]

[['female', 'Trak1 KO', 'c297', datetime.date(2023, 7, 17), 26.82, 'normal', 'T1 not fused', 456.955201276957, 'normal', 0.0007493947196495, 'normal', 1.0101437389513774, 0.9999140444632636, 0.9600148293905852], ['female', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.61, 'abnormal', 'cranial sutures open', 457.5100349335903, 'normal', 0.0004419507321009, 'normal', 1.0035055758679603, 1.0003927055780095, 0.9759852003145064], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.77, 'normal', None, 394.6528800566795, 'normal', 0.0, 'normal', 1.0079152557528932, 0.9968233515420772, 0.9839383953999812], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 28.0, 'normal', 'sternum crooked', 371.7126733547781, 'normal', 0.0, 'normal', 1.0177830589173196, 1.0053979192301064, 0.9900974813553808], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.77, 'normal', None, 433.5658095053968, 'normal', 0.001498789439299, 'normal', 1.01209747457925, 1.0013543949102326, 0.9779786962830576], ['female', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 26.67, 'abnormal', 'T1 not fused, cranial sutures open', 418.17999252295664, 'normal', 0.0002690134891049, 'normal', 1.0493561416070056, 0.9934420627099833, 0.9894357699041728], ['male', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 26.99, 'normal', 'kyphosis + lordosis, pectus excavatum', 566.0427590049876, 'normal', 0.0026901348910495, 'normal', 1.01698891544809, 1.0040195536811212, 0.9539897704986308], ['female', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.77, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 607.3429570725464, 'normal', 0.0016332961838515, 'normal', 1.032828160820996, 0.9898770784817132, 0.9529215356708792], ['female', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.27, 'abnormal', 'T1 not fused, 26 caudal vertebrae, sternum crooked, cranial sutures open', 585.1332859079923, 'normal', 0.0072057184581684, 'normal', 1.015850406388686, 0.9939671839555958, 0.9342690097408252], ['female', 'Pgf', 'c297', datetime.date(2023, 7, 17), 26.64, 'abnormal', 'kyphosis, cranial sutures open', 841.2573961575471, 'normal', 0.0210406978978517, 'normal', 1.057041268793687, 1.0013129386254362, 0.9787326441436182], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 27.08, 'normal', 'T1 not fused, 21 caudal vertebrae, pectus excavatum', 471.6862367196242, 'normal', 0.001498789439299, 'normal', 1.0163060864635922, 0.9970280458158016, 0.9860605262362075], ['male', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 27.5, 'normal', 'scoliotic, pectus excavatum', 440.48184827342016, 'normal', 0.0122016832558318, 'normal', 1.0507467074688353, 1.0264839663490364, 0.9870422820591522], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.78, 'normal', None, 434.0259164583685, 'normal', 0.0036508973521386, 'normal', 1.0372419165481388, 1.013019302637174, 0.9702120875306198], ['male', 'Trak1 KO', 'c297', datetime.date(2023, 7, 17), 26.85, 'normal', None, 453.4103892633064, 'normal', 5.764574766534722e-05, 'normal', 1.0074245028023836, 0.9645050248982878, 0.9498372775352384], ['female', 'Pgf', 'c297', datetime.date(2023, 7, 17), 25.83, 'normal', None, 475.2743725429592, 'normal', 0.0062257407478574, 'normal', 0.9909324062501672, 0.97852127589816, 0.959430418409442], ['female', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 27.62, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 696.2325185565593, 'normal', 0.0463279658737173, 'normal', 1.0550549950747952, 1.012542821477389, 0.995240042369322], ['female', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 27.07, 'normal', 'L6 = S0, pectus excavatum', 439.21939673011246, 'normal', 0.0034779601091426, 'normal', 1.0372520310878834, 1.0158440465178211, 0.985476592793908], ['male', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 27.06, 'normal', None, 408.1831536293121, 'normal', 0.0011529149533069, 'normal', 1.032631772889495, 1.0063422337456642, 0.9792044253460176], ['female', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.29, 'abnormal', 'sternum crooked, cranial sutures open', 613.4327454389796, 'normal', 0.0032858076169247, 'normal', 1.0005450845994932, 0.99793798162899, 0.9486256770814852], ['male', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 27.18, 'normal', None, 524.9655791559472, 'normal', 0.0340494216209984, 'normal', 1.0262185020743664, 1.0128726974764104, 0.9709024507007886], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.37, 'normal', None, 431.3845517177997, 'normal', 0.0014411436916336, 'normal', 1.0432660950888282, 0.9867782676066874, 0.9590497168040234], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 26.42, 'normal', 'T1 not fused', 416.4099111524539, 'normal', 0.0001345067445524, 'normal', 1.0148204783413484, 0.9887062378963726, 0.9626351240402198], ['female', 'Trak1 KO', 'c297', datetime.date(2023, 7, 17), 26.54, 'abnormal', 'T1 not fused, cranial sutures open', 374.1085147486957, 'normal', 0.0015372199377425, 'normal', 0.9940234672610712, 0.9827007326322228, 0.9700472284255752], ['male', 'Mlkl', 'c297', datetime.date(2023, 7, 17), 27.17, 'abnormal', 'kyphosis, cranial sutures open', 345.6957466351367, 'normal', 0.0, 'normal', 1.0101379795095464, 0.9982482191407444, 0.975468087590377], ['male', 'Trak1 KO', 'c297', datetime.date(2023, 7, 17), 26.95, 'abnormal', 'T1 not fused, L6 = half S0, cranial sutures open', 669.6710270995907, 'normal', 0.0081088351715921, 'normal', 1.0351400813798357, 0.988895061784783, 0.980681351905642], ['male', 'Trak1 KO', 'c297', datetime.date(2023, 7, 17), 27.14, 'normal', None, 633.3404886867773, 'normal', 0.0067253372276238, 'normal', 1.0082116635916596, 1.0005280956875626, 0.9759546141014168], ['female', 'C57Bl/6NCrl', 'c297', datetime.date(2023, 7, 17), 26.17, 'normal', 'T1 not fused', 632.6227432981175, 'normal', 0.0059375120095307, 'normal', 1.0234770062911347, 0.996529650690946, 0.9848807548576272]]
[['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 27.41, 'normal', None, 605.0863543029138, 'normal', 3.8430498443564814e-05, 'normal', 1.0073302364204968, 0.9766624225692996, 0.9546814823690264], ['male', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 26.92, 'normal', None, 420.8382481191954, 'normal', 0.0022481841589485, 'normal', 1.0253687240092857, 1.0085437762904557, 0.9785842068146914], ['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 25.41, 'abnormal', 'T1 not fused, cranial sutures open', 722.9183779590355, 'normal', 0.024461012259329, 'normal', 0.9812433652483136, 0.9639839785435056, 0.9393373490296923], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.57, 'normal', 'T1 not fused', 345.9010354040916, 'normal', 0.0003074439875485, 'normal', 1.0197343224853244, 0.9942729139816304, 0.9693159260207684], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.54, 'normal', 'T1 not fused, LH II. Broken/incoherent', 517.5828012329209, 'normal', 0.0074363014488297, 'normal', 1.003622488624329, 0.9901724745162436, 0.9516623744643652], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 25.7, 'normal', None, 558.9634020683086, 'normal', 0.0369317090042657, 'normal', 1.0091501234409133, 0.9527757287773552, 0.9214557161607508], ['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 27.48, 'normal', None, 491.4692798758988, 'normal', 0.0008262557165366, 'normal', 1.0237607674551477, 0.9799661966214052, 0.960617239096419], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 25.92, 'normal', None, 575.7280019353469, 'normal', 0.003170516121594, 'normal', 1.040156358313086, 0.9887203037164763, 0.9675295484207558], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 25.37, 'normal', 'T1 not fused', 1104.6499518715952, 'abnormal', 0.963625533223166, 'abnormal', 1.182796386184592, 0.953347441488195, 0.7969031453678568], ['male', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 27.44, 'normal', None, 536.1009878591894, 'normal', 0.0006533184735406, 'normal', 1.0102741821136545, 0.9800273097754806, 0.9727021350557916], ['male', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.67, 'normal', None, 771.8092283340065, 'normal', 0.0929441604857615, 'normal', 1.0087251879061765, 1.0054392913904062, 0.9682046862989184], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.54, 'normal', 'T1 not fused', 360.4363172413367, 'normal', 0.0024211214019445, 'normal', 1.0220622908595844, 0.9922670743814797, 0.9806439343190584], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.58, 'normal', 'PS missing', 627.9896238101038, 'normal', 0.0066484762307367, 'normal', 1.0081591933971876, 0.972535682974846, 0.9313703708805158], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 27.33, 'normal', None, 592.2305642506486, 'normal', 0.0004803812305445, 'normal', 1.041660874331949, 1.001876775523325, 0.976804372453191], ['male', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 24.72, 'abnormal', 'rostrum malformed + shorter premaxilla', 3244.3732607819475, 'abnormal', 0.4780177548902809, 'abnormal', 1.0649727311645911, 1.0061225400375728, 0.9355501997906944], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 27.02, 'normal', 'T1 not fused', 480.60001297649455, 'normal', 0.0031320856231505, 'normal', 1.0469690799485485, 1.035316590751905, 1.0104424012575564], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.55, 'normal', None, 479.3329705368634, 'normal', 0.0037277583490257, 'normal', 1.0017688589724485, 0.9986554416803154, 0.966624233256688], ['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 26.92, 'normal', None, 453.1026656462393, 'normal', 0.0001921524922178, 'normal', 1.0000831538438155, 0.9841337795907128, 0.9526960703273276], ['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 26.66, 'normal', None, 415.3298983048511, 'normal', 0.0002305829906613, 'normal', 0.9963509581784876, 0.9849558143448665, 0.9632675524999524], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 27.26, 'normal', None, 538.9052857218883, 'normal', 0.0025748433957188, 'normal', 1.0123665886780673, 0.9695300953679618, 0.9635768465297216], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.73, 'normal', None, 426.6927874479241, 'normal', 0.0003650897352138, 'normal', 1.0321249016796863, 0.9957155745829832, 0.9587600816153782], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.67, 'normal', None, 618.8342116394952, 'normal', 0.0086084316513585, 'normal', 1.0238563130744316, 0.9867108378891888, 0.9713564178223904], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.13, 'normal', None, 541.3243877543747, 'normal', 0.0103954498289842, 'normal', 1.0137519019895351, 0.9642836252823505, 0.9410758992936156], ['male', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 26.34, 'normal', 'pectus excavatum', 491.1320183941638, 'normal', 0.0036893278505822, 'normal', 0.986583643979318, 0.9821789730742972, 0.9512041197622388], ['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 27.24, 'normal', None, 499.2109592167244, 'normal', 0.0004611659813227, 'normal', 1.0496111949015547, 1.0277695133165008, 0.9886940221300976], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 27.23, 'normal', None, 588.0020298016258, 'normal', 0.0037854040966911, 'normal', 1.0236132290994315, 1.006119158407923, 0.9819596253189026], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.26, 'normal', None, 461.546746486218, 'normal', 0.0016332961838515, 'normal', 1.0033110679980204, 0.977172451758465, 0.9608713032761296], ['male', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.74, 'normal', 'T1 not fused, tail tip osteoneogenesis, kyphosis', 550.7284073273739, 'normal', 0.0085892164021367, 'normal', 1.022180508918507, 1.0041418505633994, 0.9776966710074056], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.26, 'normal', 'kyphosis, pectus excavatum', 740.0031195752865, 'normal', 0.0224049805925982, 'normal', 0.9966624184843708, 0.9902161632333344, 0.9738552762568726], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.6, 'normal', 'T1 not fused', 412.54466409669664, 'normal', 1.9215249221782407e-05, 'normal', 1.03986187782065, 1.0088449518004825, 0.9846543787479098], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.94, 'normal', 'T1 not fused', 390.3169953182468, 'normal', 0.0027285653894931, 'normal', 1.0314922958290795, 1.0121030962058246, 0.9983938868159448], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.72, 'normal', 'T1 not fused, pectus excavatum', 344.46100055344107, 'normal', 0.0, 'normal', 1.0050020285436818, 0.9966585967634708, 0.9790821427394512], ['female', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 25.28, 'normal', 'T1 not fused, pectus excavatum', 657.8307621032766, 'normal', 0.0185235002497982, 'normal', 0.9675464990114409, 0.9542898731354305, 0.920074082983842], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 26.67, 'normal', None, 473.4891273351668, 'normal', 0.0041120633334614, 'normal', 1.0190710693433864, 0.9955169012977152, 0.9864898745616972], ['male', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 27.45, 'normal', 'pectus excavatum', 475.0455097526565, 'normal', 0.0112217055455209, 'normal', 1.0352938104195355, 0.9853051374744904, 0.98072477526338], ['female', 'C57Bl/6NCrl', 'c264', datetime.date(2022, 11, 14), 26.62, 'normal', 'T1 not fused, kyphosis', 480.2867768361287, 'normal', 3.8430498443564814e-05, 'normal', 1.0132692672857326, 0.982566252271446, 0.9779120626750566], ['female', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 27.15, 'normal', 'pectus excavatum', 435.859985915461, 'normal', 0.0003843049844356, 'normal', 1.005934882642176, 0.9892139629359477, 0.9474963068249896], ['male', 'Dvl3 CY', 'c264', datetime.date(2022, 11, 14), 27.57, 'normal', None, 581.7057754824705, 'normal', 0.0193113254678913, 'normal', 1.0467700024168038, 1.0046994853361182, 0.9763887206098972], ['male', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.86, 'normal', 'PS missing', 598.4524520953744, 'normal', 0.0165443295799546, 'normal', 1.0128057526392615, 0.9838609040200657, 0.9707582806803232], ['male', 'Mmp13', 'c264', datetime.date(2022, 11, 14), 26.4, 'normal', 'T1 not fused', 683.7347958048636, 'normal', 0.0146996656546635, 'normal', 0.992415739914419, 0.9838688132170708, 0.9763924697643626]]

[['male', 'Creb3l2', 'c277', datetime.date(2023, 2, 13), 27.08, 'normal', 'T1 not fused', 488.8355298478541, 'normal', 0.0036316821029168, 'normal', 1.0369838101159767, 1.014663418888219, 0.989549677413121], ['male', 'Creb3l2', 'c277', datetime.date(2023, 2, 13), 26.74, 'normal', None, 406.6919888636783, 'normal', 0.0, 'normal', 1.0310862682795696, 0.9920791490445268, 0.9847040149334144], ['female', 'Creb3l2', 'c277', datetime.date(2023, 2, 13), 26.58, 'normal', 'T1 not fused', 309.01296275163685, 'normal', 0.0001921524922178, 'normal', 0.997135413340021, 0.9875787955966888, 0.9600907010008708], ['female', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.27, 'normal', None, 412.4462322206223, 'normal', 9.607624610891204e-05, 'normal', 1.0179214674672667, 0.9957466430768188, 0.9776517190535412], ['female', 'Vsx1', 'c277', datetime.date(2023, 2, 13), 28.09, 'abnormal', 'cranial sutures open', 488.1305640392557, 'normal', 0.0, 'normal', 1.0218782483844555, 1.0164765169583996, 0.9890322693964252], ['male', 'Vsx1', 'c277', datetime.date(2023, 2, 13), 27.47, 'normal', None, 550.795515957723, 'normal', 0.0049767495484416, 'normal', 1.0338130521002755, 1.0251548665945431, 0.9965580554665416], ['female', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.8, 'normal', 'scoliotic mild, T1 not fused, Processus spinosus missing, left C7 rib rudiment', 438.31073920096, 'normal', 0.001056838707198, 'normal', 1.0320395432239378, 1.0055369797151912, 0.9611791170299456], ['female', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.09, 'normal', None, 617.5550070753957, 'normal', 0.0155451366204219, 'normal', 1.0056635503910194, 0.9883003149404298, 0.9591752231880494], ['male', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.93, 'normal', 'scoliotic, T1 not fused, Processus spinosus missing', 573.6727944855306, 'normal', 0.0091848891280119, 'normal', 1.0055626365331605, 0.9824752840194788, 0.9666652589596904], ['female', 'PGC', 'c277', datetime.date(2023, 2, 13), 26.37, 'normal', None, 666.4249821108726, 'normal', 0.0267860574151646, 'normal', 0.9900151130095, 0.98564681502969, 0.935615387750911], ['male', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.99, 'normal', 'T1 not fused, LH II. osteoneogenesis', 639.2878637944028, 'normal', 0.0004611659813227, 'normal', 1.0328685372444246, 0.9940762351982378, 0.967015461926912], ['female', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 26.28, 'normal', 'tail tip cut off, T1-T2 transposed, left C7 rib rudiment + C7 process abnormal, ribs/thorax shape abnormal', 740.9626633156115, 'normal', 0.0387571576803351, 'normal', 1.010053978148395, 0.9982985774926988, 0.9726302501639092], ['male', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.74, 'normal', 'kyphosis', 423.2530292031077, 'normal', 0.002113677414396, 'normal', 1.0176507540787243, 0.996058953897324, 0.98339876190927], ['male', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 27.01, 'normal', 'T1 not fused, Processus spinosus missing', 519.5505622629665, 'normal', 0.0119518850159486, 'normal', 1.0094749309214377, 0.9915529057628109, 0.9548174812653526], ['female', 'C57Bl/6NCrl', 'c277', datetime.date(2023, 2, 13), 26.77, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 362.6958865462684, 'normal', 1.9215249221782407e-05, 'normal', 0.9927422820198092, 0.9829287559459348, 0.9620646140528524], ['male', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 26.72, 'normal', 'T1-T2 transposed, left + right C7 rib rudiment', 519.8655690384288, 'normal', 0.0006725337227623, 'normal', 1.001738630687916, 0.9823931512168764, 0.974794019958929], ['female', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 25.74, 'abnormal', 'T1 not fused, PS missing, left+right C7 rib rudiment, cranial sutures open', 544.7335961175723, 'normal', 0.0006533184735406, 'normal', 0.9711363006943272, 0.9695967932284292, 0.9360530285133908], ['male', 'C57Bl/6NCrl', 'c277', datetime.date(2023, 2, 13), 24.85, 'abnormal', 'T1 not fused, kyphosis, rostrum rounded, cranial sutures open', 2753.3139002498806, 'abnormal', 0.3804427193420698, 'abnormal', 1.0007628795001318, 0.9910150645940876, 0.9201272396329644], ['female', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.06, 'abnormal', 'scoliotic, T1 not fused, cranial sutures open', 423.63398084991456, 'normal', 0.0001537219937742, 'normal', 1.0440553751595247, 0.9899073801552984, 0.9696230267379912], ['female', 'PGC', 'c277', datetime.date(2023, 2, 13), 26.76, 'normal', 'scoliotic, T1 not fused, left C7 process abnormal', 400.3118373829765, 'normal', 0.0001537219937742, 'normal', 1.0127883616705198, 0.98891769396703, 0.9550734647059224], ['female', 'Creb3l2', 'c277', datetime.date(2023, 2, 13), 26.89, 'abnormal', 'interscapular ossification, cranial sutures open', 687.7002685583388, 'normal', 0.0260750931939587, 'normal', 1.0128432415756414, 0.9800145607829474, 0.9337881167236418], ['female', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 27.11, 'abnormal', 'T1 not fused, cranial sutures open', 485.23421344715854, 'normal', 0.004938319049998, 'normal', 1.0362321679602218, 1.0187264280158057, 0.9903556709149468], ['female', 'C57Bl/6NCrl', 'c277', datetime.date(2023, 2, 13), 25.93, 'abnormal', 'T1 not fused, left C7 rib rudiment, cranial sutures open', 620.2587929995381, 'normal', 0.0032089466200376, 'normal', 0.9962170558332368, 0.9634487674780938, 0.9383075169602751], ['female', 'PGC', 'c277', datetime.date(2023, 2, 13), 26.4, 'normal', 'T1 not fused', 713.9842810461976, 'normal', 0.0123746204988278, 'normal', 1.003282688584988, 0.9809674688012372, 0.932718089995434], ['male', 'Creb3l2', 'c277', datetime.date(2023, 2, 13), 26.9, 'normal', 'sternum crooked', 411.8136886461664, 'normal', 0.001671726682295, 'normal', 1.015519324710373, 1.0009614922258554, 0.9791048346113452], ['female', 'Creb3l2', 'c277', datetime.date(2023, 2, 13), 26.28, 'normal', 'scoliotic', 418.8431864924767, 'normal', 3.8430498443564814e-05, 'normal', 0.9912403407322584, 0.9789350672217534, 0.949171537131053], ['male', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 26.45, 'normal', 'T1 not fused, PS missing, kyphosis, pectus excavatum', 471.7010266652791, 'normal', 0.000345874485992, 'normal', 0.9903762298103932, 0.981419714332746, 0.9545832720562236], ['male', 'Vsx1', 'c277', datetime.date(2023, 2, 13), 26.94, 'normal', None, 259.43144942367604, 'normal', 0.0012489911994158, 'normal', 1.0266502040137564, 1.0075601764907247, 0.9929796452783052], ['female', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.28, 'normal', 'T1 not fused, PS missing, left C7 rib rudiment', 744.625540872726, 'normal', 0.0392567541601014, 'normal', 1.015368635455992, 1.002473475062223, 0.9493492308778791], ['female', 'PGC', 'c277', datetime.date(2023, 2, 13), 26.47, 'normal', 'T1 not fused', 568.6760195524072, 'normal', 0.0, 'normal', 0.9894494298643088, 0.9848992913432778, 0.9503827370393676], ['male', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 26.99, 'normal', 'T1 not fused, left + right C7 rib rudiment', 533.0356367702863, 'normal', 0.0044195073210099, 'normal', 1.0276058883108277, 1.0000061397019542, 0.9833102236563196], ['male', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 26.31, 'normal', 'scoliotic', 584.1293274392643, 'normal', 0.0140655624303447, 'normal', 1.0227639387828955, 0.9822964505052044, 0.9323291583416484], ['female', 'Agpat2', 'c277', datetime.date(2023, 2, 13), 27.13, 'normal', 'scoliotic, PS missing', 659.9255292371154, 'normal', 0.0057453595173129, 'normal', 1.0243169946031885, 1.020582983561228, 0.9592439896394964], ['male', 'Vsx1', 'c277', datetime.date(2023, 2, 13), 26.65, 'normal', 'kyphosis', 376.4930010735194, 'normal', 0.0012105607009722, 'normal', 1.0441887091722653, 1.0124154622368595, 0.9887814110904192], ['male', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 28.28, 'normal', 'T1 not fused, pectus excavatum', 563.6005535117654, 'normal', 0.0144498674147803, 'normal', 1.0958880511027178, 1.0379977410098669, 1.0144710874832326], ['female', 'Cd209c', 'c277', datetime.date(2023, 2, 13), 26.75, 'normal', None, 685.1050873269746, 'normal', 0.0142192844241189, 'normal', 1.0004431657651136, 0.9716058363117568, 0.9671773011787432], ['male', 'Cobll1', 'c277', datetime.date(2023, 2, 13), 26.65, 'normal', 'T1 not fused', 370.5239931263092, 'normal', 0.000345874485992, 'normal', 1.005600683700628, 0.9931469267783196, 0.9748770924735396]]
[['female', 'Ate1', 'c267', datetime.date(2022, 12, 5), 27.07, 'normal', 'LH I. polydactyly', 359.7999158183258, 'normal', 0.0031897313708158, 'normal', 0.9866387303685268, 0.9794489153500698, 0.9628129006773876], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 27.43, 'normal', 'sternum malformed', 334.3024410681016, 'normal', 0.0015372199377425, 'normal', 1.020214791517392, 1.0159638735585146, 0.9926890815581664], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 26.36, 'normal', None, 1805.058547370023, 'abnormal', 0.997175358364398, 'abnormal', 0.97178286780725, 0.9356537379523068, 0.882219903741676], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.4, 'normal', None, 638.4704746704948, 'normal', 0.0036701126013604, 'normal', 1.0036531794883918, 0.9850461666820532, 0.9569814090018672], ['female', 'Fam161b', 'c267', datetime.date(2022, 12, 5), 26.42, 'normal', None, 72135.7506211982, 'abnormal', 0.9984435648130356, 'abnormal', 1.512524556527694, 1.1946472498618892, 0.6420950257454704], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 27.65, 'normal', None, 518.0834805346497, 'normal', 0.0042465700780139, 'normal', 1.081497694800769, 1.036199619269797, 0.99760861296416], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 26.71, 'normal', None, 2191.3511012555223, 'abnormal', 0.9941777794858, 'abnormal', 1.1749086089768714, 1.111728320232993, 0.9376383393591708], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.72, 'normal', 'shorter tail', 590.1276075522276, 'normal', 0.0018446639252911, 'normal', 0.9938457034612608, 0.9840800027047936, 0.9712309058115304], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.77, 'normal', 'tail move', 441.5268451597632, 'normal', 0.0006533184735406, 'normal', 0.9971463406834152, 0.9902799354957668, 0.9769153713929296], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 25.47, 'abnormal', 'shorter tail, cranial sutures open', 2908.727114976085, 'abnormal', 0.3941239767879789, 'abnormal', 1.013152465871233, 0.9820128290400372, 0.9299543538451788], ['female', 'Fam161b', 'c267', datetime.date(2022, 12, 5), 26.31, 'normal', None, 137042.18840748526, 'abnormal', 0.9991737442834634, 'abnormal', 1.1014052365769291, 0.8961860957721375, 0.7044472321831456], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 26.96, 'normal', None, 333.7745253380959, 'normal', 0.0, 'normal', 1.0462804245178443, 1.0254071494414063, 1.0015855126076856], ['female', 'Ate1', 'c267', datetime.date(2022, 12, 5), 27.11, 'abnormal', 'cranial sutures open', 459.1265153705767, 'normal', 0.0045732293147842, 'normal', 0.9988086335051052, 0.9889462334939376, 0.9654671582839768], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 27.37, 'normal', None, 316.5428654029969, 'normal', 0.0, 'normal', 1.0263256327729675, 1.0107281575466511, 0.9900639939630316], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 28.71, 'normal', 'pectus excavatum', 380.8135142954188, 'normal', 0.0, 'normal', 1.0155996364856748, 0.9999414737492284, 0.9892581971454943], ['female', 'Cpm', 'c267', datetime.date(2022, 12, 5), 25.94, 'normal', 'T1 not fused, kyphosis', 530.6949788645524, 'normal', 0.0006533184735406, 'normal', 0.9873963974858664, 0.956463344005431, 0.9362401716268672], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.25, 'abnormal', 'right C7 rib, cranial sutures open severe', 443.8278038368848, 'normal', 0.0001921524922178, 'normal', 1.0041450007450032, 0.9732185159137366, 0.9491661785060288], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 28.75, 'abnormal', 'T1 not fused, cranial sutures open, microphtalmia', 757.1492542657357, 'normal', 0.0131240152184773, 'normal', 1.0248304897282272, 1.0155028896141969, 0.9890054823115204], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 25.89, 'normal', 'T1 not fused', 374.27757051472713, 'normal', 0.001056838707198, 'normal', 1.0128612448074148, 0.9895662924010594, 0.9758797296515864], ['female', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.61, 'normal', 'shorter tail', 435.1360189801605, 'normal', 0.0007686099688712, 'normal', 1.0008944869412273, 0.9862030256616664, 0.9573927593495538], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 27.47, 'normal', 'L6 = half S0', 503.184476957748, 'normal', 0.0446370239422005, 'normal', 1.0377843443808343, 1.0207575858953466, 1.0007752337077438], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 26.65, 'normal', 'T1 not fused, tail move', 335.3477317169003, 'normal', 0.0019599554206218, 'normal', 1.0356969058680257, 0.9888070816297972, 0.9784879163033064], ['female', 'Cpm', 'c267', datetime.date(2022, 12, 5), 25.8, 'normal', None, 431.3366030814539, 'normal', 5.764574766534722e-05, 'normal', 1.0183330718312211, 0.9815853859092478, 0.9580589844616012], ['female', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.66, 'normal', 'kyphosis, T1 not fused', 395.8334104772733, 'normal', 0.0, 'normal', 0.9957053112105844, 0.9832815392113567, 0.9566491690504366], ['female', 'Cpm', 'c267', datetime.date(2022, 12, 5), 26.21, 'normal', 'T1 not fused', 467.7105951237726, 'normal', 0.0025364128972752, 'normal', 0.983550375757095, 0.9676968400627118, 0.946104136755828], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 26.83, 'normal', 'pectus excavatum', 321.7842826678992, 'normal', 0.0006341032243188, 'normal', 1.036154886184196, 1.010777180009488, 0.9858711638360323], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 28.29, 'normal', None, 377.0080299408098, 'normal', 0.0, 'normal', 1.0660866900702592, 1.026012618188798, 0.9976842242570512], ['female', 'Fam161b', 'c267', datetime.date(2022, 12, 5), 27.04, 'normal', None, 10306.544879150586, 'abnormal', 0.1750893509088812, 'abnormal', 1.0882794643900071, 1.0094150430752908, 0.9220803974684358], ['male', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 27.13, 'normal', None, 391.9264480828464, 'normal', 0.0, 'normal', 1.0294839526936652, 1.0184634256673006, 1.0087951340105898], ['male', 'Cpm', 'c267', datetime.date(2022, 12, 5), 27.2, 'normal', 'tail move', 589.4038010990479, 'normal', 0.0079166826793743, 'normal', 1.0229880393530613, 0.9933599990099892, 0.980828087583092], ['female', 'C57Bl/6NCrl', 'c267', datetime.date(2022, 12, 5), 27.04, 'normal', 'T1 not fused', 357580.6618340668, 'abnormal', 0.9984435648130356, 'abnormal', 1.2635847709506456, 0.8698529223127025, 0.3906497844035521]]

[['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 27.24, 'abnormal', 'T1 extra process, cranial sutures open severe', 602.6868226913023, 'normal', 0.008646862149802, 'normal', 1.0464972767355285, 1.0068038344610415, 0.977951002057268], ['male', 'C57Bl/6NCrl', 'c257', datetime.date(2022, 9, 27), 26.95, 'normal', 'kyphosis', 852.2149473794603, 'normal', 0.0612005687713769, 'normal', 1.0237865164533615, 0.9904644647313228, 0.9896010065200472], ['male', 'Uox', 'c257', datetime.date(2022, 9, 27), 27.27, 'normal', 'pectus excavatum', 463.0874974756133, 'normal', 0.000787825218093, 'normal', 1.01975807402697, 1.0043590504134263, 0.9692194065197022], ['male', 'C57Bl/6NCrl', 'c257', datetime.date(2022, 9, 27), 26.36, 'normal', None, 561.8335526816131, 'normal', 0.0066100457322931, 'normal', 1.02206130933515, 1.0006641202642923, 0.9697191421692396], ['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.96, 'normal', 'T1 not fused', 408.3299514919918, 'normal', 0.0006341032243188, 'normal', 1.0074398510449198, 0.9840229429606628, 0.9715146993468932], ['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 27.28, 'normal', None, 259.29093451433266, 'normal', 0.0, 'normal', 1.0093892979121537, 1.0024846250643191, 0.9627511140226824], ['female', 'Dcaf5', 'c257', datetime.date(2022, 9, 27), 24.96, 'normal', 'pectus excavatum', 950.2268966874904, 'normal', 0.0757272971830444, 'normal', 0.9749762539893916, 0.9391989866859718, 0.861954550874368], ['female', 'Dcaf5', 'c257', datetime.date(2022, 9, 27), 25.4, 'normal', None, 909.1724834707954, 'normal', 0.0338764843780023, 'normal', 0.9814709913843268, 0.9495608500092414, 0.8947018127331197], ['male', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.49, 'normal', None, 477.594660568078, 'normal', 0.0019791706698435, 'normal', 1.0293852989478935, 1.009356358594431, 0.9794155211025306], ['female', 'C57Bl/6NCrl', 'c257', datetime.date(2022, 9, 27), 28.25, 'abnormal', 'cranial sutures open', 411.5118117249016, 'normal', 0.0, 'normal', 1.044649191472661, 1.0119567769317075, 0.9881226041968048], ['female', 'C57Bl/6NCrl', 'c257', datetime.date(2022, 9, 27), 26.7, 'normal', None, 385.4049884381228, 'normal', 0.0, 'normal', 1.0348028422732407, 1.0078374074667864, 0.9935821790800762], ['male', 'Hcls1', 'c257', datetime.date(2022, 9, 27), 26.53, 'normal', None, 638.9143365808577, 'normal', 0.015621997617309, 'normal', 1.024360216486907, 0.9997074482357924, 0.9774291641586834], ['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.33, 'normal', None, 377.619143275189, 'normal', 0.0019023096729564, 'normal', 1.002744305063811, 0.9964629281629518, 0.9668619241439198], ['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.19, 'normal', None, 441.8572691168892, 'normal', 5.764574766534722e-05, 'normal', 1.009110940618754, 1.0043131573194894, 0.9577293616199578], ['female', 'C57Bl/6NCrl', 'c257', datetime.date(2022, 9, 27), 24.62, 'abnormal', 'rostrum malformation', 1854.039516854369, 'abnormal', 0.172994888743707, 'abnormal', 1.008135148284135, 0.959628298099136, 0.940071642042278], ['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.18, 'normal', None, 931.6269184331009, 'normal', 0.0019407401714, 'normal', 1.028297495205747, 1.0002011954301315, 0.9783082365681132], ['male', 'C57Bl/6NCrl', 'c257', datetime.date(2022, 9, 27), 26.53, 'normal', 'T1 not fused', 527.3383444116976, 'normal', 0.002382690903501, 'normal', 1.0230767914829826, 0.9951329871748354, 0.9896787286309524], ['female', 'Uox', 'c257', datetime.date(2022, 9, 27), 27.4, 'normal', None, 399.667533469984, 'normal', 0.0001537219937742, 'normal', 1.0117441348095246, 0.9999807393354596, 0.9893820475847152], ['male', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.59, 'normal', 'T1 not fused', 461.8720967752857, 'normal', 0.0197917066984358, 'normal', 1.0602827639441783, 1.0255090940839855, 0.9851281348276868], ['male', 'Uox', 'c257', datetime.date(2022, 9, 27), 26.99, 'normal', 'T1 not fused, C7 right rib rudiment', 658.7152995792809, 'normal', 0.0182544867606932, 'normal', 1.0493622851950752, 1.0096996893227494, 0.9914196338451532], ['male', 'Uox', 'c257', datetime.date(2022, 9, 27), 27.52, 'normal', 'T1 not fused, pectus excavatum', 622.2707853288515, 'normal', 0.0004995964797663, 'normal', 1.0223864063411858, 0.9995470299868128, 0.9726909882207952]]
[['female', 'Cer1', 'c287', datetime.date(2023, 5, 9), 27.11, 'abnormal', 'T1 not fused, cranial sutures open', 444.1847929596962, 'normal', 0.0004035202336574, 'normal', 1.0301373562737022, 0.9969466780793392, 0.9627043644465252], ['female', 'Ptprz1', 'c287', datetime.date(2023, 5, 9), 26.51, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 425.2731597826522, 'normal', 0.0, 'normal', 1.009988716404303, 0.9950419154939272, 0.9628300443514072], ['male', 'Cer1', 'c287', datetime.date(2023, 5, 9), 26.07, 'normal', 'T1 not fused', 1660.9692278222428, 'abnormal', 0.1793743514853387, 'abnormal', 1.0037855830977085, 0.9925012650477224, 0.946019199076552], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.37, 'normal', 'T1 not fused', 443.9372957711431, 'normal', 0.0024595519003881, 'normal', 1.005530249122448, 0.9651731853061658, 0.954523876218452], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.84, 'normal', 'T1 not fused, kyphosis', 326.8581426431219, 'normal', 0.0, 'normal', 1.0291022718266305, 1.003649313943256, 0.976291370446859], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.24, 'abnormal', 'Processus spinosus missing, kyphosis severe, pectus excavatum, cranial sutures open mild', 1300.944609460816, 'abnormal', 0.0861227470120287, 'normal', 1.0140336117213555, 0.9667129561259228, 0.9309610923160124], ['female', 'Cer1', 'c287', datetime.date(2023, 5, 9), 26.08, 'abnormal', 'T1 not fused, sacral vertebrae mildly dysmorfed, cranial sutures open mild', 328.2046784553264, 'normal', 7.686099688712963e-05, 'normal', 1.0039354749761462, 0.9959573287697636, 0.9810248411268172], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 25.06, 'normal', 'scoliotic', 717.9447967361176, 'normal', 0.0345682333499865, 'normal', 0.9612654361185732, 0.9371473389130458, 0.9185777217593812], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 27.27, 'abnormal', 'T1 not fused, cranial sutures open', 539.4939060622623, 'normal', 0.0062065254986357, 'normal', 1.019264807823297, 1.0049679194280643, 0.966111064385398], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.98, 'normal', None, 615.8198679465314, 'normal', 0.0203489489258675, 'normal', 1.0219996441938777, 1.0007650054093518, 0.977018842825218], ['male', 'Cobll1', 'c287', datetime.date(2023, 5, 9), 26.74, 'normal', 'T1 not fused, kyphosis, pectus excavatum', 950.3343656286607, 'normal', 0.0529764421044541, 'normal', 1.04094617852466, 0.998558803672438, 0.9479693951919772], ['male', 'Ptprz1', 'c287', datetime.date(2023, 5, 9), 26.74, 'normal', 'T1 not fused, kyphosis, pectus excavatum', 413.0843245972421, 'normal', 5.764574766534722e-05, 'normal', 1.007022221201889, 0.9958673192399912, 0.9826070022162836], ['male', 'Ptprz1', 'c287', datetime.date(2023, 5, 9), 27.02, 'normal', None, 746.2039905629381, 'normal', 0.0151608316359863, 'normal', 1.051932193328469, 1.003359406895776, 0.985356360982805], ['female', 'Cer1', 'c287', datetime.date(2023, 5, 9), 26.28, 'normal', 'T1 not fused, C3 fused to C2, Ca6 fused to Ca7, RHp II. Osteoneogenesis mild', 755.1644949310808, 'normal', 0.0117789477729526, 'normal', 1.0232473501054886, 0.998830136389622, 0.9680067599725592], ['female', 'Ptprz1', 'c287', datetime.date(2023, 5, 9), 26.78, 'abnormal', 'pectus excavatum, cranial sutures open', 492.0555818908544, 'normal', 0.0426194227739133, 'normal', 1.049081036216454, 0.9910609517636948, 0.962680389093562], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.43, 'normal', 'scoliotic, T1 not fused', 339.69589186654474, 'normal', 0.0, 'normal', 1.0055059752791893, 0.9909185838067048, 0.9629700439810648], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 25.95, 'abnormal', 'T1 not fused, cranial sutures open', 1003.1673196390044, 'abnormal', 0.2564659313631298, 'abnormal', 1.0251852489440696, 0.9638408977220062, 0.9461626553080708], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.53, 'normal', None, 304.8330955707476, 'normal', 0.0, 'normal', 1.0095791915249066, 0.9845520975937324, 0.9645697053350472], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.74, 'normal', 'pectus excavatum', 367.261363069227, 'normal', 0.0006917489719841, 'normal', 1.0110774504712408, 1.0043809346587718, 0.970644327557358], ['female', 'Ptprz1', 'c287', datetime.date(2023, 5, 9), 26.41, 'abnormal', 'LHp II. Osteoneogenesis, cranial sutures open', 707.2662162681384, 'normal', 0.0009031167134237, 'normal', 1.0053455414978367, 0.9834464897969856, 0.9538151450700398], ['female', 'Casp8', 'c287', datetime.date(2023, 5, 9), 26.0, 'abnormal', 'T1 not fused, sternum crooked mildly, cranial sutures open mildly, frontal + parietal bones soft', 1019.153984892894, 'abnormal', 0.2373275431382345, 'abnormal', 1.0082413384889155, 0.9527099963706536, 0.9283329762352532], ['male', 'Cer1', 'c287', datetime.date(2023, 5, 9), 26.94, 'abnormal', 'T1 not fused, kyphosis, RHp II. Osteoneogenesis, cranial sutures open', 587.8368073764768, 'normal', 0.0026132738941624, 'normal', 1.0163105255530087, 1.0114964385336496, 0.9850121732372183], ['male', 'Cobll1', 'c287', datetime.date(2023, 5, 9), 26.49, 'normal', 'L6 = half S0, kyphosis, pectus excavatum, LHp II. Osteoneogenesis', 461.1182457007968, 'normal', 3.8430498443564814e-05, 'normal', 1.0039214085782393, 0.9829593638656026, 0.9502370560928856], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.92, 'abnormal', 'kyphosis, cranial sutures open', 926.1397445010948, 'normal', 0.0355289958110756, 'normal', 1.0373419457580768, 0.9838956143953628, 0.977420069327094], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.33, 'normal', None, 433.5940649573164, 'normal', 0.0012489911994158, 'normal', 1.014313354490046, 0.9949502081673084, 0.9630522078864012], ['male', 'Ptprz1', 'c287', datetime.date(2023, 5, 9), 26.5, 'abnormal', 'T1 not fused, kyphosis, pectus excavatum, cranial sutures open', 719.0719965283737, 'normal', 0.0194842627108873, 'normal', 1.026994757797104, 0.9788771848416504, 0.9424215937604488], ['male', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 26.88, 'normal', 'pectus excavatum', 504.8569713280969, 'normal', 0.0, 'normal', 1.0149516479423752, 0.9852590433912826, 0.9584564136324014], ['female', 'C57Bl/6NCrl', 'c287', datetime.date(2023, 5, 9), 25.95, 'abnormal', 'cranial sutures open', 442.6773710876005, 'normal', 0.0008262557165366, 'normal', 0.9978158940915892, 0.9713012258015504, 0.9376182115324142]]
[['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.46, 'normal', None, 669.1828709649858, 'normal', 0.0144306521655585, 'normal', 1.012780119383749, 0.9880352935355352, 0.9684441210777108], ['male', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.29, 'normal', None, 619.2926318770096, 'normal', 0.0045347988163406, 'normal', 1.0047071422220288, 0.9797437885375372, 0.9706073724420424], ['female', 'Tcaf2', 'c256', datetime.date(2022, 9, 19), 26.02, 'abnormal', 'T1 not fused, cranial sutures open', 672.9810705722432, 'normal', 0.0229814380692517, 'normal', 1.0023712296238354, 0.9745442839874195, 0.9430459813052892], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.34, 'normal', 'T1 not fused', 485.3092130525473, 'normal', 0.0071672879597248, 'normal', 1.0151393212589603, 1.0031485924259569, 0.9685205596430304], ['female', 'Tcaf2', 'c256', datetime.date(2022, 9, 19), 25.94, 'normal', None, 927.7868961084598, 'normal', 0.0644671611390799, 'normal', 1.0129917714696464, 0.976067066140226, 0.9246850672564184], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.3, 'normal', 'T1 not fused', 1533.0100693251072, 'abnormal', 0.0092809653741209, 'normal', 0.9854033052021238, 0.9671239776442716, 0.9552963997500636], ['male', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 27.03, 'normal', 'T1 not fused', 341.32331425021664, 'normal', 0.0015948656854079, 'normal', 1.005723669003625, 0.993261481501883, 0.9843543253140108], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 24.74, 'abnormal', 'T1 not fused, C7 left rib, rostrum crooked', 3918.956620314477, 'abnormal', 0.4823988317128473, 'abnormal', 1.0224813373753217, 0.965000257538806, 0.9474161171981228], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.13, 'normal', 'T1 not fused', 432.6932838961758, 'normal', 0.0, 'normal', 1.01454490394277, 1.0000104895312043, 0.9726672353374324], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 25.9, 'normal', 'T1 not fused', 399.9086586212162, 'normal', 0.0, 'normal', 1.0330833846115195, 0.9996417515038362, 0.958352775903568], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.41, 'normal', 'kyphosis', 554.5009743199129, 'normal', 0.0069174897198416, 'normal', 1.0130668815934618, 0.9731022549519142, 0.95820637317697], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.77, 'normal', 'T1 not fused', 647.1649977488061, 'normal', 0.0198301371968794, 'normal', 1.0285209443302663, 1.0105823902314313, 0.969841023729364], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.05, 'normal', None, 405.91397635512806, 'normal', 0.0006533184735406, 'normal', 1.026742970403345, 1.018128949824946, 0.9913310729939038], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 27.39, 'normal', None, 455.65894564313567, 'normal', 0.0002690134891049, 'normal', 1.0382833112681018, 0.9907545595139032, 0.9635765954551768], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 27.71, 'normal', None, 316.8295890523748, 'normal', 0.0, 'normal', 1.0476369912965222, 1.0127782853044554, 0.980775722245831], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.38, 'normal', 'T1 not fused', 366.652501077162, 'normal', 0.0030552246262634, 'normal', 1.0639018422892577, 1.0121311686220236, 0.982489596772762], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.36, 'normal', 'T1 not fused', 472.8856598785935, 'normal', 0.0002113677414396, 'normal', 0.9951549963047756, 0.9744868539378924, 0.9379243787379492], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 27.24, 'normal', None, 505.4609863412085, 'normal', 0.0340109911225548, 'normal', 1.042263148847194, 1.0395410914366543, 1.008779603892396], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.7, 'abnormal', 'T1 not fused, cranial sutures open', 453.0244563926691, 'normal', 0.0004035202336574, 'normal', 0.9950142145758396, 0.9860396532286912, 0.9561293330720564], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 25.41, 'normal', None, 404.7210858012887, 'normal', 0.0005764574766534, 'normal', 1.0054727803481158, 0.9633998715992212, 0.9495497247101355], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 25.41, 'normal', 'T1 not fused', 476.68312127396166, 'normal', 0.0, 'normal', 0.9997193183557976, 0.9796165835364992, 0.9496896798116586], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 27.88, 'normal', None, 577.367447294892, 'normal', 0.0008262557165366, 'normal', 0.99653908545603, 0.9832855205208744, 0.9618417709418502], ['male', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.87, 'normal', 'shorter tail, pectus excavatum; CA22+', 559.914221980439, 'normal', 0.0099342838476615, 'normal', 1.0183623565211075, 0.9843178191241474, 0.9608087961075256], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.42, 'normal', None, 660.2955102436874, 'normal', 0.0246531647515468, 'normal', 1.027518590279654, 0.985384710528704, 0.9693587935583716], ['male', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.22, 'normal', None, 376.3930776926372, 'normal', 0.0003843049844356, 'normal', 1.00636617215904, 0.9848816956550752, 0.949262715277729], ['male', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.68, 'normal', 'L6=half S0, pectus excavatum', 551.1550184415254, 'normal', 0.0156988586141962, 'normal', 1.0494568253567305, 1.012442956906596, 0.9874315249988314], ['female', 'C57Bl/6NCrl', 'c256', datetime.date(2022, 9, 19), 26.77, 'normal', 'T1 not fused, PS missing, tendond ossification', 327.68010432656763, 'normal', 0.0015372199377425, 'normal', 1.0244510364014106, 1.0056386116281792, 0.9699493635122264], ['female', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.42, 'normal', None, 416.8079976838673, 'normal', 0.0009223319626455, 'normal', 0.9982333611345924, 0.9848324435297204, 0.965521703506944], ['male', 'Cobll1', 'c256', datetime.date(2022, 9, 19), 26.55, 'normal', None, 375.81336637976506, 'normal', 0.0, 'normal', 1.0234921967997228, 1.0167714279668656, 0.9800000560873168]]

[['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.38, 'normal', 'scoliotic mild', 359.8624054112446, 'normal', 0.0002113677414396, 'normal', 1.001081917283106, 0.9819665510508606, 0.9593090516784196], ['male', 'Ism1', 'c294', datetime.date(2023, 6, 26), 24.14, 'abnormal', 'kyphosis, L3 + L4 fused together, shorter rostrum + rostrum malformation + cranial sutures open', 3625.5491729400783, 'abnormal', 0.4524999039237539, 'abnormal', 1.0331714934081917, 0.9985673737015766, 0.9347448000510372], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.7, 'normal', None, 327.8942117945616, 'normal', 0.0002497982398831, 'normal', 1.017645446086858, 0.9854763342629828, 0.9732324265883469], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.59, 'normal', 'scoliotic, kyphosis mild', 641.3133170259279, 'normal', 0.0035356058568079, 'normal', 1.0318667137779376, 0.9941172598626684, 0.9804018537093148], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.99, 'normal', None, 618.3758642036338, 'normal', 0.0092617501248991, 'normal', 1.0105196672049863, 0.9886182889219248, 0.9557893818790084], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.26, 'normal', 'pectus excavatum', 662.1012931253466, 'normal', 0.0171976480534952, 'normal', 1.0180262293513909, 0.9685537437291588, 0.9518497407007412], ['female', 'Ces1c', 'c294', datetime.date(2023, 6, 26), 25.93, 'abnormal', 'T1 not fused, cranial sutures open + shorter rostrum', 790.6692099065186, 'normal', 0.008646862149802, 'normal', 1.012777551432498, 0.9932066230078808, 0.9723390898242534], ['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.81, 'normal', None, 519.8980341725054, 'normal', 0.0052841935359901, 'normal', 1.0091178732465855, 1.0000765093352575, 0.988452248485559], ['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.31, 'abnormal', 'cranial sutures open', 443.0197285079026, 'normal', 0.0001537219937742, 'normal', 0.9989796570286676, 0.9852068023875972, 0.9557427034661274], ['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 27.38, 'normal', None, 453.0226547389125, 'normal', 0.0, 'normal', 1.001954458925842, 0.9946081766597432, 0.969144897318404], ['male', 'Ces1c', 'c294', datetime.date(2023, 6, 26), 26.49, 'normal', None, 416.4225511157878, 'normal', 0.0002305829906613, 'normal', 1.023830644085385, 0.9989232405741832, 0.9785493357297336], ['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.69, 'normal', None, 426.6733032194068, 'normal', 0.0015372199377425, 'normal', 1.0162190384975929, 0.988718249935396, 0.9859556646115972], ['female', 'Ism1', 'c294', datetime.date(2023, 6, 26), 24.53, 'abnormal', 'scoliotic mild, shorter rostrum + rostrum malformation + cranial sutures open', 2436.2673494962587, 'abnormal', 0.1774336113139387, 'abnormal', 1.0141401164705215, 0.9965278706095894, 0.9476099801842915], ['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.58, 'normal', 'LHp II. osteoneogenesis', 435.4703521612728, 'normal', 0.0052457630375465, 'normal', 1.0021847448148669, 0.9748736234089724, 0.961626330463536], ['female', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.11, 'abnormal', 'cranial sutures open mild', 501.0874538784538, 'normal', 0.0, 'normal', 0.9938906825312362, 0.9926360923191496, 0.9739485533106896], ['female', 'Ces1c', 'c294', datetime.date(2023, 6, 26), 27.96, 'abnormal', 'cranial sutures open', 718.9235558019199, 'normal', 0.032320049191038, 'normal', 1.0126583205469708, 0.9967195625459468, 0.9899180753952812], ['male', 'Ces1c', 'c294', datetime.date(2023, 6, 26), 26.2, 'normal', None, 400.27292522583554, 'normal', 1.9215249221782407e-05, 'normal', 1.0157882992022884, 0.992689497076127, 0.9633515900626004], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.6, 'normal', None, 260.2189495534761, 'normal', 0.0, 'normal', 1.0177235696992362, 0.9924488907947128, 0.96749483504354], ['female', 'Ces1c', 'c294', datetime.date(2023, 6, 26), 26.01, 'abnormal', 'cranial sutures open', 438.5852064573132, 'normal', 0.0028822873832673, 'normal', 0.9894761212766368, 0.976367207081834, 0.9421512472114156], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.58, 'normal', 'T1 not fused, pectus excavatum', 503.3725783368519, 'normal', 0.0, 'normal', 0.9913952608122076, 0.9801171781912292, 0.9627595884628988], ['male', 'C57Bl/6NCrl', 'c294', datetime.date(2023, 6, 26), 26.65, 'normal', 'L6 = S0, pectus excavatum', 317.5654767792595, 'normal', 3.8430498443564814e-05, 'normal', 1.0345151323120636, 0.989551036496498, 0.9861944771195056], ['male', 'Ism1', 'c294', datetime.date(2023, 6, 26), 24.94, 'abnormal', 'shorter rostrum + rostrum malformation + cranial sutures open', 1956.3358708940011, 'abnormal', 0.3010645248068867, 'abnormal', 1.0683975499365868, 1.0328830079330256, 0.9458786532865876]]
[['female', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.63, 'abnormal', 'cranial sutures open mild', 472.07610741133993, 'normal', 0.0003650897352138, 'normal', 1.0159760291722435, 1.002438708315081, 0.9802656845167596], ['male', 'Dis3l', 'c293', datetime.date(2023, 6, 19), 26.53, 'normal', 'T1 not fused, C7 process abnormal', 428.2796292172444, 'normal', 0.0009031167134237, 'normal', 1.0347603773521348, 0.987653604518889, 0.9663732449272956], ['female', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 25.99, 'abnormal', 'cranial sutures open', 454.4370884036089, 'normal', 1.9215249221782407e-05, 'normal', 0.9952997316823724, 0.9823640658436508, 0.9498935125439124], ['male', 'Dis3l', 'c293', datetime.date(2023, 6, 19), 26.82, 'normal', None, 323.56649861133934, 'normal', 0.0, 'normal', 1.0268185189556711, 1.004423446804609, 0.9783383667752968], ['male', 'Dis3l', 'c293', datetime.date(2023, 6, 19), 26.46, 'normal', 'scoliotic mild, T1 not fused', 646.8689053663007, 'normal', 0.0079551131778179, 'normal', 1.0199783908068425, 0.9941898172834168, 0.9629266065897708], ['male', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.43, 'normal', 'LHp II. osteoneogenesis', 422.0486899521031, 'normal', 0.0, 'normal', 1.0333370245621607, 0.9929376941560066, 0.9791087130344478], ['male', 'Dis3l', 'c293', datetime.date(2023, 6, 19), 26.57, 'normal', 'kyphosis', 503.6934625426703, 'normal', 1.9215249221782407e-05, 'normal', 1.0436505974529402, 1.007511987285395, 0.9813820222360056], ['female', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.52, 'normal', 'T1 not fused', 633.0067447198572, 'normal', 0.9316705737673416, 'abnormal', 1.3093167064865938, 1.052981930456332, 0.9095143606160778], ['male', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.75, 'normal', None, 380.27148625385416, 'normal', 0.0, 'normal', 1.02339683181423, 0.9997789154209472, 0.9882189645157028], ['male', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.66, 'normal', None, 351.5398628233402, 'normal', 0.0, 'normal', 1.0330166120635864, 1.005407484926148, 0.962840441823113], ['female', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.37, 'normal', 'kyphosis', 418.0257632885549, 'normal', 0.0011913454517505, 'normal', 1.0208149261610775, 1.0010814071644474, 0.9938237569426606], ['male', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.48, 'normal', 'T1 not fused, kyphosis', 385.3102608346105, 'normal', 0.000172937242996, 'normal', 1.0098550685001009, 1.002376721201528, 0.9750176547877114], ['female', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 25.94, 'normal', 'T1 not fused, kyphosis', 451.9535331412034, 'normal', 0.0061873102494139, 'normal', 1.029485709975771, 0.9983207436472228, 0.9819493494807418], ['male', 'Nkiras1', 'c293', datetime.date(2023, 6, 19), 25.96, 'normal', 'cranial sutures open very mild (not scored)', 736.9356518731755, 'normal', 0.0301871565274201, 'normal', 1.0056189128938282, 0.980753874148266, 0.9456785684058312], ['male', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.91, 'normal', None, 390.3020471894232, 'normal', 0.0002497982398831, 'normal', 1.0312624661662098, 1.009723164695942, 0.9758425740275012], ['male', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.86, 'normal', 'T1 not fused, pectus excavatum, kyphosis', 589.0631238794725, 'normal', 0.0025940586449406, 'normal', 1.0221179910716311, 1.004412789797568, 0.9925393322901066], ['male', 'Dis3l', 'c293', datetime.date(2023, 6, 19), 26.78, 'normal', 'T1 not fused, C5 + C6 fused together, left C7 rib rudiment', 424.6842600835985, 'normal', 0.0002113677414396, 'normal', 1.0143206255140271, 1.0089009828159754, 0.9792032403605676], ['male', 'Dis3l', 'c293', datetime.date(2023, 6, 19), 26.64, 'abnormal', 'T1 not fused + extra thoracic process, left C7 rib rudiment, costal cartilages doubled, cranial sutures open mild', 590.1548132106158, 'normal', 0.0124130509972714, 'normal', 1.0347167009995408, 1.0210972774832745, 0.9602256067347422], ['female', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.14, 'abnormal', 'scoliotic, cranial sutures open', 419.7952986531884, 'normal', 0.0003650897352138, 'normal', 1.0101506555055513, 0.9925845299464906, 0.9643314952775676], ['male', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.4, 'normal', 'kyphosis, pectus excavatum severe', 820.8596240804637, 'normal', 0.0256715729603012, 'normal', 1.0147273446351832, 0.9905805083973812, 0.943476756102071], ['male', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.65, 'normal', 'kyphosis, pectus excavatum mild', 318.3995732508658, 'normal', 0.0012874216978594, 'normal', 1.0473445958762757, 1.0097834682103508, 0.9802423138909304], ['male', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.56, 'normal', 'T1 not fused', 412.8150368175295, 'normal', 0.0003650897352138, 'normal', 1.0115574997617278, 0.9870891356371222, 0.9610741293039328], ['male', 'psKlcs', 'c293', datetime.date(2023, 6, 19), 26.71, 'normal', 'T1 not fused, kyphosis', 362.4845301318132, 'normal', 5.764574766534722e-05, 'normal', 1.0422717194064386, 1.0290823561971765, 0.9912622356025402], ['male', 'Nkiras1', 'c293', datetime.date(2023, 6, 19), 27.31, 'abnormal', 'cranial sutures open', 425.55443657781086, 'normal', 0.0, 'normal', 1.04749022724396, 1.0056194644051228, 0.9933406401261574], ['female', 'C57Bl/6NCrl', 'c293', datetime.date(2023, 6, 19), 26.55, 'normal', None, nan, nan, nan, nan, nan, nan, nan]]

[['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.53, 'normal', 'L6= S0, pectus excavatum', 457.1645316956384, 'normal', 0.0005572422274316, 'normal', 1.022849748012865, 0.9879840039496842, 0.9645484267909828], ['male', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 26.91, 'normal', None, 457.1057958031304, 'normal', 0.0055724222743168, 'normal', 1.0227810850621395, 0.9897298815466876, 0.9748706869148236], ['female', 'Rnf34 tm1b', 'c268', datetime.date(2022, 12, 12), 26.05, 'normal', None, 779.7608049973167, 'normal', 0.0161023788478536, 'normal', 0.9881791871680056, 0.9797735915924743, 0.942594967966463], ['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.62, 'normal', 'T1 not fused, L6= S0', 478.5233384257646, 'normal', 0.0066100457322931, 'normal', 1.0294086880718676, 1.0059118794563202, 0.9649572905811148], ['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.49, 'normal', 'T1 not fused, pectus excavatum mild', 543.4577054818355, 'normal', 0.0019023096729564, 'normal', 1.0062715004587834, 0.9801091029843512, 0.9548773856196524], ['male', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 27.09, 'normal', 'T1-T2 transposed+PS doubled, left C7 rib, L6=half S0', 449.6594724582432, 'normal', 0.0, 'normal', 1.0323080600817185, 0.9934024291892416, 0.9714262488915856], ['female', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 24.51, 'abnormal', 'rostrum malformation', 3691.516928616199, 'abnormal', 0.6696706506283386, 'abnormal', 1.0124161678660537, 0.978882934018342, 0.926057475677198], ['female', 'Cpm', 'c268', datetime.date(2022, 12, 12), 26.79, 'normal', 'T1 not fused', 619.9812504845423, 'normal', 0.0015564351869643, 'normal', 1.0272058038996887, 0.9879321900383804, 0.9703180824669296], ['male', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 26.99, 'normal', 'T1-T2 transposed+T1 not fused, pectus excavatum', 626.5721603616117, 'normal', 0.0073978709503862, 'normal', 1.0157147241761528, 0.9761976782900404, 0.94955478087941], ['male', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 26.5, 'normal', 'scoliotic, T1 not fused, left C7 rib', 711.6833267277689, 'normal', 0.0114330732869605, 'normal', 1.0180877403107638, 0.992386796492909, 0.9511871716091034], ['male', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 26.16, 'normal', 'T1 not fused', 545.4810756720506, 'normal', 0.0082241266669228, 'normal', 1.028423260237154, 1.003194416410052, 0.9675846448053528], ['male', 'Zim1', 'c268', datetime.date(2022, 12, 12), 26.51, 'normal', 'scoliosis + kyphosis severe', 496.0173648505192, 'normal', 0.0075708081933822, 'normal', 1.02111957217004, 0.993933878422739, 0.959322190925634], ['female', 'Zim1', 'c268', datetime.date(2022, 12, 12), 26.76, 'normal', None, 690.290428934619, 'normal', 0.0042081395795703, 'normal', 1.0097286473656102, 0.9817020990516524, 0.9785809417882726], ['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.56, 'normal', 'L6= S0, pectus excavatum', 678.1666695905466, 'normal', 9.607624610891204e-05, 'normal', 1.0131667381242195, 1.0013994873961078, 0.9900532351048076], ['male', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 26.35, 'normal', None, 588.6859520751146, 'normal', 0.0070712117136159, 'normal', 1.008520770587197, 0.9861763991782394, 0.9701981082194356], ['female', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 26.16, 'normal', 'T1 not fused', 431.8710376616006, 'normal', 0.0015564351869643, 'normal', 0.9913315978047992, 0.9741032632572054, 0.9424491465338845], ['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.97, 'normal', None, 598.2912990808633, 'normal', 0.0030552246262634, 'normal', 1.0134544626076092, 0.9947111606662832, 0.9635535839979475], ['female', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 26.35, 'normal', 'T1 not fused, left C7 process abnormal', 416.57556642641526, 'normal', 0.0, 'normal', 1.013277932145075, 0.9689607809651544, 0.9352276415253796], ['female', 'Zim1', 'c268', datetime.date(2022, 12, 12), 25.62, 'normal', 'T1-T2 transposed+PS doubled', 687.2501092413914, 'normal', 0.0071096422120594, 'normal', 0.9974254826846572, 0.9349535897704468, 0.9181798015924348], ['male', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 27.15, 'normal', 'T1 not fused, PS missing, , pectus excavatum severe', 533.7723903411027, 'normal', 0.0078974674301525, 'normal', 1.010293752205324, 0.9869859756323882, 0.9422629936901136], ['female', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 25.78, 'normal', 'kyphosis', 696.6134069595355, 'normal', 0.0068982744706198, 'normal', 0.9890674015657982, 0.9846261929427446, 0.9411078427184172], ['female', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 26.63, 'normal', None, 411.8240073132592, 'normal', 0.0004995964797663, 'normal', 1.0236988654475214, 0.9851690891901724, 0.9734644511411013], ['female', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 25.83, 'normal', 'T1 not fused', 1036.147922968803, 'abnormal', 0.0467699166058183, 'normal', 0.9989196876628936, 0.9611203727455252, 0.948631674220717], ['male', 'Cst6', 'c268', datetime.date(2022, 12, 12), 26.86, 'normal', 'T1 not fused, L6=half S0', 554.649484629237, 'normal', 0.001056838707198, 'normal', 1.033654683316381, 1.003847743872046, 0.9815775896197834], ['female', 'Hcls1', 'c268', datetime.date(2022, 12, 12), 27.0, 'normal', 'T1 not fused, PS missing', 480.6005557377176, 'normal', 0.0017485876791821, 'normal', 1.0305552594854464, 0.9892653708199776, 0.9672491784861372], ['female', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 25.8, 'normal', None, 445.4270612189716, 'normal', 0.0001152914953306, 'normal', 1.0098760530327742, 0.9773218852107002, 0.9552451799614642], ['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.68, 'normal', None, 747.7166657672045, 'normal', 0.0284577840974597, 'normal', 0.9965627781643884, 0.987156548552754, 0.9388443282223428], ['female', 'C57Bl/6NCrl', 'c268', datetime.date(2022, 12, 12), 26.52, 'normal', 'T1 not fused, hindpaws moved', 608.7487822093773, 'normal', 0.0048038123054456, 'normal', 1.003733732085788, 0.98475597453513, 0.9553311570062014], ['male', 'Rnf34 tm1b', 'c268', datetime.date(2022, 12, 12), 26.68, 'normal', None, 440.8168598747261, 'normal', 0.003170516121594, 'normal', 1.007261166945716, 0.966575589229402, 0.9616695908404772], ['male', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.82, 'normal', 'T1 not fused + T1 extra process', 1031.4074910695242, 'abnormal', 0.1279351293186272, 'abnormal', 1.0652994363639234, 1.013448217407921, 0.9921792091195551], ['female', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.08, 'normal', 'T1 not fused', 836.6294621021653, 'normal', 0.0134891049536912, 'normal', 1.0046140359755855, 0.979981550572902, 0.9468582716966596], ['male', 'Cst6', 'c268', datetime.date(2022, 12, 12), 26.35, 'normal', None, 501.1443379408432, 'normal', 0.000345874485992, 'normal', 1.0022053430104882, 0.9817177711542868, 0.9415814178620142], ['female', 'Ppp3cb', 'c268', datetime.date(2022, 12, 12), 26.5, 'normal', 'T1 not fused, L6=half S0', 642.200992955566, 'normal', 0.0049959647976634, 'normal', 1.0256636879344858, 0.9744101836742576, 0.9534785125237224]]
[['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 25.51, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 719.4976303331607, 'normal', 0.0395641981476499, 'normal', 1.004102761717147, 0.9739412991498322, 0.9602930597251188], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.96, 'normal', None, 406.99945352349965, 'normal', 0.0002690134891049, 'normal', 1.0473617320486408, 1.0153601541417998, 0.99404770773133], ['female', 'Tppp3', 'c291', datetime.date(2023, 6, 5), 26.78, 'normal', 'T1 not fused, pectus excavatum', 614.1178508279007, 'normal', 0.0074363014488297, 'normal', 1.0056954787618473, 0.9836049235271452, 0.9669905406691937], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 27.14, 'abnormal', 'cranial sutures open', 644.9594476392787, 'normal', 0.0181776257638061, 'normal', 1.00659523417756, 1.003042362456828, 0.9903900845663406], ['male', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 26.74, 'normal', 'T1 not fused', 423.9606509078381, 'normal', 0.0010184082087544, 'normal', 1.0150173251411083, 0.9639767380834148, 0.9546513693303584], ['female', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 25.32, 'abnormal', 'shorter rostrum, cranial sutures open', 621.5089357571965, 'normal', 0.014834172399216, 'normal', 0.9842043607217232, 0.9527707884796132, 0.8955393107885768], ['male', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 28.18, 'normal', None, 469.9058494339344, 'normal', 0.0004803812305445, 'normal', 1.0059561351766089, 0.9980451277222158, 0.970143112960972], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 28.12, 'normal', 'T1 not fused, shorter tail', 463.9605097616724, 'normal', 0.0003266592367703, 'normal', 1.0304162929801055, 0.9995331008196302, 0.985925812836431], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.99, 'normal', 'T1 not fused', 586.2599822020106, 'normal', 0.001498789439299, 'normal', 1.0144005189604837, 0.9951661832968952, 0.971579663413516], ['female', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 27.09, 'abnormal', 'cranial sutures open', 433.3878658705968, 'normal', 0.002113677414396, 'normal', 1.002800507406144, 0.9890865159632876, 0.9660425285833024], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.96, 'normal', None, 608.065576557289, 'normal', 0.0220014603589408, 'normal', 1.0310423003602256, 1.0199906307113733, 0.9766982421161304], ['male', 'Tppp3', 'c291', datetime.date(2023, 6, 5), 26.02, 'normal', 'scoliotic', 432.48887298644667, 'normal', 0.0017293724299604, 'normal', 1.0087440891757369, 0.9881590645553702, 0.9499134739938114], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 27.34, 'normal', None, 407.3362613115355, 'normal', 0.0056684985204258, 'normal', 1.012377349178031, 1.0026856927044308, 0.989819041604642], ['female', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 26.85, 'abnormal', 'cranial sutures open', 414.1140173949044, 'normal', 0.0, 'normal', 1.000090925396904, 0.9715561218833472, 0.963719183090448], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.84, 'normal', None, 666.7900052286807, 'normal', 0.0666961300488067, 'normal', 1.0703275319354335, 1.0077153277871274, 0.9883680135293836], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 27.92, 'abnormal', 'scoliotic, kyphosis, T1 not fused, cranial sutures open, ossi frontale + parietale soft, enamel lower', 676.6684668670479, 'normal', 0.0158525806079704, 'normal', 1.0140039538997452, 0.9907526439095656, 0.9481050421905284], ['male', 'Tppp3', 'c291', datetime.date(2023, 6, 5), 26.43, 'normal', 'T1 not fused, kyphosis', 847.9033388170207, 'normal', 0.0411782790822796, 'normal', 1.0048939969295765, 0.9744753260880265, 0.9446506401589668], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 27.44, 'abnormal', 'lordosis, cranial sutures open', 446.2234358945847, 'normal', 0.0254794204680834, 'normal', 1.0169892872514776, 1.001831127060792, 0.9622969507277458], ['female', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 27.72, 'normal', 'sternum crooked', 599.760125392247, 'normal', 0.0021521079128396, 'normal', 1.012450939528378, 0.9895699245927964, 0.9834937735057953], ['male', 'Gcnt1', 'c291', datetime.date(2023, 6, 5), 26.98, 'normal', 'Processus spinosus missing', 631.4961016190908, 'normal', 0.0249990392375389, 'normal', 1.0244261085802242, 0.9966183757150152, 0.9763410953077448], ['female', 'Tppp3', 'c291', datetime.date(2023, 6, 5), 26.81, 'normal', 'T1 not fused', 729.9377943264789, 'normal', 0.0142769301717843, 'normal', 1.0043391215487738, 0.991377875732412, 0.977668311002032], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.01, 'normal', 'T1 not fused, kyphosis mild', 415.1241051647142, 'normal', 0.0, 'normal', 1.0212513012076805, 0.9782937325592802, 0.9592414051568594], ['male', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 26.89, 'normal', 'pectus excavatum severe', 505.739887703857, 'normal', 0.0029399331309327, 'normal', 1.018430797953541, 0.983081524035028, 0.9666517920971496], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 27.07, 'abnormal', 'T1 not fused, cranial sutures open', 1165.7212069356117, 'abnormal', 0.256004765381807, 'abnormal', 1.0205170846061908, 0.9907870575496968, 0.962897573578774], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 27.41, 'normal', None, 534.2612807158565, 'normal', 0.0018638791745128, 'normal', 1.020541913490841, 1.006410842626901, 0.9733792952082214], ['male', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.71, 'normal', 'scoliotic, kyphosis, Processus spinosus missing', 523.961917507884, 'normal', 0.0026132738941624, 'normal', 1.0188731744318118, 0.9940158340230086, 0.9628232187700352], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 26.28, 'abnormal', 'cranial sutures open', 394.11391021801575, 'normal', 0.0, 'normal', 0.9933573936391628, 0.9793552487880172, 0.9531720929089662], ['female', 'HHAT', 'c291', datetime.date(2023, 6, 5), 25.97, 'normal', 'scoliotic', 399.8344888245916, 'normal', 0.0004803812305445, 'normal', 1.0094307711728805, 0.9982782295731902, 0.9725741829487102], ['male', 'C57Bl/6NCrl', 'c291', datetime.date(2023, 6, 5), 26.85, 'normal', None, 522.495394307795, 'normal', 0.0030936551247069, 'normal', 1.0141977413982426, 0.9876843475678526, 0.9682332196809064]]
[['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c272', datetime.date(2023, 1, 9), 25.23, 'normal', None, 590.0932672928765, 'normal', 0.0028630721340455, 'normal', 0.9896981658878318, 0.9398198377058344, 0.9225071645588132], ['female', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 27.37, 'normal', None, 349.4095111574237, 'normal', 0.0001921524922178, 'normal', 1.0067833870994736, 0.9925981988958178, 0.9823586481095754], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c272', datetime.date(2023, 1, 9), 26.75, 'normal', None, 371.7687473956132, 'normal', 0.0005764574766534, 'normal', 1.0043563879018969, 0.975305529381964, 0.9467568244933772], ['male', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 26.94, 'normal', None, 284.29568654717366, 'normal', 0.0, 'normal', 1.0300589824184394, 1.0027656887016736, 0.990000062602352], ['male', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.39, 'abnormal', None, 1948.7440492648157, 'abnormal', 0.3016025517850966, 'abnormal', 1.0486896229695444, 0.9745054516738793, 0.9478910381358394], ['female', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.52, 'abnormal', None, 1668.2770875619128, 'abnormal', 0.0317435917143845, 'normal', 0.998319245027219, 0.9749622157186952, 0.9701328892293536], ['female', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 27.11, 'abnormal', None, 586.5417531917763, 'normal', 0.0005956727258752, 'normal', 1.0161672617064874, 0.991443120539989, 0.952059550365028], ['male', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.99, 'abnormal', None, 1387.6970405005482, 'abnormal', 0.0457707236462856, 'normal', 0.9958386905641304, 0.978136388785236, 0.9650837379702312], ['female', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.64, 'abnormal', None, 884.4326826073421, 'normal', 0.9335536681910764, 'abnormal', 1.163507321286941, 1.032965984578805, 0.7776028043984492], ['female', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.15, 'abnormal', None, 2721.7936810619003, 'abnormal', 0.6765881403481803, 'abnormal', 1.2027022962629033, 0.995748690294138, 0.9483911270420188], ['male', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 27.36, 'abnormal', None, 522.6859957084306, 'normal', 0.000172937242996, 'normal', 1.0306575101835216, 1.017848508509233, 0.9790045787726784], ['male', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 27.36, 'abnormal', None, 1082.842778377731, 'abnormal', 0.0312247799853964, 'normal', 1.003593700262421, 0.989048360037928, 0.9627102298721276], ['male', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.32, 'abnormal', None, 1727.9913463637974, 'abnormal', 0.0958264478690288, 'normal', 1.0227976144296225, 1.0143699037041662, 0.9608361373184646], ['female', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.77, 'abnormal', None, 1156.688795310873, 'abnormal', 0.0631028784443334, 'normal', 1.044724646642918, 1.007859768237371, 0.9799623649110892], ['male', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 26.66, 'normal', None, 558.8705085192851, 'normal', 0.0034203143614772, 'normal', 1.027565317175062, 0.992381595351495, 0.9866008023492792], ['female', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 26.75, 'normal', None, 330.8453102735692, 'normal', 0.0, 'normal', 1.026456960704071, 1.0010515883544688, 0.983143116916738], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c272', datetime.date(2023, 1, 9), 27.01, 'normal', None, 338.12471102722657, 'normal', 0.0037469735982475, 'normal', 1.057469911724613, 1.0056407361745543, 0.9919502599917438], ['male', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.29, 'abnormal', None, 1756.83536298612, 'abnormal', 0.0773221628684524, 'normal', 1.0176644812378746, 0.9672570582637692, 0.9563980984633632], ['female', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 27.17, 'abnormal', None, 515.6871442746707, 'normal', 0.0443487952038737, 'normal', 1.0721250498650103, 0.9978382822460464, 0.9678391878153936], ['female', 'Enpp1', 'c272', datetime.date(2023, 1, 9), 26.5, 'abnormal', None, 1917.283209365717, 'abnormal', 0.0407555435994004, 'normal', 1.0139769524792217, 0.9843606296119388, 0.97180308983673], ['male', 'C57Bl/6NCrl', 'c272', datetime.date(2023, 1, 9), 26.67, 'abnormal', None, 585.8701785383364, 'normal', 0.0030360093770416, 'normal', 1.0012599402918696, 0.985866114506884, 0.974495260701271]]

[]
[['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.7, 'abnormal', 'cranial sutures open', 318.42245177481936, 'normal', 1.9215249221782407e-05, 'normal', 1.0363717059474484, 1.0001623324319149, 0.9665739193996076], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.46, 'abnormal', 'sternum malformed, cranial sutures open', 936.0239821340656, 'normal', 0.274816494369932, 'abnormal', 1.015648005140204, 1.0138489369828287, 0.939332143337608], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.26, 'normal', 'T1 not fused', 364.6423583189223, 'normal', 0.0, 'normal', 0.9936961752616728, 0.9891687128625192, 0.9677214471540077], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.24, 'normal', 'T1 not fused, kyphosis', 534.8955965497622, 'normal', 0.0314937934745013, 'normal', 1.020700818535168, 0.9971458111345666, 0.9720783914451944], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 25.04, 'normal', 'kyphosis', 465.6115118778437, 'normal', 0.0048998885515545, 'normal', 1.0096703404782916, 1.0053312482952004, 0.9628391075187036], ['female', 'C57Bl/6NCrl', 'c286', datetime.date(2023, 5, 2), 27.17, 'abnormal', 'L6 = S0, cranial sutures open', 613.1786005455991, 'normal', 0.007859036931709, 'normal', 1.0214181135983844, 1.0010196877623836, 0.9600552089593274], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.18, 'abnormal', 'T1 not fused, scoliotic, RHP II. Osteoneogenesis, cranial sutures open', 624.464641299311, 'normal', 0.0015948656854079, 'normal', 0.9869850443599004, 0.9734046314807469, 0.9371460617316956], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.13, 'normal', 'pectus excavatum, tendon ossification', 702.3173859148316, 'normal', 0.0308789054994043, 'normal', 1.0344054431333194, 1.0050002259483268, 0.9783500791028208], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.27, 'normal', 'T1 not fused, LHP II. Osteoneogenesis', 461.93742612864384, 'normal', 0.0002882287383267, 'normal', 1.0179849501672844, 0.9833588890321108, 0.9610667573726656], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 25.66, 'normal', 'scoliotic + kyphosis', 451.7844345318464, 'normal', 0.0033050228661465, 'normal', 0.9912220650701782, 0.9758156224923116, 0.9565120234896468], ['male', 'C57Bl/6NCrl', 'c286', datetime.date(2023, 5, 2), 26.75, 'normal', 'right C7 rib rudiment', 337.0369166431578, 'normal', 1.9215249221782407e-05, 'normal', 1.011446083578991, 0.9839780332942502, 0.9736329552516776], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.91, 'normal', None, 583.704299374089, 'normal', 0.0017678029284039, 'normal', 1.0127685495575056, 0.9944311600638224, 0.9589516266124668], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.51, 'normal', 'kyphosis', 548.2021401167909, 'normal', 0.0035740363552515, 'normal', 1.0219699422265542, 1.0004953356509223, 0.9571217361118456], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.57, 'normal', None, 466.213128708097, 'normal', 0.022693209330925, 'normal', 1.023169625105005, 0.9855403202485696, 0.9614940373976024], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.06, 'normal', 'T1 not fused, kyphosis', 517.2222798947708, 'normal', 0.0002690134891049, 'normal', 1.0052307589840208, 0.9759261786063806, 0.956245616844538], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.11, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 785.1960938954032, 'normal', 0.0015564351869643, 'normal', 1.0198229135270758, 1.0067981828427404, 0.9675349434828464], ['female', 'C57Bl/6NCrl', 'c286', datetime.date(2023, 5, 2), 27.61, 'normal', 'T1 not fused', 452.7551539939537, 'normal', 0.0029399331309327, 'normal', 1.011730279302316, 0.9833603430071168, 0.9586093828383964], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.74, 'normal', None, 377.6831286843391, 'normal', 0.0001921524922178, 'normal', 1.0094757905172969, 1.0069363116288932, 0.978886974863982], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 27.06, 'normal', 'pectus excavatum, kyphosis, tendon ossification', 493.0434048462852, 'normal', 0.0064563237385188, 'normal', 1.0174772166746826, 0.9958733695029962, 0.982741519414576], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.4, 'abnormal', 'T1 not fused, cranial sutures open', 577.8300761972994, 'normal', 0.0083586334114753, 'normal', 1.0177685890992625, 0.994011074490306, 0.9509955850674688], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.24, 'normal', 'T1 not fused', 469.1533046683715, 'normal', 0.0221743976019368, 'normal', 1.0167907790676756, 1.0086472167489435, 0.972540021207405], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.45, 'abnormal', 'T1 not fused, Processus spinosus missing, shape of skull abnormal (esp. ossi parietale + frontale, skull rounded) + cranial sutures open severe', 11098.373552537882, 'abnormal', 0.8838630337035471, 'abnormal', 1.266050412674859, 1.0969888599539626, 0.8337098163191952], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.42, 'normal', 'T1 not fused, kyphosis', 527.7907859208382, 'normal', 0.0, 'normal', 1.0283192298180164, 1.0059329849193088, 0.9801257113039288], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.18, 'abnormal', 'cranial sutures open severe', 447.5076706223536, 'normal', 0.0, 'normal', 1.026660915841305, 0.9994566972871936, 0.962768028755796], ['male', 'C57Bl/6NCrl', 'c286', datetime.date(2023, 5, 2), 26.42, 'normal', 'T1 not fused, pectus excavatum', 308.6017326152735, 'normal', 0.0004803812305445, 'normal', 0.9845085174703724, 0.982373054666744, 0.9622764779836748], ['female', 'C57Bl/6NCrl', 'c286', datetime.date(2023, 5, 2), 26.11, 'normal', None, 446.0821402498071, 'normal', 0.0015756504361861, 'normal', 1.0057180597959918, 0.9788633706301774, 0.9551219123158984], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.43, 'normal', None, 489.267206852288, 'normal', 0.0027669958879366, 'normal', 1.0003665934311965, 0.9883181178174044, 0.9488964750333228], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.71, 'normal', 'pectus excavatum', 448.1859560595442, 'normal', 0.0159294416048576, 'normal', 1.017225003274686, 0.9748952531747358, 0.9573887335172572], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.91, 'abnormal', 'cranial sutures open', 494.27297376029406, 'normal', 0.0, 'normal', 1.0056934693840187, 0.990657048305458, 0.9546532270801108], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 25.87, 'normal', None, 570.4938621091467, 'normal', 0.022251258598824, 'normal', 1.030790112298403, 1.0070756896807522, 0.9848884131311024], ['female', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.46, 'abnormal', 'T1 not fused, cranial sutures open severe', 608.1183649661508, 'normal', 0.0033626686138119, 'normal', 0.9936777447469558, 0.982948519779926, 0.956872901928731], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 26.29, 'normal', 'T1 not fused', 607.8695228444307, 'normal', 0.0089927366357941, 'normal', 0.9938779441323644, 0.9760845890434235, 0.9430143116337824], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.92, 'abnormal', 'T1 not fused, cranial sutures open', 664.7835234576224, 'normal', 0.0140463471811229, 'normal', 1.0204077946353394, 1.007507142320014, 0.9768245549386873], ['male', 'Adgrf1', 'c286', datetime.date(2023, 5, 2), 26.69, 'normal', 'T1 not fused, right C7 rib rudiment, kyphosis, sternum malformed', 407.023104631384, 'normal', 0.0, 'normal', 1.002227529378141, 0.9998860038571998, 0.9878256109375464], ['male', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.3, 'normal', 'T1 not fused', 354.2565004153713, 'normal', 0.0, 'normal', 1.028207859308288, 0.9951191715018616, 0.9731818640637384], ['male', 'C57Bl/6NCrl', 'c286', datetime.date(2023, 5, 2), 26.2, 'normal', 'kyphosis mild', 554.2873764264419, 'normal', 0.0031320856231505, 'normal', 1.0025780234554544, 0.9667712403612352, 0.951551799707501], ['female', 'Klk10', 'c286', datetime.date(2023, 5, 2), 27.0, 'normal', 'T1 not fused', 503.75244626182246, 'normal', 0.0040352023365743, 'normal', 1.0282621780271617, 0.9922637337244784, 0.9820128490437564]]
[['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 26.03, 'abnormal', 'T1 not fused, cranial sutures open', 467.3461282471264, 'normal', 0.0073786557011644, 'normal', 1.019966392884112, 0.9899925733416756, 0.976696026933186], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 27.15, 'normal', 'pectus excavatum mild', 440.3750068301801, 'normal', 0.000172937242996, 'normal', 1.023924162479418, 1.0135399962255671, 0.9895928578836942], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 26.76, 'normal', 'scoliotic mild', 499.491953580382, 'normal', 0.0001921524922178, 'normal', 1.0199303664136807, 1.0020118981279815, 0.9692296896174576], ['male', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 26.3, 'normal', None, 841.7234259184282, 'normal', 0.0750931939587256, 'normal', 1.0236456663777025, 0.9791265851000972, 0.9666033610704492], ['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 25.95, 'abnormal', 'T1 not fused, left C7 rib rudiment, LH II. Osteoneogenesis, cranial sutures open, L6 = half S0', 494.7868410523815, 'normal', 0.002382690903501, 'normal', 1.00044149184887, 0.9766858176018022, 0.9579824433547696], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 26.72, 'normal', 'T1 not fused', 579.1877196727911, 'normal', 0.0033818838630337, 'normal', 1.0241890888205092, 1.0001403102293756, 0.970913215772189], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 24.18, 'abnormal', 'cranial sutures open', 1112.4823449540984, 'abnormal', 0.04150493831905, 'normal', 0.9613781154678948, 0.936532324454966, 0.8929539985012118], ['female', 'Gpatch4', 'c278', datetime.date(2023, 2, 20), 24.19, 'abnormal', '3rd + 4th cervical vertebrae fused, 14th thoracic rib, 7 lumbar vertebrae, sternum crooked, rostrum malformation', 2938.0136011306954, 'abnormal', 0.3317320625648515, 'abnormal', 1.0252002055872609, 0.9520928572208056, 0.9026355880925194], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 25.98, 'abnormal', 'T1 not fused, cranial sutures open mild', 824.0308961116226, 'normal', 0.0202913031782022, 'normal', 0.975168138744708, 0.9407726590056196, 0.9278579257581756], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 25.22, 'abnormal', 'T1 not fused, C5+C6 fused, scoliotic mild, cranial sutures open severe', 817.6778561335041, 'normal', 0.0086852926482456, 'normal', 0.9689688679421498, 0.953551821737938, 0.8812460600128843], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 25.98, 'normal', 'T1 not fused, L6 process abnormal', 546.7496258196222, 'normal', 0.0012682064486376, 'normal', 1.003449336056408, 0.9801598687770569, 0.934872488903258], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 26.62, 'normal', 'scoliotic mild', 506.600820822446, 'normal', 0.0001537219937742, 'normal', 1.0065079985333183, 0.9910790083334756, 0.975026116543143], ['male', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 27.17, 'normal', 'T1 not fused', 581.2968521952571, 'normal', 0.0142192844241189, 'normal', 1.019696581956315, 1.0029478141997494, 0.9898182564192736], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 26.23, 'normal', None, 485.0486226061624, 'normal', 9.607624610891204e-05, 'normal', 1.003928215335774, 0.9929182368608036, 0.9870767524332502], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 26.06, 'normal', 'scoliotic, T1 not fused', 446.91286601173744, 'normal', 0.0, 'normal', 1.0074466483494615, 1.0033002146409724, 0.9653886745629554], ['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 27.3, 'normal', None, 723.5495409095302, 'normal', 0.0296875600476538, 'normal', 1.0178850653370748, 0.9828729231675498, 0.9546121007351394], ['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 26.34, 'normal', 'T1-T2 transposed', 679.7724582796844, 'normal', 0.0268629184120518, 'normal', 1.001658713652218, 0.96947665849483, 0.949593806141875], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 26.67, 'abnormal', 'T1 not fused, cranial sutures open', 675.3404160198795, 'normal', 0.0012105607009722, 'normal', 1.0068095545019862, 0.9974417048750188, 0.955813588376966], ['female', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 25.76, 'abnormal', 'cranial sutures open', 761.0332850217404, 'normal', 0.0350293993313093, 'normal', 0.9913153297969856, 0.9741883372690396, 0.9172236973790198], ['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 26.47, 'normal', 'T1 not fused', 351.47901186860975, 'normal', 0.0002497982398831, 'normal', 1.0174431848524863, 1.0070518622422848, 0.9827336246382988], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 26.75, 'abnormal', 'T1-T2 transposed, cranial sutures open', 472.6653118060825, 'normal', 0.0024595519003881, 'normal', 1.0017013891505784, 0.9815589027076383, 0.9472162068581672], ['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 27.52, 'normal', 'scoliotic, pectus excavatum severe', 347.22535314435544, 'normal', 0.0027285653894931, 'normal', 1.0282872925747917, 0.9989463431757932, 0.9628529301709764], ['male', 'C57Bl/6NCrl', 'c278', datetime.date(2023, 2, 20), 27.14, 'abnormal', 'T1 not fused, cranial sutures open + rostrum malformation', 2014.0861970680828, 'abnormal', 0.322758541178279, 'abnormal', 1.031538074133699, 1.0029055666763014, 0.9768137254915098], ['female', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 24.97, 'abnormal', 'L6 = half S0, cranial sutures open', 809.914944619159, 'normal', 0.0177164597824833, 'normal', 0.9618036253147472, 0.926124414734867, 0.8920283916746427], ['female', 'Vsx1', 'c278', datetime.date(2023, 2, 20), 26.81, 'normal', 'T1 not fused, kyphosis', 431.3287086088652, 'normal', 0.0002497982398831, 'normal', 1.0123084045631798, 1.0028767002522558, 0.9744342622763522], ['male', 'Wdr27', 'c278', datetime.date(2023, 2, 20), 26.18, 'normal', None, 387.2746758342186, 'normal', 0.0014603589408554, 'normal', 1.0549100966193985, 0.9943388913363308, 0.9794349903880096], ['male', 'Gpatch4', 'c278', datetime.date(2023, 2, 20), 25.75, 'normal', 'pectus excavatum', 468.1229692486399, 'normal', 0.0102609430844318, 'normal', 1.010702999924219, 0.9896820983045944, 0.9595483350868296]]

[['female', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 25.31, 'normal', 'T1+T2 not fused, PS missing, kyphosis', 1362.0791165315486, 'abnormal', 0.1490719034625879, 'abnormal', 1.044809019207503, 0.9877219934494312, 0.9057361917343112], ['female', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.85, 'normal', None, 447.0096848326786, 'normal', 0.0039006955920218, 'normal', 1.0280853517480963, 0.9912856083125596, 0.9596307286520904], ['male', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.82, 'normal', 'T1 not fused, kyphosis', 647.319838721114, 'normal', 0.0105107413243149, 'normal', 0.9968362559892524, 0.9911131921886704, 0.957182872808558], ['female', 'Hcls1', 'c258', datetime.date(2022, 10, 3), 25.88, 'normal', None, 503.2157952556445, 'normal', 0.0014603589408554, 'normal', 0.982923003535266, 0.9732965592401526, 0.9467863218525108], ['male', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.55, 'normal', 'pectus excavatum', 582.3138373067402, 'normal', 0.0022289689097267, 'normal', 1.0047906431956473, 0.9746840199457052, 0.9537887511782815], ['male', 'Klhl6', 'c258', datetime.date(2022, 10, 3), 27.06, 'normal', 'C7 left rib, kyphosis', 679.7028595904806, 'normal', 0.0040928480842396, 'normal', 1.005394653915008, 1.0000768352717155, 0.97697213598338], ['female', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.8, 'normal', None, 282.7564185720332, 'normal', 0.0, 'normal', 0.9912821148613064, 0.9790364503817824, 0.9571885219625402], ['female', 'C57Bl/6NCrl', 'c258', datetime.date(2022, 10, 4), 27.31, 'abnormal', 'cranial sutures open', 2370.997255544689, 'abnormal', 0.6547788324814573, 'abnormal', 1.0228307580426876, 0.9805244043738692, 0.8729505385827406], ['female', 'Amelx', 'c258', datetime.date(2022, 10, 4), 25.71, 'normal', 'T1-T2 transposed, left costal cartilage doubled, C7 processes abnormal, blunt lower incisors', 10886.467910974849, 'abnormal', 0.140405826063564, 'abnormal', 1.0368021762600728, 0.9716037927764462, 0.8911338017312741], ['male', 'Slc15a1', 'c258', datetime.date(2022, 10, 3), 27.06, 'normal', 'T1 not fused', 326.3699206314302, 'normal', 0.0, 'normal', 1.0382197349497038, 1.022220791575363, 0.9879246545816986], ['female', 'Amelx', 'c258', datetime.date(2022, 10, 4), 25.55, 'abnormal', 'scoliotic, T1 not fused, LHI.-broken phalang, cranial sutures open', 10170.857691379448, 'abnormal', 0.1371584489450828, 'abnormal', 1.0284516465782725, 0.952342987850087, 0.8989414800018332], ['male', 'Hcls1', 'c258', datetime.date(2022, 10, 3), 26.71, 'normal', None, 590.8500621900441, 'normal', 0.0053610545328772, 'normal', 1.015189375340776, 0.9905696708332116, 0.9512550157654416], ['male', 'C57Bl/6NCrl', 'c258', datetime.date(2022, 10, 3), 26.46, 'normal', None, 265.6720214930199, 'normal', 0.0, 'normal', 1.0081577374215007, 0.9896824271346758, 0.978498440354961], ['male', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.53, 'normal', 'T1-T2 transposed, T1 not fused, pectus excavatum mild', 696.2969928504368, 'normal', 0.0470389300949233, 'normal', 1.0343722941955116, 1.0041010414443052, 0.95153416665791], ['male', 'Xrcc5', 'c258', datetime.date(2022, 10, 3), 21.91, 'abnormal', 'scoliotic, PS missing, 24-25th caudal vertebrae malformed, zygomatic arch deformed, cranial sutures open', 2541.306600737004, 'abnormal', 0.4876830252488375, 'abnormal', 0.8477137323014139, 0.8071583889743579, 0.793587338676637], ['female', 'C57Bl/6NCrl', 'c258', datetime.date(2022, 10, 4), 25.76, 'abnormal', 'scoliotic, cranial sutures open', 1487.7989057331954, 'abnormal', 0.0175819530379309, 'normal', 1.0443696084344098, 0.9746212484842588, 0.9522288170449086], ['female', 'Amelx', 'c258', datetime.date(2022, 10, 4), 25.47, 'abnormal', 'T1-T2 transposed, right C7 rib, C7 processes abnormal, sternum malformed, blunt incisors, cranial sutures open', 1160.862369907617, 'abnormal', 0.0123746204988278, 'normal', 0.9884308511615274, 0.9691139924866028, 0.9417030606202568], ['male', 'Ate1', 'c258', datetime.date(2022, 10, 3), 27.38, 'normal', None, 448.104325090464, 'normal', 0.0042273548287921, 'normal', 1.001159688808128, 0.982338009221457, 0.9729365245104716], ['male', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.99, 'normal', 'T1 not fused + PS missing', 576.4986330774865, 'normal', 0.0099342838476615, 'normal', 1.0120668446685563, 0.9768908007475527, 0.9318906609317016], ['male', 'C57Bl/6NCrl', 'c258', datetime.date(2022, 10, 3), 26.97, 'normal', 'pectus excavatum', 640.829466748296, 'normal', 0.0001152914953306, 'normal', 1.007030164998771, 0.9877972090207644, 0.9668660650074906], ['male', 'Ate1', 'c258', datetime.date(2022, 10, 3), 27.41, 'normal', 'T1 not fused', 272.1473468010983, 'normal', 0.0, 'normal', 1.0463609968993677, 1.0173796303180764, 0.9968788012669788], ['male', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.9, 'normal', None, 369.7023383619164, 'normal', 0.0, 'normal', 1.0248621058690397, 0.9951495523328378, 0.9744968116193652], ['female', 'C57Bl/6NCrl', 'c258', datetime.date(2022, 10, 4), 25.32, 'normal', None, 8087.445478322681, 'abnormal', 0.1082971446139656, 'abnormal', 1.0170418337425815, 0.9665124526421351, 0.8937168829721454], ['male', 'Xrcc5', 'c258', datetime.date(2022, 10, 3), 23.45, 'abnormal', 'scoliotic, T1 not fused, PS missing, 23-24th caudal vertebrae malformed, zygomatic arch deformed, cranial sutures open', 1773.8925741443609, 'abnormal', 0.2191307021252065, 'abnormal', 0.8641957298903975, 0.8519475264237514, 0.824505696951168], ['male', 'Xrcc5', 'c258', datetime.date(2022, 10, 3), 22.17, 'abnormal', 'C5+6 fused, T1 not fused, PS missing, kyphosis, zygomatic arch deformed, cranial sutures open, shorter rostrum', 10819.52705649484, 'abnormal', 0.9871449982706276, 'abnormal', 1.1539865936416671, 1.1299437838530184, 0.856796378269118], ['female', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.56, 'normal', None, 316.81606938392525, 'normal', 0.0, 'normal', 1.000596421363954, 0.9948158188910592, 0.979596537781942], ['female', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.65, 'normal', None, 481.4060509055248, 'normal', 0.000172937242996, 'normal', 1.0086841355006655, 0.995882096514202, 0.9586213987117088], ['male', 'C57Bl/6NCrl', 'c258', datetime.date(2022, 10, 3), 26.07, 'normal', None, 512.1979120057123, 'normal', 0.0068790592213981, 'normal', 0.992787264596888, 0.9737587623285014, 0.945486777704783], ['male', 'Slc15a1', 'c258', datetime.date(2022, 10, 3), 26.65, 'abnormal', 'cranial sutures open mild', 652.3882937102609, 'normal', 0.0088197993927981, 'normal', 1.022403202896507, 0.9916228950188662, 0.9448130119475262], ['female', 'Amelx', 'c258', datetime.date(2022, 10, 4), 26.12, 'normal', None, 9661.263685616346, 'abnormal', 0.1525498635717305, 'abnormal', 1.0179379929418708, 0.972531579820163, 0.894226711303589], ['female', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.42, 'normal', None, 526.3374343041785, 'normal', 0.0025940586449406, 'normal', 0.9868265747837492, 0.9790166439328818, 0.9401467088742446], ['female', 'Hcls1', 'c258', datetime.date(2022, 10, 3), 26.61, 'normal', None, 436.90439243778417, 'normal', 0.0007493947196495, 'normal', 1.004805668060387, 0.9885816211937172, 0.952617368691298], ['female', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.7, 'normal', None, 696.2572248247111, 'normal', 0.0036508973521386, 'normal', 1.0082866093749736, 0.9922757597357648, 0.9266115509611166], ['female', 'Xrcc5', 'c258', datetime.date(2022, 10, 3), 21.83, 'abnormal', 'C7 not fused, T1-T2 transposed, 27th caudal vertebra malformed, cranial sutures open, zygomatic arch deformed', 3735.4334412764015, 'abnormal', 0.9865108950463088, 'abnormal', 1.3020777264192824, 1.1200497118038446, 0.9914590732193757], ['male', 'Ate1', 'c258', datetime.date(2022, 10, 3), 25.89, 'abnormal', 'shorter rostrum + mildly crooked', 2198.6194603010267, 'abnormal', 0.2897467430152569, 'abnormal', 1.0301120711471243, 1.0006842622336412, 0.9363795878297532], ['male', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 27.31, 'normal', 'T1 not fused, right costal cartilage doubled+pectus excavatum severe', 481.5461268162513, 'normal', 0.0005572422274316, 'normal', 1.010918559272928, 0.9839116700264132, 0.960593337412586], ['female', 'Xrcc5', 'c258', datetime.date(2022, 10, 3), 21.52, 'abnormal', 'T1 not fused, PS missing, 24th caudal vertebra malformed, kyphosis, shorter rostrum, cranial sutures open, zygomatic arch deformed', 3861.3226404904863, 'abnormal', 0.97261826985896, 'abnormal', 1.3221702018733763, 1.1175057248710427, 0.9988323546533354], ['male', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 26.49, 'normal', None, 450.8050389561554, 'normal', 0.0034587448599208, 'normal', 1.016158614196495, 0.9889910023553194, 0.974218703587154], ['female', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.53, 'normal', None, 686.0253021721921, 'normal', 0.0132969524614734, 'normal', 1.0115758502796668, 0.9959569252949004, 0.971706805099466], ['female', 'Amelx', 'c258', datetime.date(2022, 10, 4), 27.64, 'normal', 'T1-T2 transposed, blunt incisors', 2010.80616263888, 'abnormal', 0.0285538603435686, 'normal', 1.036504383402009, 0.9687938309655924, 0.9479658832124528], ['female', 'Klhl6', 'c258', datetime.date(2022, 10, 3), 26.48, 'normal', None, 601.7016082370544, 'normal', 0.0204258099227547, 'normal', 1.022897884303209, 0.998442100599546, 0.9551631541958788], ['female', 'Amelx', 'c258', datetime.date(2022, 10, 4), 25.65, 'normal', 'T1-T2 transposed, right C7 rib, sternum malformed, blunt incisors', 2206.8421889022075, 'abnormal', 0.0540332808116521, 'normal', 1.0176386313737424, 0.973529226519063, 0.9341294138298568], ['male', 'Ate1', 'c258', datetime.date(2022, 10, 3), 27.32, 'normal', None, 411.48455106396585, 'normal', 7.686099688712963e-05, 'normal', 1.0169160600935083, 0.99478586449342, 0.9575825271825246], ['female', 'Ate1', 'c258', datetime.date(2022, 10, 3), 26.44, 'normal', None, 426.8891096761094, 'normal', 0.0, 'normal', 1.0253589119270043, 1.0157469171080027, 0.962915220601824], ['female', 'Vnn3', 'c258', datetime.date(2022, 10, 3), 27.0, 'abnormal', 'cranial sutures open mild', 302.1837685884535, 'normal', 0.0, 'normal', 1.0181485799284178, 0.9997828292943356, 0.979146791583534]]
[['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.39, 'normal', 'T1 not fused, scoliotic', 397.4023092719572, 'normal', 0.0025171976480534, 'normal', 1.0317571965001189, 0.9824677090473872, 0.9633397990645566], ['female', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.49, 'normal', None, 520.0099626187781, 'normal', 0.0, 'normal', 0.9956429446434872, 0.989167814336666, 0.9513018196212436], ['female', 'Crocc2', 'c261', datetime.date(2022, 10, 24), 26.68, 'normal', 'T1 not fused; CA22+', 622.5424896465254, 'normal', 0.0185811459974635, 'normal', 1.017225982457135, 0.9829235815918024, 0.9565315459387486], ['male', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 26.88, 'normal', None, 482.0204349348872, 'normal', 0.0179662580223665, 'normal', 1.0500786522104142, 1.0042209681273977, 0.9876647671728436], ['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 27.1, 'normal', None, 621.9704459429868, 'normal', 0.0147957419007724, 'normal', 1.0238814952031852, 0.985249803064026, 0.96183827486016], ['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 25.73, 'normal', 'kyphosis', 742.3506543421498, 'normal', 0.071173283117482, 'normal', 1.021106444714902, 0.9806754209319676, 0.964192103924368], ['male', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 26.47, 'normal', 'T1 not fused', 537.7838818953061, 'normal', 0.0033242381153683, 'normal', 1.0058685613411085, 0.9731633546721744, 0.9508984892658604], ['female', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 27.05, 'normal', 'T1 not fused', 523.779093125108, 'normal', 0.0025940586449406, 'normal', 1.0182347185439773, 0.998989664982791, 0.974315063097596], ['male', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 27.21, 'normal', None, 516.9108325136049, 'normal', 0.0609507705314937, 'normal', 1.0416477315568935, 0.9958933341129164, 0.9598000149134976], ['female', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 27.02, 'normal', None, 351.9956030280457, 'normal', 0.0001345067445524, 'normal', 1.0383208775338115, 1.0096730453709035, 0.987744718456789], ['female', 'Nxnl2', 'c261', datetime.date(2022, 10, 24), 26.71, 'normal', None, 469.3524120106783, 'normal', 0.0059567272587525, 'normal', 1.0435401297628046, 0.9847346568137576, 0.974696426131671], ['female', 'Nxnl2', 'c261', datetime.date(2022, 10, 24), 27.08, 'normal', None, 575.1209035428765, 'normal', 0.0020368164175089, 'normal', 1.0253294953962502, 1.0192259416304092, 1.0020984937363535], ['female', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.27, 'normal', 'T1 not fused', 563.2334706662847, 'normal', 0.962549479266746, 'abnormal', 1.1651856657253878, 0.9843707991147946, 0.8689779346082711], ['female', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.64, 'normal', 'T1 not fused', 375.210853478678, 'normal', 0.0, 'normal', 0.998394668208382, 0.9828908019849526, 0.9604809442306644], ['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.91, 'normal', None, 323.37585667545864, 'normal', 0.0008646862149802, 'normal', 1.0229237692254545, 1.0025610164879957, 0.9858211751681648], ['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.98, 'normal', None, 439.8346530463602, 'normal', 0.0033818838630337, 'normal', 1.00759182285302, 0.9890026890862976, 0.9572160466024529], ['male', 'Nxnl2', 'c261', datetime.date(2022, 10, 24), 26.64, 'normal', None, 352.0859368034007, 'normal', 9.607624610891204e-05, 'normal', 1.0164843452456116, 1.0047624771501051, 0.993066231775055], ['female', 'Impact', 'c261', datetime.date(2022, 10, 24), 26.74, 'normal', 'T1 not fused', 351.44450804459177, 'normal', 0.0, 'normal', 1.0028997371124686, 1.0002905713746315, 0.9719183726076548], ['female', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 26.59, 'normal', 'T1 not fused', 564.8806405475233, 'normal', 0.0024019061527228, 'normal', 1.012131276747023, 0.9826927360754788, 0.9573853703017694], ['male', 'Nxnl2', 'c261', datetime.date(2022, 10, 24), 27.72, 'normal', 'kyphosis', 562.1950731885087, 'normal', 0.0044002920717881, 'normal', 1.0307001034640872, 0.9863022418527824, 0.9606185575796456], ['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.71, 'normal', 'T1 not fused, pectus excavatum', 287.68308676823773, 'normal', 0.0, 'normal', 1.0045463756877928, 0.9836776799226328, 0.9753060556239358], ['male', 'C57Bl/6NCrl', 'c261', datetime.date(2022, 10, 24), 26.54, 'normal', 'pectus excavatum, kyphosis', 425.5810242629079, 'normal', 0.0008839014642019, 'normal', 1.0058008453347225, 0.986123543057936, 0.955720330417345], ['female', 'Crocc2', 'c261', datetime.date(2022, 10, 24), 25.92, 'normal', 'pectus excavatum', 952.2811236045924, 'normal', 0.0457130778986203, 'normal', 0.9884546913391348, 0.9762570791757966, 0.9361431966701872], ['female', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 26.29, 'normal', 'T1 not fused', 362.5208859779638, 'normal', 0.0019215249221782, 'normal', 0.9931940423314196, 0.9794241154133632, 0.9546537737951056], ['male', 'Ccdc110', 'c261', datetime.date(2022, 10, 24), 26.62, 'normal', None, 303.16559092782785, 'normal', 0.0001537219937742, 'normal', 1.01661250631865, 0.9764638801103748, 0.970195059400956]]

[['male', 'Sord', 'c271', datetime.date(2023, 1, 2), 26.22, 'normal', None, 489.5241096078377, 'normal', 0.0013450674455247, 'normal', 1.0210691471421127, 0.979607087646954, 0.9606712166134465], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.36, 'abnormal', 'RH II. Osteoneogenesis, cranial sutures open mild', 417.1852585538933, 'normal', 0.0009991929595326, 'normal', 0.9943164173956432, 0.974436002195221, 0.9469176449897944], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.49, 'normal', None, 387.0960012078105, 'normal', 0.0003843049844356, 'normal', 1.019586581154356, 0.9969020805252324, 0.976484205536765], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.06, 'normal', 'pectus excavatum', 563.2532040898429, 'normal', 0.0019023096729564, 'normal', 1.0040784086964882, 0.9699097578390916, 0.9567341286101374], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.45, 'normal', 'scoliotic, T1 not fused, left C7 rib', 399.9788554637264, 'normal', 0.0, 'normal', 1.0136247328191548, 0.998096943928968, 0.983219683498308], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.58, 'normal', 'T1-T2 transposed', 595.8979701416632, 'normal', 0.0022673994081703, 'normal', 1.0264307992187875, 0.9880913989738624, 0.9575068406194666], ['female', 'Sord', 'c271', datetime.date(2023, 1, 2), 27.1, 'abnormal', 'cranial sutures open', 403.3371646311487, 'normal', 0.9133007955113178, 'abnormal', 1.279368688406945, 1.147493331748927, 0.8679171561288245], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.22, 'abnormal', 'cranial sutures open mild', 383.7956165360762, 'normal', 0.0003266592367703, 'normal', 0.9857681647748318, 0.9782880639657876, 0.9526588344778744], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.28, 'normal', 'LH II. Osteoneogenesis', 572.1740659643726, 'normal', 0.0118365935206179, 'normal', 1.0242766777968348, 0.9907053879546028, 0.9789937589541168], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.75, 'normal', 'tendon ossification', 326.1047212396153, 'normal', 0.0007301794704277, 'normal', 1.036722485231409, 1.011252678610643, 0.989585341766606], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 25.99, 'normal', None, 465.3647230540708, 'normal', 0.0, 'normal', 0.9983621845984028, 0.9873352993702986, 0.957909716306933], ['female', 'Sord', 'c271', datetime.date(2023, 1, 2), 26.51, 'normal', 'RF paw missing digit', 680.2838241595009, 'normal', 0.0087429383959109, 'normal', 1.0204560381388474, 0.9881458727743564, 0.9526440519508604], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.62, 'normal', 'T1 not fused', 694.9347346495717, 'normal', 0.0098958533492179, 'normal', 1.021281948726335, 0.9836645307834015, 0.968013674850145], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 25.96, 'abnormal', 'T1 not fused, cranial sutures open', 552.431393978182, 'normal', 0.0389493101725529, 'normal', 1.0373163125821347, 0.9792442295058488, 0.9458988178517814], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 25.74, 'abnormal', 'cranial sutures open', 404.78759041432, 'normal', 0.000172937242996, 'normal', 0.9786842764616565, 0.95661892090935, 0.951034139513204], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.46, 'normal', 'cervical vertebrae 4+5 fused together, pectus excavatum', 386.568631498001, 'normal', 0.0, 'normal', 1.0121663467718258, 0.9989503014701004, 0.953423681101012], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 27.65, 'normal', 'T1 not fused, L6=half S0', 599.1115976850836, 'normal', 0.0205026709196418, 'normal', 1.031678562832751, 0.9911891835256224, 0.966259621315412], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.96, 'abnormal', 'cranial sutures open', 594.2530888038384, 'normal', 0.0011144844548633, 'normal', 1.037491938193698, 1.017020759711286, 0.9903233552927994], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 27.18, 'normal', 'T1 not fused, LH II. Osteoneogenesis', 508.1384497576754, 'normal', 0.0005188117289881, 'normal', 1.0277826214596937, 0.995318180877928, 0.9765096769031444], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.12, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open mild', 690.6877881180974, 'normal', 0.0057453595173129, 'normal', 1.0348808503608042, 0.983806218452184, 0.9592273301315124], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.54, 'normal', 'cranial sutures open mild', 655.3762274484199, 'normal', 0.0102993735828753, 'normal', 0.9943621752419554, 0.983115261359506, 0.9500560400886452], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.18, 'normal', 'T1 not fused, pectus excavatum', 556.1039125615733, 'normal', 0.0019215249221782, 'normal', 0.9896955320609516, 0.984742229966074, 0.967576492899273], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.26, 'normal', 'T1-T2 transposed', 555.5625298906176, 'normal', 0.0312055647361746, 'normal', 1.051232736836588, 1.002022345661686, 0.9730787743429616], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.07, 'normal', None, 468.72361970628265, 'normal', 0.0, 'normal', 1.003337317994622, 0.9842076126870356, 0.9577489696481088], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.55, 'normal', 'T1 not fused', 688.2544424921986, 'normal', 0.0683678567311018, 'normal', 1.0151112620321097, 0.9900285355794824, 0.9802309150241496], ['female', 'Sord', 'c271', datetime.date(2023, 1, 2), 26.39, 'abnormal', 'move, cranial sutures open', 504.0511838034624, 'normal', 0.0024595519003881, 'normal', 1.0021737435526594, 0.9897474121887152, 0.9738401854021456], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.64, 'normal', 'pectus excavatum', 436.2267060394056, 'normal', 0.0044195073210099, 'normal', 1.0042987079534067, 0.9901871501518908, 0.9799294124955822], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 27.16, 'normal', None, 335.52736123748934, 'normal', 0.0044771530686753, 'normal', 1.022366169538217, 0.9931719835793682, 0.9747812058508168], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.99, 'abnormal', 'cranial sutures open', 556.3917300421497, 'normal', 0.0012682064486376, 'normal', 1.03135668300056, 0.9886680698777742, 0.9622733990117024], ['male', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 27.33, 'normal', None, 483.40781416058365, 'normal', 0.0001537219937742, 'normal', 1.0584049357650898, 1.010361613343964, 1.0042080595915084], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.23, 'normal', 'LH II. Osteoneogenesis', 454.5658391862421, 'normal', 3.8430498443564814e-05, 'normal', 1.0152543046341838, 0.9842701239361143, 0.9553757444404336], ['female', 'C57Bl/6NCrl', 'c271', datetime.date(2023, 1, 2), 26.32, 'normal', None, 428.34201764326514, 'normal', 0.0029783636293762, 'normal', 1.0158801996826472, 0.9872321656645856, 0.9718072289820664], ['female', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 26.55, 'normal', None, 384.43211099103576, 'normal', 1.9215249221782407e-05, 'normal', 1.014066262510853, 1.0016836541237029, 0.9751655656683336], ['male', 'Il1r1', 'c271', datetime.date(2023, 1, 2), 27.81, 'normal', 'T1-T2 transposed', 724.7607404765307, 'normal', 0.0445601629453134, 'normal', 1.0232246534267038, 0.9937781876057676, 0.9775207605756498]]
[['female', 'Trpv4 tm1b', 'c300', datetime.date(2023, 8, 7), 25.29, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 522.6381085690931, 'normal', 0.004765381807002, 'normal', 0.9633833454998972, 0.9592857458270518, 0.9019328597348112], ['male', 'Pcid2', 'c300', datetime.date(2023, 8, 7), 27.9, 'normal', 'T1 not fused, Rhp I. Polydactyly', 479.55266919420393, 'normal', 0.0002690134891049, 'normal', 1.0236801336779229, 0.9978441481466932, 0.9911535786077902], ['male', 'Tcirg1', 'c300', datetime.date(2023, 8, 7), 26.25, 'normal', 'T1 not fused, L6 = half S0', 266.6303678425875, 'normal', 0.000614887975097, 'normal', 1.0197298366872634, 1.0028681220370927, 0.9742897745280824], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.32, 'normal', None, 364.1647445121886, 'normal', 0.0, 'normal', 1.009673159061607, 0.9899704357058612, 0.9803415405508616], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 25.97, 'abnormal', 'cranial sutures open', 1214.6571633280555, 'abnormal', 0.1786057415164674, 'abnormal', 0.9939079624909456, 0.9742029058090068, 0.928926263457485], ['male', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 26.02, 'normal', 'T1 not fused', 480.7779089942964, 'normal', 1.9215249221782407e-05, 'normal', 0.9933378611664548, 0.9794195222751092, 0.9458130687022062], ['male', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 26.86, 'normal', None, 484.3018185290104, 'normal', 0.0, 'normal', 1.00942744437876, 0.97730449072385, 0.957231075778303], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.08, 'abnormal', 'T1 not fused, cranial sutures open', 569.8974113734522, 'normal', 0.0007109642212059, 'normal', 1.0214707756755608, 1.0019773549139002, 0.970449478574035], ['female', 'Trpv4 tm1b', 'c300', datetime.date(2023, 8, 7), 26.38, 'normal', 'T1 not fused', nan, nan, nan, nan, nan, nan, nan], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.45, 'abnormal', 'T1 not fused, cranial sutures open', 845.5326154716447, 'normal', 0.033991775873333, 'normal', 1.0259857733437263, 0.9823137794840816, 0.9350814027970684], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.18, 'abnormal', 'cranial sutures open', 950.9445885940478, 'normal', 0.0342415741132162, 'normal', 1.0220970348281722, 1.0043106884810693, 0.9231430114078492], ['male', 'Dpp9', 'c300', datetime.date(2023, 8, 7), 27.55, 'normal', None, 627.1045417258377, 'normal', 0.0104338803274278, 'normal', 1.032082157841938, 1.0048355929050057, 0.9836156594023212], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.27, 'normal', 'T1 not fused, scoliotic, kyphosis, pectus excavatum', 762.7634778477421, 'normal', 0.0067445524768456, 'normal', 1.0089079299915036, 0.9804474970026424, 0.9510082922649348], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.52, 'normal', 'T1 not fused', 468.2421460316573, 'normal', 0.0178509665270358, 'normal', 1.0119056901790675, 0.9780488112010228, 0.9468020882867874], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.19, 'normal', None, 505.6551785510363, 'normal', 0.004054417585796, 'normal', 0.9883821474528476, 0.9755022143636036, 0.9533538485324424], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.82, 'abnormal', 'pectus excavatum, cranial sutures open', 495.9521430159679, 'normal', 0.0004995964797663, 'normal', 1.0292119170893088, 0.975587612968854, 0.9558933313989978], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.48, 'abnormal', 'L6 = S0, pectus excavatum, rostrum rounded + malformed', 1721.3026789095084, 'abnormal', 0.1826601591022635, 'abnormal', 1.0022376749864417, 0.9847542173186474, 0.9758020218708636], ['male', 'Pcid2', 'c300', datetime.date(2023, 8, 7), 26.72, 'normal', 'T1 not fused, pectus excavatum severe', 464.5573080863686, 'normal', 0.0004611659813227, 'normal', 1.008542868454971, 0.9995323119401236, 0.9616995681731324], ['male', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 26.08, 'normal', 'kyphosis', 689.1343214623585, 'normal', 0.0107221090657545, 'normal', 0.9810045560596776, 0.9707533186486716, 0.9123696509932994], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.21, 'normal', None, 490.80043205068574, 'normal', 0.0041697090811267, 'normal', 1.0089100774607966, 0.990102167062158, 0.9563934384353768], ['male', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 27.09, 'normal', 'pectus excavatum', 540.695482389791, 'normal', 0.0011913454517505, 'normal', 1.0178328765508744, 0.9946914975353766, 0.9736040339693324], ['female', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 26.84, 'abnormal', 'cranial sutures open', 728.8964914876797, 'normal', 0.0217708773682794, 'normal', 1.0029236331573197, 0.9686270063181276, 0.9175363903701614], ['female', 'Trpv4 tm1b', 'c300', datetime.date(2023, 8, 7), 23.59, 'abnormal', 'T1 not fused, kyphosis, rostrum malformation + cranial sutures open severe + microphthalmia', 7523.346407750551, 'abnormal', 0.7022020675608163, 'abnormal', 1.0300370004157111, 0.949435658808396, 0.896471254308499], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.93, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 657.8452687076848, 'normal', 0.0121632527573882, 'normal', 1.016883154870556, 0.9836043399417516, 0.9530919812319348], ['female', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 25.74, 'normal', None, 601.9923687887549, 'normal', 0.0004995964797663, 'normal', 0.9823527363033988, 0.9596685282082348, 0.907498049468668], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 27.79, 'normal', 'T1 not fused', 398.1802578825369, 'normal', 0.0007493947196495, 'normal', 1.0075653580224353, 0.9899053963051784, 0.9543318174702016], ['female', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 25.43, 'normal', 'scoliotic', 808.5402737474348, 'normal', 0.027285653894931, 'normal', 0.9994469454454836, 0.977011949721312, 0.9403009266710854], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 27.18, 'abnormal', 'cranial sutures open', 473.9549600957138, 'normal', 0.0, 'normal', 1.019471628795214, 0.966153410491884, 0.9511455527777926], ['female', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.08, 'abnormal', 'scoliotic, cranial sutures open', 502.7853182142593, 'normal', 0.0009031167134237, 'normal', 1.0005089042399975, 0.9753668349598008, 0.9542305301314712], ['female', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 25.27, 'abnormal', 'kyphosis, cranial sutures open', 817.6534220004105, 'normal', 0.0049191038007762, 'normal', 0.996047836990922, 0.9745125345124706, 0.9242123854147056], ['female', 'Gzmb', 'c300', datetime.date(2023, 8, 7), 25.51, 'normal', None, 1167.9753567890805, 'abnormal', 0.0053418392836555, 'normal', 0.9820684172880656, 0.96104900894971, 0.9234020001779976], ['female', 'Trpv4 tm1b', 'c300', datetime.date(2023, 8, 7), 26.65, 'normal', None, nan, nan, nan, nan, nan, nan, nan], ['male', 'C57Bl/6NCrl', 'c300', datetime.date(2023, 8, 7), 26.15, 'abnormal', 'scoliotic, pectus excavatum, cranial sutures open', 635.7166161478883, 'normal', 0.0166211905768417, 'normal', 0.9939307265255688, 0.9614533718559686, 0.9533837292924744]]

[['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.76, 'normal', 'scoliotic, pectus excavatum', 581.1855406718896, 'normal', 0.0052649782867683, 'normal', 1.0053649741955275, 0.9867475165193909, 0.9712973076333248], ['male', 'Uox', 'c265', datetime.date(2022, 11, 21), 27.39, 'normal', None, 339.2814610720428, 'normal', 0.0001152914953306, 'normal', 1.032409756999269, 0.9859018267832452, 0.9827843075620332], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.78, 'normal', '4 + 5 cervical vertebrae fused', 689.8958732083047, 'normal', 0.0571845816840244, 'normal', 1.035128452614971, 1.003656453377458, 0.9966080885933198], ['female', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 26.71, 'normal', '5 sacral vertebrae', 482.2923791539567, 'normal', 0.0041697090811267, 'normal', 0.9967393718237452, 0.9673597199881676, 0.9487189719593868], ['male', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 26.31, 'normal', '5 sacral vertebrae', 909.7330552350552, 'normal', 0.0365666192690519, 'normal', 1.0034267708403055, 0.9821084240472808, 0.9310424973758245], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.32, 'normal', None, 707.3429232633077, 'normal', 0.0305330310134122, 'normal', 1.0057544911490832, 0.9736004799647554, 0.9542608042127108], ['male', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 24.69, 'abnormal', '5 sacral vertebrae, rostrum malformation', 2358.781672299392, 'abnormal', 0.2919949271742054, 'abnormal', 1.0057262049756643, 0.9613398495545064, 0.928970647067864], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.59, 'normal', None, 491.5142639657938, 'normal', 0.0009031167134237, 'normal', 1.0195393302602025, 0.9898957429208808, 0.9736560661326058], ['male', 'Uox', 'c265', datetime.date(2022, 11, 21), 26.64, 'abnormal', 'T1 not fused, rostrum malformed, pectus excavatum', 1939.1656621759123, 'abnormal', 0.2217247607701472, 'abnormal', 1.0597820493366157, 0.9925472058964636, 0.9785734108379917], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.03, 'normal', 'PS missing, kyphosis, pectus excavatum mild, RH II. Osteoneogenesis', 620.8892479608365, 'normal', 0.0040736328350178, 'normal', 0.9920048854682688, 0.9761574296893686, 0.930324486418786], ['female', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 27.3, 'normal', 'scoliotic, T1 not fused, 5 sacral vertebrae (or 7 lumbar), S0 only one process fused to pelvis', 533.6337822463261, 'normal', 0.002382690903501, 'normal', 1.0029627714119815, 0.9878816985538272, 0.9666667490159424], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.91, 'normal', 'scoliotic', 543.9959100582104, 'normal', 0.0063602474924099, 'normal', 0.9852176200787244, 0.976340183660136, 0.948163845014044], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 25.77, 'normal', 'T1 not fused', 477.9327131512398, 'normal', 0.0, 'normal', 0.9806809130298983, 0.9586697422204582, 0.941360406390808], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.71, 'normal', None, 377.4887386021108, 'normal', 0.0013066369470812, 'normal', 1.0146465742846538, 1.0012589470309157, 0.9848127989506064], ['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.47, 'normal', None, 653.2043683074112, 'normal', 0.1055685792244725, 'abnormal', 1.041820775931641, 0.984470758829752, 0.964236676073485], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 27.48, 'normal', 'T1 not fused, tail tip deformed', 674.2810342708394, 'normal', 0.0140655624303447, 'normal', 1.043040589872311, 0.997696424020449, 0.9511944024780612], ['female', 'Dcaf5', 'c265', datetime.date(2022, 11, 21), 26.0, 'abnormal', 'T1 not fused, cranial sutures open', 873.539607175987, 'normal', 0.2269897390569155, 'abnormal', 0.9812338030749784, 0.9691688045649236, 0.9038946923286952], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.99, 'normal', None, 1079.6757148833933, 'abnormal', 0.0898697206102763, 'normal', 1.047237335373758, 0.9837107492517756, 0.9770358678345872], ['male', 'Uox', 'c265', datetime.date(2022, 11, 21), 26.73, 'normal', 'pectus excavatum severe', 442.4128556250821, 'normal', 0.0005188117289881, 'normal', 1.0213781870519207, 0.9774175020083318, 0.9473269331061352], ['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.74, 'abnormal', 'cranial sutures open', 595.2216238403494, 'normal', 0.002113677414396, 'normal', 1.0386133255082943, 1.0315056174945356, 0.992811607255883], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.57, 'normal', None, 497.3467911851885, 'normal', 0.0006725337227623, 'normal', 1.0095178075920035, 0.9736790183757532, 0.9685380533959266], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.71, 'normal', 'tendon ossification', 562.9224838717721, 'normal', 0.0056877137696475, 'normal', 0.9894512448899864, 0.9779621432972886, 0.9341226032736089], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.83, 'normal', None, 381.0455222233999, 'normal', 7.686099688712963e-05, 'normal', 1.0049842761967094, 0.9630622915902594, 0.9546069619436516], ['male', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 26.04, 'normal', '5 sacral vertebrae, kyphosis', 652.6847707559, 'normal', 0.0206948234118596, 'normal', 0.9822700668050948, 0.9760358237470416, 0.9392675612810428], ['female', 'Uox', 'c265', datetime.date(2022, 11, 21), 26.81, 'normal', None, 678.3489149724867, 'normal', 0.0110295530533031, 'normal', 1.0251635746769805, 0.990440544952032, 0.9711803659377176], ['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.17, 'normal', 'pectus excavatum', 497.933444483442, 'normal', 0.0103570193305407, 'normal', 1.0099995965908306, 0.9892947912710977, 0.9684861001429944], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.51, 'normal', 'T1 not fused', 635.2858728973299, 'normal', 0.0010760539564198, 'normal', 1.0091001569806997, 0.9844996817628964, 0.9610400929272608], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.89, 'normal', 'left C7 rib, tail move', 666.2969187129481, 'normal', 0.0016332961838515, 'normal', 1.0044845694602609, 0.9734186043826364, 0.961204340728259], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.63, 'normal', None, 537.2542741812605, 'normal', 0.0003843049844356, 'normal', 0.9956003122113766, 0.9708445937242332, 0.9492522618909948], ['male', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.92, 'normal', None, 460.4871450382663, 'normal', 0.0010952692056415, 'normal', 0.999092471180002, 0.9790386669598922, 0.9586948488506676], ['male', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 24.94, 'abnormal', '5 sacral vertebrae, 5 + 6 cervical vertebrae fused, RH I. polysyndactyly, rostrum malformation', 2628.218505924045, 'abnormal', 0.314284616271473, 'abnormal', 1.024950864591886, 1.0142085533493992, 0.9489045527115956], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 27.02, 'normal', None, 701.2911947040125, 'normal', 0.0456170016525114, 'normal', 1.040292684319278, 1.0155003099990023, 0.9973107024142396], ['male', 'Gpatch4', 'c265', datetime.date(2022, 11, 21), 26.65, 'normal', '5 sacral vertebrae, kyphosis', 601.2334098148277, 'normal', 0.0006917489719841, 'normal', 1.0113325338098078, 0.9850884918228532, 0.9628363698208936], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.59, 'normal', 'T1 not fused, PS small but present', 764.4404907729817, 'normal', 0.0073017947042773, 'normal', 0.9641342289191144, 0.9558560414044182, 0.940328508089021], ['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.77, 'normal', None, 867.5126945444603, 'normal', 0.0863917605011337, 'normal', 1.0554850012364616, 1.0438435235504009, 0.9879000617725544], ['male', 'Fam227b', 'c265', datetime.date(2022, 11, 21), 25.7, 'normal', None, 880.8846193142742, 'normal', 0.0570308596902501, 'normal', 1.0334980901499429, 1.0020217947985817, 0.9799624955978798], ['female', 'Dcaf5', 'c265', datetime.date(2022, 11, 21), 25.09, 'abnormal', 'LH II. Osteoneogenesis, cranial sutures open', 886.810422177606, 'normal', 0.0910802813112486, 'normal', 0.9613800304959452, 0.939889553627938, 0.8598758867673367], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.43, 'normal', 'RH I. polysyndatyly', 726.3963885014415, 'normal', 0.0047077360593366, 'normal', 0.9906287957401598, 0.9777405857386748, 0.9537937704725472], ['female', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.61, 'normal', None, 1001.4301581597032, 'abnormal', 0.0388724491756658, 'normal', 1.0413990340647117, 0.9912416878688964, 0.9508911531635008], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.99, 'normal', 'pectus excavatum severe', 388.0938276268464, 'normal', 0.0009415472118673, 'normal', 0.9926214434357848, 0.9685521622730204, 0.9441309700925842], ['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.37, 'normal', 'kyphosis', 681.3129672554825, 'normal', 0.0386802966834479, 'normal', 1.0296411925554985, 0.9911217781470936, 0.9691202008610184], ['female', 'C57Bl/6NCrl', 'c265', datetime.date(2022, 11, 21), 26.22, 'abnormal', 'T1 not fused', 412.3546990449881, 'normal', 0.0, 'normal', 1.001854229818753, 0.98620724294422, 0.9598375502101668], ['male', 'Fam227b', 'c265', datetime.date(2022, 11, 21), 25.91, 'normal', None, 702.391052651391, 'normal', 0.044944467929749, 'normal', 1.0126538673385812, 0.989025311242306, 0.9639089980528402], ['male', 'Fnip1', 'c265', datetime.date(2022, 11, 21), 26.9, 'normal', None, 335.8424131526924, 'normal', 0.0007686099688712, 'normal', 1.018394239733446, 0.9937656547767616, 0.9770318333000522]]
[['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 25.45, 'normal', 'cranial sutures open mild', 536.1761376022309, 'normal', 0.0034779601091426, 'normal', 0.9690202584474732, 0.9558893619406112, 0.929470173009356], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.31, 'normal', None, 447.7584715838464, 'normal', 0.0017293724299604, 'normal', 1.017950251725286, 0.9885246152344588, 0.9656261415558954], ['female', 'Cops8', 'c269', datetime.date(2022, 12, 19), 26.72, 'normal', 'T1 not fused, PS missing; 12 thoracic vertebrae + 12 thoracic costae + extra C7 left+right costae + extra L1 left costa (costae L: 12+1+1; R: 12+1); scoliotic mild, sternum crooked', 871.7554037674383, 'normal', 0.0376426732254717, 'normal', 0.9865795995253166, 0.9774040334051816, 0.9450431497978056], ['male', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 27.38, 'normal', None, 324.60602275449133, 'normal', 0.0003843049844356, 'normal', 1.0633294890963991, 1.0104997512162122, 0.9959357779028114], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.59, 'normal', 'T1 not fused', 474.1065722528989, 'normal', 0.000614887975097, 'normal', 0.9930574137486904, 0.9893515572453084, 0.9713457740510596], ['male', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 27.13, 'normal', None, 309.084755549832, 'normal', 3.8430498443564814e-05, 'normal', 1.0223405304554098, 1.0038230409106332, 0.991382502544975], ['female', 'Cops8', 'c269', datetime.date(2022, 12, 19), 27.4, 'abnormal', 'cranial sutures open', 496.8466217653884, 'normal', 0.0018254486760693, 'normal', 1.001908190938637, 0.9938153041899476, 0.9745614564896808], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.76, 'normal', None, 382.8336398244055, 'normal', 0.0039583413396871, 'normal', 1.0228615076949583, 1.0023151982797027, 0.9702881521015708], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 27.56, 'normal', None, 422.9051845108213, 'normal', 0.0028054263863802, 'normal', 1.025309150251252, 0.9736843107853094, 0.9598089144778348], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.24, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 601.7304472067851, 'normal', 0.0002497982398831, 'normal', 0.994987571834688, 0.992005138275806, 0.9375813938415778], ['female', 'Cops8', 'c269', datetime.date(2022, 12, 19), 27.07, 'normal', 'T1 not fused', 481.8787991050796, 'normal', 0.8664348026593905, 'abnormal', 1.3618641664351785, 1.1075835590605407, 0.9026463185429506], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.38, 'normal', 'T1 not fused, kyphosis, cranial sutures open mild', 587.877764429123, 'normal', 0.0075323776949387, 'normal', 1.0062733982768488, 0.963978712409656, 0.9310874455876328], ['male', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.46, 'abnormal', 'cranial sutures open', 520.2269823677946, 'normal', 0.0009031167134237, 'normal', 1.0065890601361356, 0.9915292543398976, 0.9774482950051472], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.58, 'normal', 'pectus excavatum', 431.32234448881655, 'normal', 0.0013066369470812, 'normal', 1.0060773743751743, 0.9960713084876898, 0.9736250212595592], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.41, 'abnormal', 'cranial sutures open', 664.7985197013512, 'normal', 0.0135851811998001, 'normal', 0.982986254359201, 0.9750576699409512, 0.9542199194166996], ['female', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 26.71, 'normal', 'T1 not fused, scoliotic', 1050.4449586065302, 'abnormal', 0.0009991929595326, 'normal', 1.029452331027583, 0.9953348913404656, 0.9772363118800268], ['female', 'Cops8', 'c269', datetime.date(2022, 12, 19), 26.86, 'abnormal', 'T1 not fused, shorter tail, cranial sutures open', 540.9046803753567, 'normal', 0.023308097306022, 'normal', 1.0225338544759457, 0.9802106362289248, 0.9628944169271938], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.22, 'abnormal', 'T1 not fused, rostrum malformation + cranial sutures open severe', 3153.7460465361924, 'abnormal', 0.3462395757272972, 'abnormal', 1.0414191336861571, 0.957805901420524, 0.9225527897053428], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.12, 'abnormal', 'cranial sutures open severe', 700.5928781932726, 'normal', 0.0156027823680873, 'normal', 1.011100332639527, 0.9892526588889072, 0.9528757571710412], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.53, 'abnormal', 'scoliotic, T3+4 fused, RH II. Osteoneogenesis, cranial sutures open', 449.7506526071119, 'normal', 0.0001152914953306, 'normal', 1.0016383825516286, 0.9916492958221054, 0.9633123777170364], ['male', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 27.19, 'normal', None, 520.5197595746995, 'normal', 0.0075515929441604, 'normal', 1.0358423834820507, 0.9844644571508602, 0.9449578695627628], ['male', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 26.36, 'normal', 'T1 not fused', 283.7788622934418, 'normal', 0.0, 'normal', 1.0004197719573809, 0.9872054657294322, 0.9628847880903432], ['male', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 27.29, 'normal', 'T1 not fused, pectus excavatum', 460.1078466404084, 'normal', 0.1099496560470389, 'abnormal', 1.0257200116241567, 1.0001995726688022, 0.9662584166791908], ['male', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.56, 'normal', 'T1 not fused, pectus excavatum', 523.3133919790605, 'normal', 0.0001921524922178, 'normal', 1.016402175472184, 0.9768360281911184, 0.9636430840245817], ['male', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.43, 'normal', None, 375.092948160948, 'normal', 0.0007301794704277, 'normal', 0.9861150480853148, 0.9801322560975688, 0.9606569032138472], ['male', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 26.45, 'normal', 'scoliotic', 568.9695817813482, 'normal', 0.0096076246108912, 'normal', 1.017282363507541, 0.9602376512476456, 0.9545502047384306], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.74, 'normal', 'L6=half S0, RH II. Osteoneogenesis', 727.7423469711374, 'normal', 0.0118173782713961, 'normal', 1.0048720693797035, 0.9835770838925058, 0.9717815300045324], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.04, 'normal', 'scoliotic', 619.9230384271445, 'normal', 0.0083778486606971, 'normal', 1.0113934683640076, 0.9560579855002468, 0.9314711760738852], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.4, 'normal', None, 516.5561458125138, 'normal', 0.000172937242996, 'normal', 0.9929826911662658, 0.9837748489923254, 0.9403993223108458], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.21, 'abnormal', 'T1 not fused, LH II. Osteoneogenesis, cranial sutures open', 568.2888317616747, 'normal', 0.0, 'normal', 0.9883293627483064, 0.974122580489805, 0.9561948613132808], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.4, 'normal', 'T1 not fused', 317.5726081250766, 'normal', 0.0, 'normal', 0.9932021307483944, 0.9802304637513796, 0.9670844115142708], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.61, 'abnormal', 'T1 not fused, cranial sutures open', 398.3926616564908, 'normal', 0.0031897313708158, 'normal', 0.9912839642700372, 0.9836402041425302, 0.9386696359179432], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.74, 'abnormal', 'sternum crooked, cranial sutures open', 623.3615695525311, 'normal', 0.0011913454517505, 'normal', 0.997186915476572, 0.9717590380525424, 0.9610840598834364], ['male', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 27.37, 'normal', 'T1 not fused', 675.8220402502262, 'normal', 0.0030360093770416, 'normal', 1.0096375469276035, 0.9723669286238152, 0.9381308555838436], ['female', 'C57Bl/6NCrl', 'c269', datetime.date(2022, 12, 19), 26.73, 'normal', None, 462.7473004211788, 'normal', 0.0, 'normal', 0.9936759796401062, 0.9831880740082848, 0.9581518027921254], ['female', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 25.87, 'normal', 'scoliotic', 519.467360322536, 'normal', 0.0043426463241228, 'normal', 1.0077034662573467, 0.9596092535221584, 0.9454609775875392], ['female', 'Nkiras1', 'c269', datetime.date(2022, 12, 19), 26.69, 'normal', 'T1 not fused, scoliotic', 417.5174835880791, 'normal', 0.0005956727258752, 'normal', 0.9928962813688031, 0.9836630600998209, 0.9488611871753868], ['male', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 27.15, 'normal', None, 534.769356588625, 'normal', 0.0085123554052496, 'normal', 1.040833920099119, 1.0110625992699012, 0.986792495403962], ['male', 'Vsx1', 'c269', datetime.date(2022, 12, 19), 27.47, 'normal', 'kyphosis+pectus excavatum', 500.00954232634393, 'normal', 0.0062257407478574, 'normal', 1.0238889527303354, 0.9954283822001284, 0.9763618710577592]]

[['male', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.73, 'normal', None, 482.2054051342475, 'normal', 0.0009607624610891, 'normal', 1.0101953647161506, 0.9907712072226093, 0.9783884134215955], ['male', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.21, 'normal', 'scoliotic, kyphosis', 478.88520787972897, 'normal', 0.0038238345951346, 'normal', 1.0105839896710784, 0.9787789956630408, 0.960154506598691], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.53, 'normal', None, 453.372490089337, 'normal', 0.0, 'normal', 1.0059668977015963, 0.9877812575441622, 0.9620647828101692], ['female', 'Wnt3a', 'c310', datetime.date(2023, 10, 16), 25.91, 'normal', 'T1 not fused, caudal vertebrae fused + deformed,', 376.4704409298248, 'normal', 0.0017678029284039, 'normal', 0.998826569572971, 0.9700592056795786, 0.9543635331752404], ['male', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 27.77, 'normal', None, 419.0052201035914, 'normal', 0.0027477806387148, 'normal', 1.0426364418266807, 1.0160652359605251, 0.9990023165973037], ['male', 'Atp5b', 'c310', datetime.date(2023, 10, 16), 27.33, 'abnormal', 'scoliotic, T1 not fused, pectus excavatum, RHp II. Osteoneogenesis, cranial sutures open', 699.8181185251256, 'normal', 0.0149110333961031, 'normal', 1.060529097137101, 1.034558130601525, 0.9840835480847918], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.68, 'normal', None, 627.4721885293619, 'normal', 0.0042273548287921, 'normal', 0.9990268308956338, 0.9922257151966938, 0.97105572517602], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.24, 'normal', 'RHp II. Osteoneogenesis', 382.7213594172438, 'normal', 0.0, 'normal', 0.995903610703424, 0.9852231811175056, 0.949164408988248], ['female', 'Wnt3a', 'c310', datetime.date(2023, 10, 16), 25.43, 'normal', 'T1 not fused, left C7 rib rudiment', 642.4041696115768, 'normal', 0.0045155835671188, 'normal', 0.9875839535889096, 0.9522859868033732, 0.915107452440165], ['male', 'Atp5b', 'c310', datetime.date(2023, 10, 16), 26.25, 'abnormal', 'T1 not fused, kyphosis, pectus excavatum, cranial sutures open', 603.2650580265877, 'normal', 0.0081856961684793, 'normal', 1.0416032652160228, 1.020713202329872, 0.9748936828824606], ['male', 'Wnt3a', 'c310', datetime.date(2023, 10, 16), 26.65, 'normal', 'T1 not fused, caudal vertebrae fused in distal part of the tail,', 426.5409288470137, 'normal', 7.686099688712963e-05, 'normal', 1.0076426307508837, 0.9993542954954912, 0.9668828221527204], ['female', 'Wnt3a', 'c310', datetime.date(2023, 10, 16), 26.05, 'normal', 'T1 not fused, C3+C4 fused, right C7 rib rudiment, kyphosis', 685.0154877066864, 'normal', 0.0026324891433841, 'normal', 1.002899697367914, 0.9701911431352604, 0.9296733997781912], ['female', 'Wnt3a', 'c310', datetime.date(2023, 10, 16), 26.87, 'normal', 'T1 not fused, scoliotic, left C7 rib rudiment + right C7 process abnormal, kyphosis, body of L3 rounded and malformed, pectus excavatum', 437.7455154940728, 'normal', 0.0, 'normal', 0.9957378295146464, 0.9887935845172277, 0.9648045166348214], ['male', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.93, 'normal', 'T1 not fused', 362.88971667788405, 'normal', 0.0, 'normal', 1.0248569000163792, 0.9951504415294036, 0.9815892032574892], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.16, 'normal', 'T1 not fused, L6 = half S0', 545.3464928047244, 'normal', 0.0021905384112831, 'normal', 1.003570824682673, 0.98943819094293, 0.9579163426686568], ['female', 'Wnt3a', 'c310', datetime.date(2023, 10, 16), 26.56, 'abnormal', 'T1 not fused, kyphosis, body of L3 rounded and malformed, cranial sutures open', 613.1245574615642, 'normal', 0.0025940586449406, 'normal', 1.0092584477386313, 0.990321311118824, 0.962549771117816], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.93, 'normal', None, 655.6354313814398, 'normal', 0.0, 'normal', 0.9969978431423812, 0.9951796983503812, 0.9666179581376424], ['male', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 27.25, 'normal', None, 419.7659958571208, 'normal', 0.0038430498443564, 'normal', 1.032754781732508, 1.0234791031379027, 0.9768553804806236], ['male', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.79, 'abnormal', 'cranial sutures open', 394.1941259324144, 'normal', 0.0002497982398831, 'normal', 1.002678628025484, 0.99299542971439, 0.9770231465906388], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.02, 'normal', 'Processus spinosus missing', 612.444913445618, 'normal', 7.686099688712963e-05, 'normal', 1.02203465613426, 0.9981926538259158, 0.9740907953107552], ['female', 'C57Bl/6NCrl', 'c310', datetime.date(2023, 10, 16), 26.07, 'normal', None, 548.528657273635, 'normal', 0.0378924714653549, 'normal', 1.0151602494606586, 0.9723944939511204, 0.958227323028876]]
[['male', 'Ptprz1', 'c263', datetime.date(2022, 11, 7), 26.6, 'normal', None, 430.44218677751945, 'normal', 0.0007109642212059, 'normal', 1.05425556705263, 0.9900733987664329, 0.963788416411933], ['male', 'C57Bl/6NCrl', 'c263', datetime.date(2022, 11, 7), 26.69, 'normal', 'sternum malformation; T1 not fused', 333.6530179907922, 'normal', 0.0, 'normal', 1.0311485875549558, 1.0048061186642905, 0.9813428354571296], ['male', 'Ptprz1', 'c263', datetime.date(2022, 11, 7), 26.44, 'normal', None, 466.3658024646472, 'normal', 0.0035932516044733, 'normal', 0.9944366525847894, 0.9800868619425188, 0.9694793335709858], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.85, 'abnormal', 'cranium sutures open; rostrum rounded; T1 not fused', 470.03019248257766, 'normal', 0.0013834979439683, 'normal', 1.003803691460062, 0.9914079937114082, 0.9616153493417736], ['female', 'C57Bl/6NCrl', 'c263', datetime.date(2022, 11, 7), 27.08, 'abnormal', 'squeezed; cranium sutures open; T1 not fused', 490.7768099466072, 'normal', 0.0072441489566119, 'normal', 1.0053238263629, 0.9627812692046226, 0.9326593777680888], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.49, 'normal', 'T1 not fused', 595.9710022643422, 'normal', 0.0031897313708158, 'normal', 1.0021062366723186, 0.972666710015742, 0.946052288082348], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 27.26, 'normal', 'hindpaw move; pectus excavatum; T1 not fused', 448.6000447319465, 'normal', 0.0, 'normal', 1.0276153264780368, 1.0020453364337143, 0.9909067134283992], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.69, 'abnormal', 'cranium sutures open', 331.42509631469693, 'normal', 0.0, 'normal', 1.0053087544084014, 0.9888132389035652, 0.9737877457547774], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.01, 'normal', 'T1 not fused', 961.2124651104464, 'normal', 0.1117366742246647, 'abnormal', 1.01700882718656, 0.9844686188922058, 0.9116530306901968], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 27.5, 'normal', 'lordosis high', 618.5004099224958, 'normal', 0.0367587717612697, 'normal', 0.9970069495968426, 0.9726667258678784, 0.9437215249082362], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.84, 'normal', 'pectus excavatum', 737.2033305129795, 'normal', 0.0132200914645862, 'normal', 1.0028511634577058, 0.9807312538631596, 0.9517231809505178], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.91, 'normal', 'C7 rib rudiment', 539.3826283326973, 'normal', 0.0098766380999961, 'normal', 1.019234779236116, 0.9934187990520577, 0.9625389753994952], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.63, 'abnormal', 'cranium sutures open', 627.9506881460643, 'normal', 0.0136236116982437, 'normal', 1.001964579109739, 0.9647019801448738, 0.9399095810800076], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.35, 'abnormal', 'cranium sutures open; pectus excavatum', 734.9697683926948, 'normal', 0.0018446639252911, 'normal', 1.0009244932776893, 0.9595472102820672, 0.9476559764339714], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 27.52, 'normal', None, 538.4746018067361, 'normal', 0.0011721302025287, 'normal', 1.019504525861182, 1.0038197803126074, 0.995067235819263], ['male', 'Mpp1', 'c263', datetime.date(2022, 11, 7), 26.26, 'abnormal', 'pectus excavatum; C7 + T1 not fused; rostrum rounded', 897.6651693319683, 'normal', 0.009972714346105, 'normal', 1.005694005461685, 0.9730037909350072, 0.956048893458856], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.4, 'abnormal', 'cranium sutures open', 535.0769843475965, 'normal', 0.0050343952961069, 'normal', 0.9834116246473852, 0.9585662057929716, 0.933946825793511], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 27.1, 'normal', 'pectus excavatum', 732.261136110834, 'normal', 0.0104530955766496, 'normal', 1.0891840813168834, 1.0157160131202672, 0.9820784870765786], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 27.55, 'normal', 'scoliotic; T1 not fused', 520.9231654715928, 'normal', 0.0201567964336497, 'normal', 1.0185596167035726, 0.9874922662101684, 0.9478645856478376], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 25.88, 'normal', None, 457.0511980007982, 'normal', 0.001671726682295, 'normal', 0.9830285214142768, 0.961704579421206, 0.9496838655299992], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 27.04, 'normal', 'Hindpaw: R II. osteoneogenesis', 740.0188488067777, 'normal', 0.0264401829291725, 'normal', 1.0337362175983331, 0.9907652369406956, 0.9752183926806044], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 23.97, 'abnormal', 'cranium sutures open; CA21+', 1290.0729559745794, 'abnormal', 0.1004573229314784, 'abnormal', 0.9157683328716052, 0.8968644697676676, 0.8861994440968352], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 27.29, 'normal', 'pectus excavatum', 383.890025230715, 'normal', 0.0, 'normal', 1.0047734852241867, 0.9852519918578452, 0.9697893625010636], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.96, 'normal', None, 421.9708885944643, 'normal', 0.0, 'normal', 1.014290307624925, 0.9767852248881036, 0.969635553671118], ['female', 'Ptprz1', 'c263', datetime.date(2022, 11, 7), 26.44, 'normal', 'T1 not fused', 675.6082986531605, 'normal', 0.0101264363398793, 'normal', 0.9858485628159652, 0.9740288387115524, 0.9414260191699548], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.74, 'normal', 'pectus excavatum; T1 not fused', 557.2585593382008, 'normal', 0.020925406402521, 'normal', 1.0299739485401724, 0.999695940432665, 0.9728133829275408], ['male', 'C57Bl/6NCrl', 'c263', datetime.date(2022, 11, 7), 27.27, 'normal', 'pectus excavatum', 478.583597862927, 'normal', 0.002113677414396, 'normal', 1.0149282799454349, 0.9961330852392222, 0.9783001402621558], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.88, 'normal', None, 445.6906984051358, 'normal', 0.0, 'normal', 0.9931192810596569, 0.9679249452567548, 0.94755833070068], ['male', 'C57Bl/6NCrl', 'c263', datetime.date(2022, 11, 7), 26.63, 'normal', None, 481.60721827713326, 'normal', 0.0064755389877406, 'normal', 1.0177014112248373, 0.987013114607476, 0.9764259815839768], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.7, 'normal', None, 503.20893497709056, 'normal', 0.0018062334268475, 'normal', 1.009655686378688, 0.9882298941147104, 0.9725296861837492], ['female', 'C57Bl/6NCrl', 'c263', datetime.date(2022, 11, 7), 27.08, 'normal', 'T1 not fused', 526.1972403990429, 'normal', 0.0020176011682871, 'normal', 1.0106492373041027, 0.989294813654744, 0.961376072834622], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 25.76, 'abnormal', 'paw move; cranium sutures open', 693.0297804941134, 'normal', 0.0037661888474693, 'normal', 0.9989900212662502, 0.9613615320055102, 0.9466194228360147], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.64, 'normal', 'pectus excavatum; rib nodes; T1 not fuse', 603.9753690376953, 'normal', 0.0007493947196495, 'normal', 1.0167578669953168, 1.009799499986484, 0.9725951864012335], ['female', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.01, 'abnormal', 'cranium sutures open; pectus excavatum; T1 not fused', 323.8636544578096, 'normal', 0.0, 'normal', 1.005664233999188, 0.9898861548367984, 0.9771259966487178], ['male', 'Ptprz1', 'c263', datetime.date(2022, 11, 7), 26.42, 'normal', 'pectus excavatum', 520.9596761109141, 'normal', 0.0048614580531109, 'normal', 1.0114588585992992, 0.9699006313950814, 0.9601468000831488], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 26.44, 'normal', 'cranium sutures open', 762.1682886923293, 'normal', 0.0279581876176934, 'normal', 1.0025442311238535, 0.9882697192849592, 0.9745559959704984], ['female', 'C57Bl/6NCrl', 'c263', datetime.date(2022, 11, 7), 26.66, 'normal', 'T1 not fused', 575.3427829868651, 'normal', 0.0047461665577802, 'normal', 0.9959427091844528, 0.9782275778990264, 0.9407051212676456], ['female', 'Ptprz1', 'c263', datetime.date(2022, 11, 7), 26.71, 'abnormal', 'cranium sutures open; C3 not fused - half to C2', 1464.1246899031976, 'abnormal', 0.0605856807962799, 'normal', 0.9980510876992352, 0.984818466359486, 0.9320202279735016], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.51, 'normal', None, 507.3416968955805, 'normal', 0.0072633642058337, 'normal', 1.0125815734700034, 1.0011976117387396, 0.9673349841726936], ['male', 'Heph', 'c263', datetime.date(2022, 11, 7), 27.24, 'normal', None, 396.4705699086862, 'normal', 0.0020944621651742, 'normal', 0.993137511298554, 0.9744488296541908, 0.9475750113550973], ['female', 'Heph', 'c263', datetime.date(2022, 11, 7), 27.01, 'abnormal', 'cranium sutures open; T1 not fused', 601.2453560597513, 'normal', 0.006533184735406, 'normal', 1.0115522744022625, 0.9799137321933982, 0.9692926569832137], ['male', 'Parva', 'c263', datetime.date(2022, 11, 7), 26.64, 'normal', 'scoliotic; T1 not fused', 645.918733914796, 'normal', 0.0045540140655624, 'normal', 1.0150010148792463, 0.9974484855050664, 0.9536802610152076], ['female', 'Ptprz1', 'c263', datetime.date(2022, 11, 7), 26.14, 'normal', None, 656.8842998544028, 'normal', 0.016947849813612, 'normal', 1.01647692863084, 0.9644907917441444, 0.9286688634820948]]

[['male', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 27.1, 'normal', None, 302.3032732174857, 'normal', 0.0, 'normal', 1.0233248207575862, 1.0134286889188535, 0.9938059989073784], ['female', 'Ism1', 'c305', datetime.date(2023, 9, 11), 25.56, 'abnormal', 'scoliotic, kyphosis, rostrum malformation, cranial sutures open', 1986.862952870653, 'abnormal', 0.1625417931670573, 'abnormal', 1.046342683951238, 1.0292998890785776, 0.944224450217855], ['male', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 25.81, 'normal', 'kyphosis, lordosis', 570.593822222798, 'normal', 0.0016525114330732, 'normal', 0.986742404081128, 0.9737075283637612, 0.9619244605732704], ['male', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 26.58, 'normal', 'T1 not fused', 375.1973445191165, 'normal', 9.607624610891204e-05, 'normal', 1.0404060857224082, 1.013348609918476, 0.9823591891990312], ['male', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 26.51, 'normal', 'L6 = half S0', 1248.5638708251724, 'abnormal', 0.0822028361707851, 'normal', 1.01714757575745, 0.9910762522358036, 0.9653349688038352], ['female', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 27.16, 'normal', 'scoliotic', 427.7523982809498, 'normal', 0.0088197993927981, 'normal', 1.0473462242882197, 1.0119095547296102, 0.9943880932806632], ['male', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 26.82, 'normal', 'T1 not fused', 479.6449731994664, 'normal', 0.0010952692056415, 'normal', 0.9970894373827798, 0.988787790658456, 0.9685944331572856], ['male', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 26.8, 'normal', 'T1 not fused', 429.8672433071688, 'normal', 0.0037277583490257, 'normal', 1.0438130480431211, 0.9946102847541416, 0.9848855002599296], ['male', 'Ism1', 'c305', datetime.date(2023, 9, 11), 25.61, 'abnormal', 'T1 not fused, scoliotic, kyphosis, tail tip deformed, rostrum malformation, nasalia deformed', 1911.2827656760217, 'abnormal', 0.2280273625148918, 'abnormal', 1.04216810190181, 1.027493420240017, 0.9754075210435674], ['female', 'Trex1', 'c305', datetime.date(2023, 9, 11), 24.47, 'abnormal', 'T1 not fused, scoliotic, kyphosis, zygomatic arch deformed', 1764.319478280402, 'abnormal', 0.1669805157372891, 'abnormal', 0.9770372394997404, 0.926826790613914, 0.9096958562052722], ['female', 'Ism1', 'c305', datetime.date(2023, 9, 11), 25.25, 'abnormal', 'T1 not fused, scoliotic mild, rostrum malformation, nasalia deformed, cranial sutures open', 2349.197421179605, 'abnormal', 0.2289304792283155, 'abnormal', 1.061874108898286, 0.99477080232854, 0.9441400777277784], ['male', 'Ism1', 'c305', datetime.date(2023, 9, 11), 24.95, 'abnormal', 'rostrum malformationm, nasalia deformed, cranial sutures open', 1922.1101456841116, 'abnormal', 0.1807770646785289, 'abnormal', 1.0409438680461467, 1.030929623856278, 0.9623441474019414], ['male', 'Ism1', 'c305', datetime.date(2023, 9, 11), 25.97, 'abnormal', 'rostrum malformation, nasalia deformed, cranial sutures open, tail tip deformed', 1892.624683305498, 'abnormal', 0.241170592982591, 'abnormal', 1.0315679975847207, 1.0160431896307796, 0.937453712095465], ['female', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 26.2, 'normal', 'T1 not fused', 560.446071519485, 'normal', 0.0043426463241228, 'normal', 1.0066510418716013, 0.9971608983110676, 0.9608381577863928], ['female', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 26.34, 'normal', 'T1 not fused, pectus excavatum mild, LHP II. Osteoneogenesis', 384.463052944187, 'normal', 0.0014795741900772, 'normal', 0.9985423586088338, 0.9924180552886088, 0.9578727756991972], ['male', 'Ism1', 'c305', datetime.date(2023, 9, 11), 25.76, 'abnormal', 'scoliotic, pectus excavatum, rostrum malformation, nasalia deformed, cranial sutures open', 2879.323717275884, 'abnormal', 0.4043849198724107, 'abnormal', 1.0504633365871825, 0.9949647439281124, 0.9648810683399268], ['female', 'Ism1', 'c305', datetime.date(2023, 9, 11), 24.82, 'abnormal', 'T1 not fused, rostrum malformation, nasalia deformed, cranial sutures open', 1537.2217427269316, 'abnormal', 0.1392144806118135, 'abnormal', 1.0529454463473396, 1.0335170365662392, 0.9523477882006666], ['female', 'Ism1', 'c305', datetime.date(2023, 9, 11), 26.03, 'abnormal', 'scoliotic, rostrum malformation, cranial sutures open', 1669.0852063446118, 'abnormal', 0.1332385381038392, 'abnormal', 1.0432600830789769, 1.0187629977884232, 0.9619105896222896], ['female', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 26.64, 'abnormal', 'T1 not fused, cranial sutures open', 537.782734122832, 'normal', 0.0014795741900772, 'normal', 1.0071272408048213, 0.982110408215441, 0.9641360249171068], ['female', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 26.9, 'abnormal', 'scoliotic, kyphosis, lordosis, cranial sutures open', 608.1685652981419, 'normal', 0.000614887975097, 'normal', 1.035356230463801, 0.986244148157476, 0.9664376212516672], ['male', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 27.56, 'normal', 'scoliotic, kyphosis, T1-T2 transposed, left C7 rib rudiment', 574.6779280356379, 'normal', 0.0061680950001921, 'normal', 1.02306134280674, 0.9937333663604682, 0.9543368545475912], ['male', 'Ism1', 'c305', datetime.date(2023, 9, 11), 25.09, 'abnormal', 'kyphosis, pectus excavatum, left costal cartilage ossified, rostrum malformation, nasalia deformed', 2311.6656028624766, 'abnormal', 0.2786787594635102, 'abnormal', 1.0390157388983428, 1.026412060647849, 0.9766271960767476], ['male', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 27.25, 'normal', None, 882.723411278183, 'normal', 0.0067445524768456, 'normal', 1.027178359092065, 0.983611789707138, 0.9674113267793684], ['male', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 27.1, 'normal', None, 426.7450356181855, 'normal', 0.0, 'normal', 1.0206482261495629, 0.9942312260649134, 0.9848672410347812], ['male', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 26.87, 'normal', None, 403.1480244108517, 'normal', 0.0007109642212059, 'normal', 1.02806125164786, 0.9954399430180144, 0.98681449818094], ['male', 'Trak1 KO', 'c305', datetime.date(2023, 9, 11), 26.51, 'normal', 'T1 not fused', 393.4856197617528, 'normal', 0.0033050228661465, 'normal', 1.0193767971338512, 1.0025259097941657, 0.9761554036546388], ['female', 'C57Bl/6NCrl', 'c305', datetime.date(2023, 9, 11), 25.91, 'normal', None, 930.3519482965884, 'normal', 0.0175435225394873, 'normal', 0.9773222076642892, 0.9714334763879184, 0.9350373782917426], ['female', 'Ces1c', 'c305', datetime.date(2023, 9, 11), 26.97, 'abnormal', 'cranial sutures open', 576.940931562034, 'normal', 0.006533184735406, 'normal', 1.031703170881147, 1.0026135406577454, 0.9657515156930327]]
[['female', 'C57Bl/6NCrl', 'c281', datetime.date(2023, 3, 13), 26.34, 'abnormal', 'Cranium sutures open; T1 not fused', 518.8602695304437, 'normal', 0.0006917489719841, 'normal', 1.019914173486451, 0.986121176366702, 0.9526967388508952], ['male', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.72, 'normal', None, 620.2765462389174, 'normal', 0.0083970639099189, 'normal', 1.035682383201593, 1.008076202228282, 0.9872192694421832], ['male', 'C57Bl/6NCrl', 'c281', datetime.date(2023, 3, 13), 27.28, 'normal', None, 1126.9546354734775, 'abnormal', 0.001229775950194, 'normal', 1.025344666700314, 1.0151358247913378, 0.9853827871744594], ['female', 'C57Bl/6NCrl', 'c281', datetime.date(2023, 3, 13), 27.01, 'abnormal', 'tendon ossification (femur); Cranium sutures open; T1 not fused; baculum weak', 474.5030775878508, 'normal', 0.0032089466200376, 'normal', 0.9995474877346412, 0.9930455566196243, 0.9739518165467514], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.14, 'normal', 'Hip ossification; scoliotic; T1 not fused', 588.3470793606045, 'normal', 0.0001152914953306, 'normal', 1.0070530225816734, 0.9712248233904897, 0.929796265263028], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.39, 'normal', 'Sternum malformation', 495.3943506008417, 'normal', 0.0012489911994158, 'normal', 0.9981580038159836, 0.9781056928877214, 0.9520690683851064], ['male', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.91, 'normal', None, 294.539904340042, 'normal', 0.0, 'normal', 1.003669548725974, 0.998339611556878, 0.9786852742658544], ['female', 'C57Bl/6NCrl', 'c281', datetime.date(2023, 3, 13), 26.63, 'normal', 'scoliotic; T1 not fused', 633.291749395619, 'normal', 0.0042657853272356, 'normal', 1.0065950273234534, 0.990145350825048, 0.96048967390008], ['male', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 27.42, 'normal', None, 507.7425257228024, 'normal', 0.0019407401714, 'normal', 1.0188939363169578, 0.9930721352884568, 0.9797740498613996], ['male', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 27.61, 'normal', 'pectus excavatum', 387.6074453276896, 'normal', 0.006533184735406, 'normal', 1.0041942105912505, 0.9950426838570772, 0.9621167653152116], ['male', 'Klhl6', 'c281', datetime.date(2023, 3, 13), 26.83, 'normal', 'Hip ossification', 747.7289467431119, 'normal', 0.0056877137696475, 'normal', 1.0050229115408265, 0.983250147678921, 0.9529747942404816], ['male', 'Gnl2', 'c281', datetime.date(2023, 3, 13), 25.3, 'normal', 'scoliotic; kyphosis high; C7 rib rudiment; tail broken', 1433.1031396615497, 'abnormal', 0.1597555820298989, 'abnormal', 0.9911967026820095, 0.9502462868320172, 0.9163319162491762], ['male', 'Faim2', 'c281', datetime.date(2023, 3, 13), 27.02, 'normal', 'kyphosis high', 454.113934399132, 'normal', 0.0075515929441604, 'normal', 1.0315501152690416, 1.0041095305973564, 0.995428866563], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.6, 'normal', None, 559.746482572503, 'normal', 0.0018062334268475, 'normal', 1.003780590639331, 0.9879637021247368, 0.969470592902224], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.98, 'normal', None, 430.3140270055178, 'normal', 0.006264171246301, 'normal', 0.9879418863043912, 0.9691630460659396, 0.9459400437785834], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.15, 'normal', 'pectus excavatum; baculum weak', 664.1401154931989, 'normal', 0.0046308750624495, 'normal', 1.034718459568125, 0.9904081773949276, 0.9679826250627293], ['male', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.94, 'normal', 'kyphosis high', 432.1711798879511, 'normal', 0.0022097536605049, 'normal', 1.0298627872247097, 1.0112595509752442, 0.9747247653927004], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.74, 'normal', None, 486.16771936430416, 'normal', 0.004054417585796, 'normal', 1.0138954824595443, 0.9799700607938524, 0.9558939933288456], ['male', 'Gnl2', 'c281', datetime.date(2023, 3, 13), 25.42, 'abnormal', 'rostrum rounded; Tendon ossification - Achilles & forepaws; T1 not fused', 2209.0558177325984, 'abnormal', 0.3736789516160024, 'abnormal', 1.0394546261596722, 1.005521005045431, 0.9156004929131876], ['male', 'Klhl6', 'c281', datetime.date(2023, 3, 13), 26.34, 'normal', 'C7 rib rudiment', 303.26662802478427, 'normal', 0.0, 'normal', 1.0157011331943917, 0.994433242141446, 0.9679355456787052], ['female', 'Gnl2', 'c281', datetime.date(2023, 3, 13), 26.45, 'normal', 'T2 proc. spinosus reduction', 776.2896701010618, 'normal', 0.0144306521655585, 'normal', 0.9973638153480424, 0.9839312621892444, 0.9389821796011912], ['male', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.24, 'normal', None, 1243.430757960807, 'abnormal', 0.0032281618692594, 'normal', 1.0053951517490658, 0.9712305793625956, 0.9426400206294008], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.59, 'normal', 'T1 not fused', 419.7314174597822, 'normal', 0.001229775950194, 'normal', 1.0175627945597443, 0.9929854385529836, 0.9694000486822388], ['male', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.38, 'normal', None, 871.3790364869345, 'normal', 0.0402175166211905, 'normal', 1.0140862156379669, 0.974595730266805, 0.9544249787657024], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.38, 'normal', 'move', 526.6875281468554, 'normal', 0.0002690134891049, 'normal', 0.984939119662303, 0.9800629891474248, 0.9528333504939396], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.44, 'normal', 'baculum weak', 326.81689799543534, 'normal', 0.0, 'normal', 1.008177755044717, 0.994107593912502, 0.9714531424036652], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 27.12, 'normal', None, 662.239346704101, 'normal', 0.0157565043618615, 'normal', 1.0034810106440126, 0.9820748448492864, 0.9378713140958798], ['male', 'C57Bl/6NCrl', 'c281', datetime.date(2023, 3, 13), 26.96, 'normal', 'Hindpaw: L II. osteoneogenesis; T1 not fused', 378.2425099804674, 'normal', 0.0005764574766534, 'normal', 1.022009126931033, 0.9821481525877171, 0.9742338121991904], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.73, 'abnormal', 'Cranium sutures open; pectus excavatum', 544.7836569560137, 'normal', 0.0009223319626455, 'normal', 1.0119874735050085, 0.9952125326476584, 0.9726929581723468], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.35, 'normal', 'T1 not fused', 411.219594082341, 'normal', 0.0019215249221782, 'normal', 1.0125690269533134, 0.9727108347680536, 0.94861596838617], ['male', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.89, 'normal', 'lordosis low', 438.4851708869438, 'normal', 0.0016140809346297, 'normal', 0.9914705625845828, 0.969131249219474, 0.9344380101517572], ['male', 'C57Bl/6NCrl', 'c281', datetime.date(2023, 3, 13), 27.07, 'normal', 'pectus excavatum; T1 not fused', 344.157603567082, 'normal', 0.0009991929595326, 'normal', 1.0123777826359417, 0.9945697908864032, 0.9641574436482708], ['male', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 25.97, 'normal', 'pectus excavatum; C7 rib rudiments', 626.3814419293109, 'normal', 0.0134891049536912, 'normal', 1.001827393732166, 0.9731933137952088, 0.9358509631466072], ['female', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.33, 'abnormal', 'Cranium sutures open; T1 not fused', 980.2808686482516, 'abnormal', 0.0378540409669113, 'normal', 0.9856789536866276, 0.9796117760625536, 0.9242037710774772], ['male', 'Faim2', 'c281', datetime.date(2023, 3, 13), 26.31, 'normal', 'kyphosis high', 567.4101396366315, 'normal', 0.0023058299066138, 'normal', 1.0126889646289168, 0.982480096562384, 0.9577331894395152], ['female', 'Mrvi1', 'c281', datetime.date(2023, 3, 13), 26.76, 'normal', 'move; scoliotic', 699.6388658895153, 'normal', 0.0057453595173129, 'normal', 0.9924092620639088, 0.988134248774597, 0.9657969462429126], ['female', 'Gnl2', 'c281', datetime.date(2023, 3, 13), 26.68, 'normal', 'scoliotic; pectus excavatum; CA24+', 857.1682278702168, 'normal', 0.037258368241036, 'normal', 1.0159362538767198, 1.0001681000663012, 0.951633081249144]]

[['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.34, 'normal', 'T1 not fused', 412.6068917593766, 'normal', 0.015718073863418, 'normal', 1.0149799260513377, 0.9773167841480606, 0.9595950564055912], ['female', 'Mroh8', 'c285', datetime.date(2023, 4, 11), 27.19, 'abnormal', 'cranial sutures open', 470.6290499141016, 'normal', 0.0030552246262634, 'normal', 1.0129666485305768, 0.9808348653103074, 0.9696057512292592], ['male', 'Mroh8', 'c285', datetime.date(2023, 4, 11), 27.81, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 737.0591559670102, 'normal', 0.0393720456554321, 'normal', 1.040087119839919, 0.9915863460355288, 0.971447267997973], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.81, 'abnormal', 'pectus excavatum, cranial sutures open', 284.45664761949496, 'normal', 0.0, 'normal', 1.0195048965913511, 0.9966244054788868, 0.988664830240276], ['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 25.54, 'abnormal', 'cranial sutures open', 642.6887185464816, 'normal', 0.008204911417701, 'normal', 0.9975014907900496, 0.9673181723654664, 0.9236505903527044], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.84, 'normal', 'T1 not fused, pectus excavatum, kyphosis mild', 469.4270663796908, 'normal', 0.0, 'normal', 1.0359645087976763, 0.984172681928217, 0.9835061348829582], ['male', 'Parp1', 'c285', datetime.date(2023, 4, 11), 26.78, 'abnormal', 'pectus excavatum severe, cranial sutures open', 642.956867715319, 'normal', 0.0377195342223588, 'normal', 1.0077294164273376, 0.9792747988025988, 0.9160951785450472], ['male', 'Parp1', 'c285', datetime.date(2023, 4, 11), 25.9, 'normal', 'T1 not fused, pectus excavatum', 694.690749150129, 'normal', 0.0153337688789823, 'normal', 1.031872452965526, 1.0109193576384785, 0.9794271114907784], ['female', 'Parp1', 'c285', datetime.date(2023, 4, 11), 25.72, 'abnormal', 'scoliotic, Processus spinosus missing, cranial sutures open', 562.0145026540462, 'normal', 0.0113369970408516, 'normal', 0.9895628659384396, 0.965376784578582, 0.9325736135906164], ['male', 'Mroh8', 'c285', datetime.date(2023, 4, 11), 25.45, 'abnormal', 'cranial sutures open', 882.4363728193426, 'normal', 0.0808193382268168, 'normal', 0.9378385510221964, 0.9184410285308298, 0.9018340058829668], ['female', 'Mroh8', 'c285', datetime.date(2023, 4, 11), 26.27, 'normal', 'T1 not fused', 413.397169823096, 'normal', 0.0014027131931901, 'normal', 1.018401978696654, 0.9782570336039036, 0.9447140147190826], ['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.54, 'normal', None, 327.9877095112228, 'normal', 0.0008070404673148, 'normal', 1.0309577126124214, 0.9901076795116543, 0.9593968776496892], ['male', 'Zim1', 'c285', datetime.date(2023, 4, 11), 25.99, 'normal', 'pectus excavatum severe', 334.7949619948744, 'normal', 0.0030360093770416, 'normal', 1.022915383094723, 0.9940434174267964, 0.961062866779169], ['male', 'Parp1', 'c285', datetime.date(2023, 4, 11), 26.37, 'abnormal', 'cranial sutures open', 572.1758907512998, 'normal', 0.0293224703124399, 'normal', 1.016892803591295, 1.001088969560729, 0.9443259293015452], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 25.74, 'normal', 'T1 not fused, scoliotic', 543.6758778778991, 'normal', 0.0209446216517428, 'normal', 0.987860629417084, 0.9588825656412436, 0.9282151235517988], ['female', 'Zim1', 'c285', datetime.date(2023, 4, 11), 26.22, 'abnormal', None, 441.4262514486964, 'normal', 0.0001537219937742, 'normal', 1.0045419471633348, 0.9812761924026092, 0.9642555585921052], ['female', 'Zim1', 'c285', datetime.date(2023, 4, 11), 26.84, 'abnormal', 'LP II. Osteoneogenesis, cranial sutures open, pectus excavatum', 369.5991617101355, 'normal', 0.0007493947196495, 'normal', 1.0185072524886556, 0.9931604183675086, 0.9555887313754255], ['male', 'Mroh8', 'c285', datetime.date(2023, 4, 11), 26.73, 'abnormal', 'cranial sutures open mild', 402.52476697910106, 'normal', 0.0006341032243188, 'normal', 1.0380622315854675, 0.9896995505103, 0.9586669001210734], ['female', 'Parp1', 'c285', datetime.date(2023, 4, 11), 26.21, 'abnormal', 'pectus excavatum mild, cranial sutures open mild', 390.28496067327006, 'normal', 0.0033434533645901, 'normal', 0.9840632025984546, 0.9765481526761536, 0.9284917705833304], ['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.29, 'abnormal', 'cranial sutures open', 417.061920156117, 'normal', 0.0, 'normal', 0.9990292574926276, 0.9724067746850392, 0.9560465641028454], ['male', 'Zim1', 'c285', datetime.date(2023, 4, 11), 26.63, 'abnormal', 'pectus excavatum, cranial sutures open', 523.1598075892348, 'normal', 0.0130855847200338, 'normal', 1.0298455092451697, 1.0127124657984516, 0.9602262624504292], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 23.84, 'abnormal', 'T1-T2 transposed, kyphosis, rostrum malformation, malocclusion, cranial sutures open', 5577.878077274509, 'abnormal', 0.6911532992582914, 'abnormal', 1.068579235802562, 0.9284830199192128, 0.8590658313163736], ['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.04, 'normal', None, 378.69229510174057, 'normal', 0.0, 'normal', 0.9992910795453416, 0.9804072869802912, 0.9329374486499308], ['female', 'Parp1', 'c285', datetime.date(2023, 4, 11), 24.64, 'abnormal', 'C3 disrupted, partly fused to C4, cranial sutures open', 768.9729566874454, 'normal', 0.0300718650320894, 'normal', 0.9879902724250372, 0.9699386269743004, 0.9381775664025744], ['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.53, 'abnormal', 'T1 not fused, cranial sutures open', 460.5844368990018, 'normal', 0.0013258521963029, 'normal', 1.0017563170057144, 0.9859769284990372, 0.9572145663681276], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.56, 'abnormal', 'kyphosis, cranial sutures open', 459.61698447261983, 'normal', 0.001229775950194, 'normal', 1.0016605460596038, 0.987301819135817, 0.9714135931181282], ['male', 'Mroh8', 'c285', datetime.date(2023, 4, 11), 25.83, 'abnormal', 'T1 not fused, rostrum abnormal', 2113.2998352394243, 'abnormal', 0.3351908074247723, 'abnormal', 1.0568615162726829, 1.0286727808245075, 0.9441097199649128], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 25.51, 'abnormal', 'T1 not fused, kyphosis, rostrum malformation', 2036.1263758455027, 'abnormal', 0.2698205295722685, 'abnormal', 1.0618347542604618, 1.015831229892476, 0.9474340851005452], ['male', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.2, 'normal', 'T1 not fused', 626.5342118522658, 'normal', 0.0125091272433803, 'normal', 1.016902256986107, 0.9844817908692, 0.9697814157310192], ['female', 'C57Bl/6NCrl', 'c285', datetime.date(2023, 4, 11), 26.22, 'abnormal', 'cranial sutures open', 460.2457961576015, 'normal', 0.005380269782099, 'normal', 1.019066355387501, 0.9762059788993304, 0.9669012836639022]]
[['male', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 27.45, 'normal', 'T1 not fused', 460.58645020012784, 'normal', 0.0013258521963029, 'normal', 1.0071522210067276, 0.9973208051341392, 0.9714044831480168], ['female', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 27.7, 'normal', None, 583.7857137047423, 'normal', 0.0008070404673148, 'normal', 0.993511370079152, 0.9752289576246568, 0.9326645001848684], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 27.46, 'normal', None, 492.4482784952254, 'normal', 0.01660197532762, 'normal', 1.0414195379814943, 1.0148582400417965, 0.9967357222128372], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.8, 'normal', 'T1 not fused, tendon ossification', 436.76796621742426, 'normal', 0.0, 'normal', 0.9971749676598984, 0.9879574461787586, 0.9791559087028252], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.76, 'normal', 'T1 not fused', 620.8479882530172, 'normal', 0.0110679835517466, 'normal', 1.0010680745842744, 0.9782102538364688, 0.9558465390640172], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c275', datetime.date(2023, 1, 30), 25.32, 'abnormal', 'T1 not fused, PS missing, right C7 rib rudiment, 5 lumbar vertebrae, kyphosis, rostrum malformation', 2908.4422825366064, 'abnormal', 0.5363360362783905, 'abnormal', 1.0562858449985306, 0.9720388817079896, 0.9328337375883008], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.86, 'normal', None, 401.905858684773, 'normal', 0.005380269782099, 'normal', 1.0244633427278913, 0.9780169779566782, 0.9647474293253644], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.96, 'normal', 'T1 not fused, left C7 process abnormal + left T1 rib malformed', 462.7186881642089, 'normal', 0.0117597325237308, 'normal', 1.040981705782677, 0.995721778963963, 0.9770553029108654], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 27.14, 'normal', 'scoliotic, pectus excavatum mild', 368.02378610792914, 'normal', 0.0, 'normal', 1.0263366462935055, 1.0065222405890657, 0.9883772229303354], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c275', datetime.date(2023, 1, 30), 25.23, 'abnormal', 'T1 not fused, C6 not fused, PS missing, right C7 rib, 5 lumbar vertebrae, rostrum malformation', 2348.265266089241, 'abnormal', 0.1713808078090772, 'abnormal', 1.0219618347049646, 1.007644957842038, 0.9510554469916096], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.05, 'normal', 'T1 not fused', 350.4483893699994, 'normal', 0.0, 'normal', 1.0020155030933493, 0.9703545440798692, 0.9644006828848776], ['male', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 27.98, 'normal', 'T1 not fused', 461.7808936467116, 'normal', 0.0021328926636178, 'normal', 1.000291680267122, 0.9888396133624876, 0.959664655570234], ['female', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 26.5, 'normal', None, 634.8107753065115, 'normal', 0.0068214134737327, 'normal', 0.9798356563553562, 0.968725264411762, 0.9287190719284572], ['male', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 27.32, 'normal', 'kyphosis', 404.8680509733022, 'normal', 7.686099688712963e-05, 'normal', 1.0577310477879875, 1.01601788109874, 0.9996666229061684], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c275', datetime.date(2023, 1, 30), 27.25, 'normal', 'T1 not fused, PS missing, right C7 rib rudiment, 5 lumbar vertebrae', 873.194744964776, 'normal', 0.0784558625725375, 'normal', 1.0250499487281008, 1.0004041159539343, 0.9755858961206332], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 27.26, 'normal', None, 447.32928162855967, 'normal', 0.0187348679912378, 'normal', 1.032054667092139, 0.9844120008118178, 0.9590456717689638], ['male', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 27.14, 'normal', None, 694.5331371927866, 'normal', 0.0100880058414357, 'normal', 1.005732632979977, 0.9909512398125548, 0.9543615660253214], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c275', datetime.date(2023, 1, 30), 25.57, 'abnormal', 'scoliotic, T1 not fused, PS missing, 5 lumbar vertebrae, rostrum malformation', 2434.279581499608, 'abnormal', 0.2235309941969947, 'abnormal', 0.9994131248470416, 0.9797139955330524, 0.9324755755605988], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.62, 'normal', 'T1 not fused, RH II. Osteoneogenesis', 505.7778759921682, 'normal', 0.0069943507167287, 'normal', 1.0129155663543767, 0.9910510620125628, 0.9673313129748372], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.63, 'normal', 'T1 not fused, pectus excavatum, kyphosis mild', 474.8223101727392, 'normal', 0.0003843049844356, 'normal', 0.999642125025494, 0.9676803731373266, 0.9642077586243284], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 27.1, 'normal', 'PS missing, 5th + 6th cervical vertebrae fused together, scoliotic', 629.016644464211, 'normal', 0.003170516121594, 'normal', 1.016757497406598, 1.0013044395908424, 0.9665390747603928], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 26.52, 'normal', 'T1 not fused', 508.87662201641473, 'normal', 0.002382690903501, 'normal', 1.0157819000548196, 0.9769385115576924, 0.9583115298889602], ['female', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 28.15, 'abnormal', 'cranial sutures open', 552.9668250090062, 'normal', 0.0075708081933822, 'normal', 1.0123092370629556, 1.0021692262907826, 0.9518688106046256], ['female', 'Ccdc110', 'c275', datetime.date(2023, 1, 30), 26.42, 'abnormal', 'cranial sutures open mild', 436.590834457263, 'normal', 0.0001152914953306, 'normal', 1.008170055584314, 0.9915501366621632, 0.9590704115559864], ['male', 'C57Bl/6NCrl', 'c275', datetime.date(2023, 1, 30), 27.09, 'normal', None, 546.2908902970099, 'normal', 0.0059759425079743, 'normal', 1.0332797044016495, 0.9911924703043276, 0.9666837626463364]]
[['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 27.31, 'normal', 'pectus excavatum', 355.3517507417505, 'normal', 0.0006533184735406, 'normal', 1.0257099859976195, 1.0018792209370524, 0.9857038384959816], ['male', 'Faim2', 'c282', datetime.date(2023, 3, 23), 26.53, 'abnormal', 'C4+C5 fused together, tail move, cranial sutures open severe', 652.4429204946033, 'normal', 0.0258252949540755, 'normal', 1.0486561694354255, 1.0157341190241476, 0.9670643781990772], ['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.39, 'normal', 'T1 not fused', 383.5850284886798, 'normal', 0.0, 'normal', 1.0082283732963726, 0.9796953330785304, 0.9634545257273984], ['female', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 27.05, 'normal', 'T1 not fused', 979.239174862596, 'normal', 0.0032281618692594, 'normal', 1.0091444832603602, 0.980366260624328, 0.946882073969793], ['female', 'psKlcs', 'c282', datetime.date(2023, 3, 23), 26.99, 'normal', None, 1021.0446093294736, 'abnormal', 0.0324545559355904, 'normal', 1.01396196944253, 1.0036406433520026, 0.940265296977132], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.39, 'abnormal', 'T1 not fused, cranial sutures open', 629.4842704162784, 'normal', 0.0006341032243188, 'normal', 1.0157117756248244, 1.0042283297948935, 0.9749857279410428], ['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 27.28, 'normal', None, 469.7082559172059, 'normal', 0.0059567272587525, 'normal', 1.0274868307744174, 1.0069064747689405, 0.9824032274624837], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.33, 'abnormal', 'scoliotic, kyphosis, cranial sutures open', 626.46896246607, 'normal', 0.0137581184427962, 'normal', 1.0210646801022494, 0.9719363364354116, 0.9416767189949504], ['female', 'psKlcs', 'c282', datetime.date(2023, 3, 23), 26.57, 'normal', None, 489.5677407748327, 'normal', 0.0021521079128396, 'normal', 1.0126400626680114, 0.9835790277909312, 0.9692367662929716], ['male', 'psKlcs', 'c282', datetime.date(2023, 3, 23), 26.75, 'normal', 'T1 not fused', 499.254742667804, 'normal', 0.0028822873832673, 'normal', 1.0323273825902577, 0.9839265736931104, 0.9626751845901949], ['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.6, 'normal', 'T1 not fused', 538.4086782196284, 'normal', 0.0109142615579724, 'normal', 0.9949983138207824, 0.9767247383706672, 0.9590984776017948], ['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.86, 'normal', 'T1 not fused', 657.8837275939958, 'normal', 0.0110487683025248, 'normal', 1.0442146689602387, 1.0008824921221244, 0.99389699978196], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.63, 'abnormal', 'scoliotic, cranial sutures open', 688.8649276332227, 'normal', 0.0048038123054456, 'normal', 0.994736808942514, 0.9625384477457882, 0.946401316543634], ['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 27.03, 'normal', None, 522.8212866042072, 'normal', 0.0035163906075861, 'normal', 1.0307171435633595, 0.9883013134605656, 0.964654374748655], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 27.33, 'normal', 'T1 not fused', 375.4477500052985, 'normal', 0.0026132738941624, 'normal', 1.0221009406992143, 1.0014031428555608, 0.9741470735390678], ['male', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.98, 'normal', 'C5 incomplete + fused to C6', 728.1247437587632, 'normal', 0.0046500903116713, 'normal', 1.0279706783615856, 0.9938325293104184, 0.9625129486884674], ['female', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.71, 'normal', None, 478.3914756340804, 'normal', 0.0015180046885208, 'normal', 1.0108075712262818, 0.9875001357338584, 0.9838924640090186], ['male', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.79, 'normal', None, 685.5982929889035, 'normal', 0.0322624034433726, 'normal', 1.028623174391718, 0.9935014572155284, 0.9825070579795184], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 28.59, 'normal', 'T1 not fused', 1055.0996312109694, 'abnormal', 0.0026517043926059, 'normal', 1.0356789526096728, 1.0144955725810734, 0.983280789593591], ['female', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.88, 'normal', 'T1 not fused', 555.2273549356801, 'normal', 0.0081664809192575, 'normal', 0.9942959546553491, 0.9856605502965482, 0.9763369230602352], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 26.33, 'normal', 'RH I. Polydactyly', 750.36534330464, 'normal', 0.0023250451558356, 'normal', 0.992053780110713, 0.9797214813327946, 0.9394483706633372], ['female', 'Faim2', 'c282', datetime.date(2023, 3, 23), 26.68, 'abnormal', 'cranial sutures open', 406.42840609123056, 'normal', 0.003170516121594, 'normal', 1.0101586367729984, 0.9867937317357156, 0.9649561214540168], ['male', 'Faim2', 'c282', datetime.date(2023, 3, 23), 26.08, 'normal', 'pectus excavatum', 495.03539306204857, 'normal', 0.0038046193459129, 'normal', 1.0138787810046386, 0.9914205169526504, 0.9830254915628852], ['male', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 28.02, 'normal', 'tail move, pectus excavatum', 1226.9349202119251, 'abnormal', 0.0006341032243188, 'normal', 1.0095071265123703, 0.9925283282226304, 0.9689330298916116], ['male', 'Faim2', 'c282', datetime.date(2023, 3, 23), 27.58, 'normal', None, 490.09271251651023, 'normal', 0.0068790592213981, 'normal', 1.0169756693532035, 0.9996582749970568, 0.979079398345126], ['female', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.73, 'normal', None, 613.5345638800117, 'normal', 0.0106644633180892, 'normal', 0.9986978624259036, 0.9868558396150718, 0.956961142581515], ['female', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.7, 'normal', 'RH II. Osteoneogenesis', 682.9078428846499, 'normal', 0.0295146228046577, 'normal', 1.018033555474801, 0.983738696761112, 0.9595734168883886], ['male', 'Rnf34 tm1b', 'c282', datetime.date(2023, 3, 23), 26.58, 'normal', 'T1 not fused, pectus excavatum severe', 527.5794590949059, 'normal', 0.0039006955920218, 'normal', 1.0174854136236129, 0.987835022568573, 0.9620751843574472], ['female', 'C57Bl/6NCrl', 'c282', datetime.date(2023, 3, 23), 25.9, 'abnormal', 'T1 not fused, L6 = half S0, cranial sutures open', 909.4620192074946, 'normal', 0.0341647131163291, 'normal', 0.9870722374118648, 0.9540692893661, 0.9375885336135096]]

[['male', 'C57Bl/6NCrl', 'c283', datetime.date(2023, 3, 27), 27.13, 'normal', 'patella dislocation', 681.2010560642112, 'normal', 0.0164674685830675, 'normal', 0.9980818849220864, 0.99506214496913, 0.982351696097749], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.55, 'normal', 'T1 not fused, hindpaws move', 781.2732874558621, 'normal', 0.1314515199262134, 'abnormal', 1.0264404750159797, 0.962574730509406, 0.9478733585154228], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.93, 'normal', 'pectus excavatum', 735.7572649199864, 'normal', 0.0021521079128396, 'normal', 1.0193138572046512, 0.9825733524886886, 0.9573741914468202], ['male', 'C57Bl/6NCrl', 'c283', datetime.date(2023, 3, 27), 26.31, 'normal', 'T1 not fused', 499.5846416582416, 'normal', 0.0147765266515506, 'normal', 1.0074630170028187, 0.978908793142604, 0.9465045921346044], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.47, 'normal', 'T1 not fused, LH II. Mild osteoneogenesis', 621.3292944337431, 'normal', 0.0388340186772222, 'normal', 0.9938134821771454, 0.960980474384472, 0.9563661119059272], ['female', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.96, 'normal', 'T1 not fused', 742.7418148046877, 'normal', 0.0002305829906613, 'normal', 0.9869404249569728, 0.981394724737582, 0.946281362553248], ['female', 'Cobl', 'c283', datetime.date(2023, 3, 27), 26.88, 'normal', 'move, RH II. Osteoneogenesis', 570.0746230357192, 'normal', 0.0115867952807347, 'normal', 1.0027500774646232, 0.982560269679616, 0.9670150269179244], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c283', datetime.date(2023, 3, 27), 27.61, 'normal', None, 521.0372952433471, 'normal', 1.9215249221782407e-05, 'normal', 1.019867502897657, 1.0054823269260316, 0.9629363293883764], ['female', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 27.08, 'normal', None, 1764.8985645167795, 'abnormal', 0.1755313016409823, 'abnormal', 1.073760308101692, 0.9928742280690956, 0.9771944918215482], ['male', 'Cobl', 'c283', datetime.date(2023, 3, 27), 27.12, 'normal', 'L6 = half S0, pectus excavatum', 479.9866679383418, 'normal', 0.0098574228507743, 'normal', 1.0620500844408594, 1.0110364315013076, 0.994502131512686], ['female', 'Cobl', 'c283', datetime.date(2023, 3, 27), 24.94, 'abnormal', 'rostrum malformation', 2307.552734633261, 'abnormal', 0.2475884862226663, 'abnormal', 1.054100521071262, 0.980148433679196, 0.9519396541545276], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 27.13, 'normal', 'pectus excavatum', 761.3774837575454, 'normal', 0.0305330310134122, 'normal', 1.0148284387204405, 0.9701516139461654, 0.9545808810912612], ['male', 'Cobl', 'c283', datetime.date(2023, 3, 27), 27.8, 'normal', None, 393.3097082935801, 'normal', 0.0002305829906613, 'normal', 1.0379585214393037, 1.018113048318533, 0.998001122433122], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.09, 'abnormal', 'T1 not fused, cranial sutures open mild', 660.1220569318253, 'normal', 0.0110871988009684, 'normal', 0.9903641844718272, 0.9673549424376188, 0.9286248723507088], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c283', datetime.date(2023, 3, 27), 26.27, 'normal', None, 424.345598803349, 'normal', 0.0004419507321009, 'normal', 1.0052961842461134, 0.9719129497875514, 0.957629013357243], ['female', 'C57Bl/6NCrl', 'c283', datetime.date(2023, 3, 27), 27.41, 'abnormal', 'T1 not fused, cranial sutures open', 396.85411808296107, 'normal', 0.0004995964797663, 'normal', 1.0193042765910756, 0.9965811815796553, 0.9739759082492412], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.78, 'normal', 'T1 not fused, pectus excavatum, move', 666.4329730108667, 'normal', 0.0586641558741016, 'normal', 1.0304884786141435, 0.9885355469041568, 0.9827049217727044], ['female', 'C57Bl/6NCrl', 'c283', datetime.date(2023, 3, 27), 26.93, 'normal', None, 345.233222136783, 'normal', 0.0, 'normal', 1.012255872238868, 0.9990133484666064, 0.9900361207922423], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c283', datetime.date(2023, 3, 27), 26.39, 'normal', 'pectus excavatum mild', 519.6311735242026, 'normal', 0.0016525114330732, 'normal', 0.9862694487501444, 0.9756386412246416, 0.9466173559440204], ['female', 'Cobl', 'c283', datetime.date(2023, 3, 27), 25.37, 'normal', None, 671.0213223878112, 'normal', 0.0340494216209984, 'normal', 1.0231788473710273, 0.9478013205864296, 0.9263224939804138], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c283', datetime.date(2023, 3, 27), 26.15, 'normal', 'pectus excavatum mild', 880.3549262911334, 'normal', 0.053245455593559, 'normal', 0.9745001785916012, 0.96257724206017, 0.9243374139243092], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c283', datetime.date(2023, 3, 27), 26.21, 'normal', 'T1 not fused', 673.9966923082599, 'normal', 0.0202336574305368, 'normal', 1.0160066600909028, 0.989620967288858, 0.9655108174707971], ['female', 'C57Bl/6NCrl', 'c283', datetime.date(2023, 3, 27), 27.77, 'normal', 'T1 not fused', 505.8393357035339, 'normal', 0.0035356058568079, 'normal', 1.0328210045145405, 1.018576505127434, 1.0006435654752024], ['female', 'Cobl', 'c283', datetime.date(2023, 3, 27), 27.26, 'abnormal', 'cranial sutures open, pectus excavatum', 388.3447089206593, 'normal', 0.0, 'normal', 1.0082224875092929, 1.0000523712365006, 0.9574058212334126], ['female', 'Cobl', 'c283', datetime.date(2023, 3, 27), 26.2, 'normal', None, 540.3887282962141, 'normal', 0.0, 'normal', 0.9927970776192792, 0.9734117128720938, 0.9544971575760142], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 26.82, 'normal', 'T1 not fused', 479.6497893457124, 'normal', 0.0072633642058337, 'normal', 1.0320986004035666, 1.0169484497759802, 0.9657420221782576], ['male', 'C57Bl/6NCrl', 'c283', datetime.date(2023, 3, 27), 26.06, 'normal', 'T1 not fused', 580.2502841355964, 'normal', 0.0145267284116675, 'normal', 0.9999541035434036, 0.9836071618115948, 0.9615115114757012], ['male', 'Cobl', 'c283', datetime.date(2023, 3, 27), 26.69, 'normal', None, 548.7567588988176, 'normal', 0.0004035202336574, 'normal', 0.9957956835765752, 0.9823612538383976, 0.9763952218014867], ['male', 'Cobl', 'c283', datetime.date(2023, 3, 27), 27.68, 'normal', 'T1 not fused', 320.1665067351388, 'normal', 0.000172937242996, 'normal', 1.0215542518790068, 1.0124112521414272, 0.9795770892834385], ['male', 'Trpv4 tm1b', 'c283', datetime.date(2023, 3, 27), 28.28, 'normal', None, 632.8324722874686, 'normal', 0.0125283424926021, 'normal', 0.995148226014358, 0.982785437893946, 0.9612549378750106], ['male', 'Cobl', 'c283', datetime.date(2023, 3, 27), 26.54, 'normal', None, 566.8323672765541, 'normal', 0.0020560316667307, 'normal', 1.00191432099557, 0.967297534842772, 0.9548484264330878]]
[['female', 'Trex1', 'c296', datetime.date(2023, 7, 10), 25.59, 'normal', 'scoliotic severe, kyphosis', 1014.5591719281832, 'abnormal', 0.0498443564813035, 'normal', 0.9736557114527518, 0.9644264457597128, 0.930931533865933], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.21, 'abnormal', 'kyphosis, cranial sutures open', 419.4218462310511, 'normal', 0.9431612928019676, 'abnormal', 1.3752249711033435, 1.0464751533915473, 0.9133729694318236], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 27.6, 'normal', 'T1 not fused, scoliotic', 427.0647947237208, 'normal', 0.0107413243149763, 'normal', 1.034779922351437, 1.0177253942505549, 0.9969286430811776], ['female', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 27.15, 'abnormal', 'scoliotic, pectus excavatum, cranial sutures open', 285.5914320641665, 'normal', 0.0, 'normal', 1.0160589816496295, 1.0035473517270723, 0.9966891951004412], ['female', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.12, 'abnormal', 'T1 not fused, lordosis, cranial sutures open + microftalmia', 551.1123442276873, 'normal', 0.0146420199069981, 'normal', 1.0054362171201223, 0.9850360150408508, 0.9586768397724484], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 25.97, 'abnormal', 'lordosis, cranial sutures open', 677.2471294698912, 'normal', 0.9050382383459512, 'abnormal', 1.1045659214924248, 0.968897282334788, 0.9014683140571448], ['male', 'Trex1', 'c296', datetime.date(2023, 7, 10), 26.02, 'abnormal', 'T1 not fused, kyphosis, pectus excavatum mild, cranial sutures open severe', 1262.4929805637116, 'abnormal', 0.212290073402252, 'abnormal', 0.959114909927676, 0.9422633586036008, 0.897065722778345], ['female', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.16, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 771.6431134383697, 'normal', 0.008473924906806, 'normal', 1.006277687063643, 0.9849051682208668, 0.9551737644733332], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 27.16, 'normal', 'pectus excavatum', 429.009012706109, 'normal', 0.0004419507321009, 'normal', 1.015015216552557, 0.9967041198341404, 0.96483559713097], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 27.03, 'normal', 'T1 not fused, pectus excavatum', 403.2362480806791, 'normal', 0.000172937242996, 'normal', 1.016802862410238, 1.0000880072669165, 0.9724442792177844], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 25.8, 'normal', None, 580.015362758461, 'normal', 0.0040736328350178, 'normal', 0.9997811408404258, 0.9803452224095768, 0.9338419874155924], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.63, 'normal', None, 460.8666930454933, 'normal', 0.0145843741593328, 'normal', 1.0239444787397267, 0.979270737119052, 0.9602120900353576], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.54, 'normal', 'T1 not fused, lordosis', 291.41580012717264, 'normal', 0.0, 'normal', 1.0164821049138255, 0.9956696629668615, 0.9664298983988128], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.62, 'normal', 'T1 not fused', 380.12482095666735, 'normal', 0.0011721302025287, 'normal', 1.0159682545032374, 0.9727154021178958, 0.9547708393520156], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.84, 'abnormal', 'T1 not fused, cranial sutures open', 492.0450944983641, 'normal', 0.0039967718381307, 'normal', 1.0009740552716953, 0.9866802062752924, 0.9692433109708908], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.66, 'abnormal', 'cranial sutures open', 479.4790560505959, 'normal', 0.0044195073210099, 'normal', 1.0188292869170237, 0.98577552054937, 0.9791324350037548], ['male', 'Trex1', 'c296', datetime.date(2023, 7, 10), 25.56, 'normal', 'T1 not fused, scoliotic mild, kyphosis', 876.4032003099521, 'normal', 0.1109296337573498, 'abnormal', 0.9799840367017768, 0.9541454467470746, 0.9240164932810372], ['female', 'Trex1', 'c296', datetime.date(2023, 7, 10), 24.3, 'normal', 'scoliotic, kyphosis severe', 1366.4250818005237, 'abnormal', 0.0818761769340148, 'normal', 0.966783535504374, 0.9259955191004264, 0.9099000489480864], ['female', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 27.35, 'abnormal', 'T1 not fused, cranial sutures open', 420.1315976895358, 'normal', 1.9215249221782407e-05, 'normal', 1.011269736502301, 1.0024682816947648, 0.9730823844634024], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.24, 'normal', 'T1 not fused, pectus excavatum', 441.29200301149234, 'normal', 0.0027477806387148, 'normal', 1.031877022955658, 0.9798484898327128, 0.96805237540941], ['female', 'Trex1', 'c296', datetime.date(2023, 7, 10), 26.45, 'normal', 'T1 not fused, scoliotic, kyphosis', 1209.7886954216217, 'abnormal', 0.0695976326812958, 'normal', 0.9832886047075522, 0.9438499139699924, 0.917536688775676], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 27.06, 'normal', None, 326.7020347031642, 'normal', 0.0, 'normal', 0.9991338513650556, 0.9776672484855587, 0.9761389710641069], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 27.77, 'normal', 'T1 not fused, pectus excavatum', 667.467102702601, 'normal', 0.0282656316052419, 'normal', 1.022395798247278, 1.0027321308187316, 0.9807023229271116], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.92, 'normal', 'T1 not fused, scoliotic mild, pectus excavatum', 585.2211243537728, 'normal', 0.0057837900157565, 'normal', 1.011330279924512, 0.9955582430265022, 0.9518581279823328], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 25.71, 'normal', None, 540.1797848156256, 'normal', 0.0014219284424118, 'normal', 1.006653168585824, 0.967302412480399, 0.9494180815741032], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.54, 'abnormal', 'T1 not fused, cranial sutures open', 556.5282992477177, 'normal', 7.686099688712963e-05, 'normal', 0.9977330246215383, 0.9865885886743524, 0.9747690819881548], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.19, 'normal', 'T1 not fused', 473.88468797695225, 'normal', 0.0125283424926021, 'normal', 1.0275782190896925, 0.978816048288168, 0.9533741224342456], ['female', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.83, 'normal', 'T1 not fused', 380.9021419753193, 'normal', 0.0, 'normal', 1.01370908063369, 0.9989032007480496, 0.9767971023137136], ['female', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 25.69, 'abnormal', 'possible ossification near left thumb, cranial sutures open', 516.5768931380718, 'normal', 0.0097421313554436, 'normal', 1.0088141007536109, 0.980007474245599, 0.9577386562769268], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.62, 'normal', 'T1 not fused, pectus excavatum', 462.23859500209073, 'normal', 0.0026709196418277, 'normal', 1.0021004471716195, 0.9777968007455938, 0.9641195570969828], ['male', 'C57Bl/6NCrl', 'c296', datetime.date(2023, 7, 10), 26.73, 'normal', 'T1 not fused, L6 = S0, pectus excavatum', 357.3111653551797, 'normal', 0.0, 'normal', 1.0257044506416666, 0.9794000094725724, 0.9639721678844728], ['male', 'Tsc1', 'c296', datetime.date(2023, 7, 10), 26.98, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 495.4711059532648, 'normal', 0.0995926367164982, 'normal', 1.0252015562676309, 0.994390557402967, 0.9547658516120467]]

[['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 27.07, 'normal', 'T1 not fused', 519.9521658911416, 'normal', 0.0015372199377425, 'normal', 1.0171056138873873, 0.991987839855084, 0.9815933941789344], ['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.35, 'normal', 'move', 442.5793135993443, 'normal', 0.0119326697667268, 'normal', 0.9851638407368056, 0.9716857474032518, 0.9522663438776754], ['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.52, 'normal', 'shorter tail - CA23+', 381.4483741680912, 'normal', 0.0, 'normal', 1.0043099788644594, 0.9730064932885992, 0.9472185984097165], ['female', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.74, 'abnormal', 'pectus excavatum, cranial sutures open', 589.2098304783275, 'normal', 0.0153337688789823, 'normal', 1.002899625957421, 0.9859224709220435, 0.9582906518555588], ['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.55, 'abnormal', 'T1 not fused, cranial sutures open', 2244.967345591715, 'abnormal', 0.2036047807540063, 'abnormal', 1.0312753014168627, 0.9857264075227892, 0.96219747813184], ['female', 'Ppp3cb', 'c280', datetime.date(2023, 3, 6), 25.62, 'normal', 'scoliotic, sternum crooked', 587.5010570773579, 'normal', 0.0009415472118673, 'normal', 0.9826430235905192, 0.9676541141716064, 0.9385141312110884], ['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.78, 'normal', None, 513.470445425971, 'normal', 0.0, 'normal', 1.012458838259891, 1.0021294812534192, 0.9732660315264808], ['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.57, 'normal', None, 454.0225338649496, 'normal', 0.0017678029284039, 'normal', 1.0166029884050602, 0.9896405926034854, 0.9763114722100524], ['female', 'Ppp3cb', 'c280', datetime.date(2023, 3, 6), 26.36, 'normal', 'T1 not fused, pectus excavatum mild', 592.7578156774482, 'normal', 0.0320318204527112, 'normal', 1.0423083712698655, 0.976070071928216, 0.9608549419795211], ['male', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.43, 'normal', 'scoliotic, T1 not fused', 784.6490860264747, 'normal', 0.0045347988163406, 'normal', 1.0197445537285628, 0.983762679050528, 0.9413131025484108], ['female', 'Ppp3cb', 'c280', datetime.date(2023, 3, 6), 26.73, 'normal', 'T1 not fused, left C7 rib rudiment', 868.733156446323, 'normal', 0.036643480265939, 'normal', 1.0192532482327556, 0.981746129775136, 0.9258764656643388], ['female', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.09, 'normal', 'T1 not fused, tendon osification, pectus excavatum mild', 387.6482280414427, 'normal', 0.0002882287383267, 'normal', 1.014041114105942, 0.9867194987906664, 0.9607525191790424], ['female', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.96, 'abnormal', 'cranial sutures open', 386.3994577713729, 'normal', 0.0, 'normal', 1.013194923062663, 0.990631357259868, 0.9543133965706824], ['male', 'Hcls1', 'c280', datetime.date(2023, 3, 6), 25.89, 'normal', 'T1 not fused, pectus excavatum', 458.6185778414936, 'normal', 0.0018062334268475, 'normal', 1.0092204963351168, 0.9770987541252631, 0.9750862308857712], ['female', 'Ppp3cb', 'c280', datetime.date(2023, 3, 6), 26.91, 'normal', None, 666.9856499165428, 'normal', 0.0017293724299604, 'normal', 0.9887082363035736, 0.9772976370033758, 0.9324133517554708], ['male', 'Ppp3cb', 'c280', datetime.date(2023, 3, 6), 26.1, 'normal', 'T1 not fused, kyphosis, pectus excavatum mild', 403.7454082767949, 'normal', 0.007148072710503, 'normal', 0.9818768742371096, 0.9644669327711904, 0.9498331367072844], ['male', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 25.72, 'normal', 'kyphosis + pectus excavatum', 635.6028371322561, 'normal', 0.0111064140501902, 'normal', 0.9672286310994964, 0.9534758521857684, 0.9132533360197266], ['female', 'Ppp3cb', 'c280', datetime.date(2023, 3, 6), 25.79, 'normal', 'PS missing, L6 = S0', 5888.9464535908655, 'abnormal', 0.6056262249721379, 'abnormal', 1.0141411839123748, 0.9704754646996198, 0.93691859067354], ['male', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.13, 'normal', 'kyphosis, pectus excavatum mild', 624.9190018796453, 'normal', 0.004938319049998, 'normal', 0.9916794404635196, 0.9810616223741744, 0.9483211940642944], ['female', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.37, 'normal', None, 458.4462698946005, 'normal', 0.0004419507321009, 'normal', 0.9947861712628212, 0.9838875388610826, 0.957463124281315], ['male', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 26.23, 'normal', 'T1 not fused, LHP II. Osteoneogenesis', 554.0175305911494, 'normal', 0.0102801583336535, 'normal', 1.0221498975063323, 1.0108814967047024, 0.9764607208710768], ['male', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 27.06, 'normal', None, 374.44990779468645, 'normal', 0.0, 'normal', 1.0432491803489603, 1.0337075148574923, 1.0052501788213972], ['male', 'C57Bl/6NCrl', 'c280', datetime.date(2023, 3, 6), 27.06, 'normal', 'T1 not fused, pectus excavatum', 457.65759252527545, 'normal', 0.0004035202336574, 'normal', 1.0150722729955868, 0.9978585142559412, 0.9890244599223416], ['female', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.03, 'normal', None, 420.3194688819825, 'normal', 0.0, 'normal', 0.988913611754354, 0.9792968891802888, 0.9538292032878284], ['female', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 26.96, 'normal', None, 457.01321415955766, 'normal', 0.000614887975097, 'normal', 1.0024136601842626, 0.9870480646332476, 0.9589180783652236], ['male', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 27.69, 'normal', 'T1 not fused', 394.2083489502709, 'normal', 0.0008454709657584, 'normal', 1.0035429646729248, 0.9861321390503578, 0.959823089016272], ['female', 'Hcls1', 'c280', datetime.date(2023, 3, 6), 27.97, 'normal', 'T1 not fused', 475.8486522723235, 'normal', 0.0038238345951346, 'normal', 1.0310576923282997, 0.9809812808769272, 0.9680839059814867], ['female', 'Gak', 'c280', datetime.date(2023, 3, 6), 27.05, 'normal', 'scoliotic', 415.9864217511567, 'normal', 0.0, 'normal', 1.0030418133670604, 0.9848963582974132, 0.9593955027009224], ['female', 'Gnl2', 'c280', datetime.date(2023, 3, 6), 27.18, 'abnormal', 'cranial sutures open', 446.9386694460102, 'normal', 0.0, 'normal', 1.0169093947358396, 0.9913064308953004, 0.9676418861341451], ['female', 'Gak', 'c280', datetime.date(2023, 3, 6), 27.17, 'normal', 'T1 not fused, kyphosis + scoliotic', 432.95372870847086, 'normal', 0.0071288574612812, 'normal', 1.0287186417467933, 1.006654486761983, 0.9893164474930154]]
[]
[['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.65, 'normal', 'scoliotic, kyphosis + lordosis,', 605.6188958652002, 'normal', 0.0041312785826832, 'normal', 1.0468523862135422, 1.0036392084632393, 0.9643915536421702], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 25.86, 'normal', None, 560.870549463568, 'normal', 0.007417086199608, 'normal', 1.0067575129095403, 0.994998120544902, 0.9728141768688084], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.56, 'abnormal', 'cranial sutures open', 338.5530326318392, 'normal', 0.0, 'normal', 1.0336453848214546, 1.009290273136616, 0.9758213844317364], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 24.73, 'abnormal', 'T1 not fused, scoliotic mild, kyphosis, rostrum malformation, cranial sutures open mild', 3262.472331937733, 'abnormal', 0.3079627992775066, 'abnormal', 1.0314842053519868, 0.9639970776354436, 0.9557896431154972], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.79, 'normal', 'T1 not fused', 790.9959515112192, 'normal', 0.0393912609046539, 'normal', 1.0303150464126825, 0.9948942186763496, 0.985256249049518], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 27.57, 'normal', 'L6 = half S0', 504.7225224988174, 'normal', 9.607624610891204e-05, 'normal', 1.0274182313207925, 1.0021488317728329, 0.983242266277602], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 25.96, 'normal', None, 731.1603794422068, 'normal', 0.04096691134084, 'normal', 1.0043221229613757, 0.9852778983897036, 0.9482233459593729], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.04, 'normal', 'kyphosis', 574.4376162242062, 'normal', 0.0204642404211982, 'normal', 1.0010576256256791, 0.977894059169943, 0.9691643463672776], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.18, 'normal', 'T1 not fused, scoliotic, kyphosis', 537.5675736509174, 'normal', 0.01218246800661, 'normal', 1.0007065454886583, 0.989408278617566, 0.96757569195861], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.68, 'normal', 'kyphosis', 318.3977413064075, 'normal', 0.0, 'normal', 1.0151218329441096, 1.0056852610761595, 0.9867116736286388], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 26.11, 'abnormal', 'T1 not fused, Processus spinosus missing, RHp II. Osteoneogenesis, cranial sutures open mild', 378.1279833068728, 'normal', 0.0001152914953306, 'normal', 0.98576825311717, 0.9755938007495252, 0.952713757444562], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.65, 'normal', None, 480.4468128038319, 'normal', 0.00830098766381, 'normal', 1.0170270151301892, 0.992655779323236, 0.9693561991347238], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 25.28, 'abnormal', 'scoliotic, kyphosis, rostrum malformation', 2158.0341913062844, 'abnormal', 0.2214557472810422, 'abnormal', 1.036840985697674, 0.9697588831803914, 0.9624831097485856], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 24.62, 'abnormal', 'T1 not fused, Processus spinosus missing, kyphosis severe, rostrum malformed + shorter, cranial sutures open mild', 3083.845071149149, 'abnormal', 0.3622266630798201, 'abnormal', 1.0404993040224364, 1.0006371221269956, 0.8932117135781326], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.46, 'normal', None, 442.5275518076784, 'normal', 0.0037854040966911, 'normal', 1.048289887157874, 1.0117931779597396, 0.9747971368544268], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 27.14, 'normal', 'pectus excavatum', 519.4118602663184, 'normal', 0.0, 'normal', 1.013073647330471, 0.9774564316419792, 0.9629451131835262], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.24, 'normal', 'T1 not fused, pectus excavatum', 658.3572835668946, 'normal', 0.0162561008416279, 'normal', 1.0210509795789355, 1.0023295180309733, 0.9832491257566208], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.67, 'normal', None, 521.9412822644034, 'normal', 0.0049575342992198, 'normal', 1.0185297518405556, 0.9995903481402022, 0.9947883612316416], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 26.39, 'normal', None, 428.16498451976776, 'normal', 0.0007686099688712, 'normal', 1.0530504532112606, 0.9961930104572552, 0.9769713145350738], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.74, 'abnormal', 'T1 not fused, kyphosis + lordosis, cranial sutures open mild', 399.8893213754215, 'normal', 0.004496368317897, 'normal', 1.0218704300928798, 0.9924806703316384, 0.9392338565754856], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 27.35, 'normal', 'pectus excavatum', 502.94296564424735, 'normal', 0.0010184082087544, 'normal', 1.0244484875255906, 0.9905455823767034, 0.9473687368851962], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 27.01, 'abnormal', 'T1 not fused, cranial sutures open', 427.0931054175619, 'normal', 0.0004611659813227, 'normal', 1.0383910438998971, 0.9911705444813864, 0.9722179494995488], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 27.24, 'normal', 'pectus excavatum', 346.51993832435653, 'normal', 0.0035163906075861, 'normal', 1.0024048831105612, 0.98164256876983, 0.9529941590232378], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.54, 'normal', 'kyphosis + lordosis,', 664.0981833679547, 'normal', 0.0032858076169247, 'normal', 1.0064393794028352, 0.9870712729720722, 0.971324580697437], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.26, 'abnormal', 'microphtalmia L', 722.5758246274812, 'normal', 0.068521578724876, 'normal', 0.9837199733972756, 0.9671802173491264, 0.96145559447731], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.63, 'normal', 'T1 not fused', 643.8899045053885, 'normal', 0.0058414357634218, 'normal', 1.0635167573725877, 1.0023149364500568, 0.975631369996221], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.98, 'abnormal', 'T1 not fused, cranial sutures open', 400.9266771229527, 'normal', 0.011298566542408, 'normal', 1.0458849632605034, 0.9901497729904848, 0.971931685181749], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 27.06, 'normal', 'T1 not fused', 298.6699909479493, 'normal', 0.0, 'normal', 1.0327694243073684, 1.0086818954758945, 0.9796345567834206], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 26.52, 'normal', 'kyphosis + lordosis, cranial sutures open mild (not scored),', 422.96011431650936, 'normal', 0.0025940586449406, 'normal', 1.0090399630463325, 0.9828496687795244, 0.9661081473679404], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.17, 'normal', 'scoliotic', 458.4109895347094, 'normal', 0.0020176011682871, 'normal', 0.9953772219938044, 0.9720656437241132, 0.9297471829743916], ['female', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.25, 'normal', None, 697.8331854215079, 'normal', 0.0198493524461012, 'normal', 1.066841356018812, 0.9930745547193754, 0.9704853270903728], ['male', 'Galnt3 RQ', 'c312', datetime.date(2023, 10, 30), 26.24, 'normal', 'T1 not fused', 579.7617622518153, 'normal', 0.0232504515583567, 'normal', 0.9903397352206964, 0.9779563107503808, 0.9549917388541096], ['female', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.1, 'abnormal', 'kyphosis, pectus excavatum, cranial sutures open', 374.91604131835055, 'normal', 0.0, 'normal', 1.0310083336225535, 1.0050536080382146, 0.9787553954063402], ['female', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 24.65, 'abnormal', 'T1-T2 transposed, rostrum malformation', 2850.098913840331, 'abnormal', 0.2868452403827677, 'abnormal', 1.015855687214454, 1.0111832432087449, 0.8798938113288832], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 27.5, 'normal', 'T1 not fused', 484.2854280696734, 'normal', 0.0006341032243188, 'normal', 1.038285386552556, 1.002835123612446, 0.9760442696061212], ['male', 'Galnt3 KO', 'c312', datetime.date(2023, 10, 30), 26.12, 'normal', 'T1 not fused, pectus excavatum mild,  kyphosis mild', 1110.7427210706585, 'abnormal', 0.1037239152991814, 'abnormal', 1.033059899156883, 0.9848760350585016, 0.952582185712642], ['male', 'C57Bl/6NCrl', 'c312', datetime.date(2023, 10, 30), 26.8, 'normal', 'T1 not fused, pectus excavatum', 312.64749973675544, 'normal', 0.0002113677414396, 'normal', 1.0090141335235907, 0.9906634962541706, 0.9768933187591132]]

[['female', 'C57Bl/6NCrl', 'c262', datetime.date(2022, 11, 1), 26.78, 'normal', 'T1 not fused', 2013.70462506606, 'abnormal', 0.0137965489412397, 'normal', 1.0371992603081417, 0.9897735455913124, 0.9466534098789964], ['male', 'C57Bl/6NCrl', 'c262', datetime.date(2022, 10, 31), 26.63, 'normal', None, 310.48420888109933, 'normal', 0.001498789439299, 'normal', 1.0054175695251102, 0.9857510026614276, 0.9704137128314309], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x March6', 'c262', datetime.date(2022, 10, 31), 24.65, 'abnormal', 'scoliotic, shorter rostrum + cranial sutures open', 2005.6813792523465, 'abnormal', 0.2051227854425271, 'abnormal', 0.9964143633581128, 0.92185516130618, 0.8983986460737989], ['female', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 23.82, 'abnormal', 'T1 not fused, malocclusion + cranial sutures open', 4974.207753125177, 'abnormal', 0.457880173705853, 'abnormal', 0.9799118347035513, 0.937266948228998, 0.8159399417321374], ['male', 'Krt34', 'c262', datetime.date(2022, 10, 31), 27.65, 'normal', None, 552.8194080992644, 'normal', 0.002113677414396, 'normal', 1.0155414616879883, 0.9754250635584004, 0.955597407478779], ['male', 'C57Bl/6NCrl', 'c262', datetime.date(2022, 10, 31), 27.13, 'normal', 'L6=half S0', 398.39013753219353, 'normal', 0.0, 'normal', 1.0380527929493648, 1.0088220139709203, 0.9932825546606572], ['female', 'Amelx', 'c262', datetime.date(2022, 11, 1), 26.17, 'normal', 'changes of enamel in incisors and molars', 10541.049825921917, 'abnormal', 0.1647707620767841, 'abnormal', 1.016697542086567, 0.9802049719784324, 0.8979537422518089], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 26.51, 'abnormal', 'T1 not fused, cranial sutures open', 580.1358324504446, 'normal', 0.0018638791745128, 'normal', 1.0124574646303233, 0.9744065421770214, 0.9656802470629196], ['male', 'C57Bl/6NCrl', 'c262', datetime.date(2022, 10, 31), 26.54, 'normal', None, 339.28381677012294, 'normal', 3.8430498443564814e-05, 'normal', 1.001085039614288, 0.9825010422260424, 0.965211756387332], ['female', 'Impact', 'c262', datetime.date(2022, 10, 31), 26.75, 'normal', None, 414.7953832330648, 'normal', 0.0, 'normal', 1.0290460349074415, 0.9947419010483992, 0.9761245497973304], ['male', 'Tkfc', 'c262', datetime.date(2022, 10, 31), 26.52, 'normal', 'T1 not fused', 469.6357033836263, 'normal', 0.0001537219937742, 'normal', 1.021065455847903, 0.9926408512482114, 0.969749878169626], ['male', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 26.27, 'normal', 'T1 not fused, pectus excavatum', 928.2792553208528, 'normal', 0.0877176126974366, 'normal', 1.0165074221890007, 0.9714816463194416, 0.9331831047125076], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 26.38, 'normal', 'scoliosis + kyphosis', 578.6954895944975, 'normal', 0.0058030052649782, 'normal', 1.0059298627726785, 0.968814987294056, 0.940973107076844], ['female', 'Amelx', 'c262', datetime.date(2022, 11, 1), 26.14, 'normal', 'upper incisors larger, changes of enamel in incisors and molars', 1727.7174540619792, 'abnormal', 0.0393336151569885, 'normal', 1.008321778624171, 0.9828045274260696, 0.9364828988960532], ['female', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 25.66, 'normal', 'T1 not fused', 1243.7803161684342, 'abnormal', 0.0655624303447215, 'normal', 0.9743906799329172, 0.952006159712664, 0.9096349928434568], ['female', 'Tkfc', 'c262', datetime.date(2022, 10, 31), 26.63, 'normal', 'T1 not fused, left C7 rib', 581.978428305003, 'normal', 0.0107028938165328, 'normal', 0.9870625678951348, 0.9826651722336768, 0.9355106523259168], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 25.98, 'normal', 'T1-T2 transposed + PS doubled, costal cartilages doubled, LH I. osteoneogenesis', 672.5249156993135, 'normal', 0.09519234464471, 'normal', 1.0253623171506634, 0.9793105706802916, 0.959479723213519], ['female', 'Amelx', 'c262', datetime.date(2022, 11, 1), 25.42, 'abnormal', 'high abrasion of lower molars, changes in enamel in incisors and molars, larger upper incisors, cranial sutures open', 192721.41231850223, 'abnormal', 0.9999615695015563, 'abnormal', 1.1147183291005809, 0.6302416602615045, 0.4478379652977675], ['male', 'Impact', 'c262', datetime.date(2022, 10, 31), 26.64, 'normal', None, 449.280204876768, 'normal', 0.0004611659813227, 'normal', 1.0367582771614876, 1.0110435747234965, 0.9810405532169364], ['female', 'Krt34', 'c262', datetime.date(2022, 10, 31), 27.06, 'abnormal', 'T1 not fused, cranial sutures open', 732.53554640688, 'normal', 0.0086276469005803, 'normal', 1.0242937461449058, 0.9974788300569886, 0.9494493663651132], ['female', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 25.75, 'normal', 'T1 not fused', 862.4962930123639, 'normal', 0.0142000691748971, 'normal', 0.9968415315812028, 0.9588535900439676, 0.9390653387041158], ['female', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 24.49, 'abnormal', 'T1 not fused, left C7 rib, rostrum malformed + cranial sutures open severe', 2781.605623914269, 'abnormal', 0.2534491372353099, 'abnormal', 0.950569510671128, 0.9217429865514194, 0.8778536786459662], ['female', 'Tkfc', 'c262', datetime.date(2022, 10, 31), 25.61, 'abnormal', 'T1 not fused, microphtalmia, rostrum malformation, cranial sutures open', 2937.985716161616, 'abnormal', 0.9728296376003996, 'abnormal', 1.4079429888991166, 1.1464607951972627, 0.8136269246161436], ['male', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 26.04, 'normal', 'scoliotic mild', 639.0795664068746, 'normal', 0.0121440375081664, 'normal', 0.9879038150467708, 0.9512238660995158, 0.9240463018857884], ['female', 'C57Bl/6NCrl', 'c262', datetime.date(2022, 11, 1), 26.15, 'normal', None, 11502.417231825886, 'abnormal', 0.1961108335575112, 'abnormal', 1.0358676569519218, 0.9839431842488596, 0.8960923526361367], ['male', 'Tkfc', 'c262', datetime.date(2022, 10, 31), 26.44, 'normal', None, 523.5088672150067, 'normal', 0.0017293724299604, 'normal', 1.0230448023552314, 0.967102587832593, 0.9606388787449576], ['male', 'Impact', 'c262', datetime.date(2022, 10, 31), 26.26, 'normal', None, 636.1030947823625, 'normal', 0.0047461665577802, 'normal', 1.0033773399159556, 0.9895538698723478, 0.9614673611509532], ['female', 'Impact', 'c262', datetime.date(2022, 10, 31), 25.87, 'normal', None, 600.1356053668775, 'normal', 0.0082241266669228, 'normal', 1.002020869970357, 0.950779008240496, 0.9371098604980784], ['male', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 26.38, 'abnormal', 'T1 not fused, cranial sutures open mild', 686.2898561856898, 'normal', 0.0277660351254755, 'normal', 1.000513466546256, 0.974193516181872, 0.9347484799240492], ['female', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 25.98, 'normal', 'T1 not fused, pectus excavatum', 752.6003300084684, 'normal', 0.0128165712309288, 'normal', 1.0049018281091708, 0.9832556688308506, 0.9493344508938146], ['female', 'Impact', 'c262', datetime.date(2022, 10, 31), 26.77, 'normal', 'T1 not fused', 671.3645864985402, 'normal', 0.0031320856231505, 'normal', 1.0001242112802955, 0.9973397429395076, 0.961546316235965], ['male', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 25.06, 'abnormal', 'T1 not fused, pectus excavatum, kyphosis, microphtalmia, rostrum malformation', 2966.287886162408, 'abnormal', 0.413012566772991, 'abnormal', 0.9844980278667086, 0.9527458826213592, 0.9076656278396984], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 26.5, 'normal', 'T1 not fused', 411.37489343964336, 'normal', 0.0074747319472733, 'normal', 0.995114091354691, 0.9727917178918546, 0.9490891755583188], ['female', 'Tkfc', 'c262', datetime.date(2022, 10, 31), 26.39, 'abnormal', 'cranial sutures open', 1095.4491803440665, 'abnormal', 0.0299757887859805, 'normal', 1.0319895094294784, 0.9914301504745466, 0.9404390534038976], ['male', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 25.97, 'normal', 'T1 not fused', 781.2802289835852, 'normal', 0.0241727835210022, 'normal', 0.9788810998700348, 0.9603068804657808, 0.9297322822950028], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 26.3, 'normal', 'scoliotic, RH II. Osteoneogenesis', 546.9638924895551, 'normal', 0.0, 'normal', 0.9989289699048892, 0.9849534710841628, 0.946885527159069], ['female', 'C57Bl/6NCrl', 'c262', datetime.date(2022, 11, 1), 25.3, 'normal', None, 10439.51840811778, 'abnormal', 0.2736443641674032, 'abnormal', 1.015557543395406, 0.999536629625877, 0.8579997025616498], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Chfr', 'c262', datetime.date(2022, 10, 31), 26.73, 'normal', None, 514.769546754121, 'normal', 0.0067445524768456, 'normal', 0.9862500851616736, 0.98044546102315, 0.9709808534637534], ['male', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 26.47, 'normal', 'T1 not fused', 837.6844951288926, 'normal', 0.0325890626801429, 'normal', 0.9928460796400496, 0.9791105291270394, 0.9240288739905388], ['female', 'Ccdc110', 'c262', datetime.date(2022, 10, 31), 26.11, 'abnormal', 'T1 not fused, LH II. Osteoneogenesis, cranial sutures open', 918.524823319522, 'normal', 0.9833788094231584, 'abnormal', 1.0842588244362132, 1.0728370631438529, 0.9142855032058352], ['female', 'Amelx', 'c262', datetime.date(2022, 11, 1), 26.26, 'normal', 'left lower incisor missing, changes of enamel in upper incisors', 9889.067792877471, 'abnormal', 0.116117751047231, 'abnormal', 0.9995655686070268, 0.9918008491601722, 0.8872002514196742], ['female', 'Mpp1', 'c262', datetime.date(2022, 11, 3), 25.06, 'normal', 'mouse rescanned on 3.11.22 due to movement on the first scan, left C7 rib + right C7 process abnormal, pectus excavatum, LH I.-polysyndactyly', 636.1020284069092, 'normal', 0.0079551131778179, 'normal', 0.9892180408394354, 0.9697365165140536, 0.9107528467172564], ['male', 'Tkfc', 'c262', datetime.date(2022, 10, 31), 26.45, 'normal', 'T1 not fused, left C7 rib, pectus excavatum, 26+27 caudal vertebrae fused', 585.701161452301, 'normal', 0.0044195073210099, 'normal', 1.0009247808222062, 0.9776741674091544, 0.9641382435913848], ['female', 'Krt34', 'c262', datetime.date(2022, 10, 31), 27.13, 'normal', 'T1 not fused', 542.967171412291, 'normal', 0.0023250451558356, 'normal', 1.028053838156441, 1.0066698914491174, 0.9908496461858368], ['male', 'Mpp1', 'c262', datetime.date(2022, 10, 31), 25.97, 'normal', None, 404.8733198353647, 'normal', 0.0050151800468852, 'normal', 0.9832981692796368, 0.977450688987636, 0.950579137448405], ['female', 'Amelx', 'c262', datetime.date(2022, 11, 1), 26.45, 'normal', 'high abrasion of lower molars, changes in enamel in incisors and lower molars', 20622.915810979724, 'abnormal', 0.9937742592521424, 'abnormal', 1.2117142845949194, 1.0179911075372026, 0.7660086930673645]]
[['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 25.78, 'abnormal', 'T1-T2 transposed, cranial sutures open', 598.8310022254595, 'normal', 0.011913454517505, 'normal', 0.9903185092362852, 0.9640723908778832, 0.9397590768933212], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.27, 'normal', 'L6 = half S0', 540.3234722045996, 'normal', 0.0490565312632104, 'normal', 1.011895350853245, 0.971673852215376, 0.9130116534566752], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 27.1, 'normal', 'T1 not fused', 374.4202429338658, 'normal', 0.0, 'normal', 1.0174163835802728, 0.984795471351978, 0.9769952357382328], ['female', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 27.19, 'abnormal', 'pectus excavatum, cranial sutures open', 364.9258046205821, 'normal', 1.9215249221782407e-05, 'normal', 1.015438336554382, 0.9785943971416928, 0.9548659833147118], ['female', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 25.73, 'abnormal', 'sternum crooked, cranial sutures open', 929.7505701774062, 'normal', 0.013681257445909, 'normal', 1.0451390445216766, 0.9995005785335108, 0.9554913780995964], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.51, 'normal', 'Processus spinosus missing, scoliotic', 384.87978476809633, 'normal', 0.000345874485992, 'normal', 1.010987398083927, 0.988103675777393, 0.9627523958313848], ['male', 'Zim1', 'c295', datetime.date(2023, 7, 3), 26.57, 'normal', 'kyphosis, pectus excavatum', 556.8206792106614, 'normal', 0.0105299565735367, 'normal', 0.9958132170754108, 0.9816083210934644, 0.9555448652091852], ['female', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 27.07, 'abnormal', 'kyphosis, cranial sutures open', 340.2770891913087, 'normal', 3.8430498443564814e-05, 'normal', 1.033224482173939, 1.0026263388847296, 0.9826101110905504], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.65, 'normal', 'kyphosis', 295.6940065370736, 'normal', 7.686099688712963e-05, 'normal', 1.0215085676367064, 0.9936839571124902, 0.967839987155108], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.39, 'abnormal', 'cranial sutures open mild', 302.7656544856169, 'normal', 5.764574766534722e-05, 'normal', 0.9964302232170962, 0.9888867690829573, 0.9679589868209268], ['male', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 26.48, 'normal', None, 396.09663156282704, 'normal', 0.0003074439875485, 'normal', 0.9995031754060566, 0.9891730966596504, 0.9718888980221516], ['female', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 26.3, 'normal', None, 360.7050524856787, 'normal', 0.0002305829906613, 'normal', 1.009913961846468, 0.9876132098725798, 0.9563374374075518], ['female', 'Zim1', 'c295', datetime.date(2023, 7, 3), 26.35, 'abnormal', 'T1 not fused, cranial sutures open', nan, nan, nan, nan, nan, nan, nan], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.54, 'abnormal', 'T1 not fused, C7 process abnormal, ossification near pelvis, cranial sutures open', 304.7697874957701, 'normal', 0.0, 'normal', 0.99669745001667, 0.9739742155610568, 0.9639339338425664], ['male', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 26.46, 'normal', 'T1 not fused', 929.0039955590096, 'normal', 0.0416010145651589, 'normal', 1.067052950398237, 0.981792254875539, 0.9542554218542744], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.79, 'normal', 'T1 not fused, pectus excavatum', 393.3919684431441, 'normal', 0.0009223319626455, 'normal', 1.014480249046626, 0.9919257459119664, 0.9859329752486398], ['male', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 25.99, 'normal', 'T1 not fused', 370.320261289996, 'normal', 0.0, 'normal', 1.0117424283378802, 0.9947666522408598, 0.9731356342375592], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.84, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 267.8723226592821, 'normal', 0.0, 'normal', 1.0318638298039071, 1.0108641835740162, 0.983148356536618], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.23, 'abnormal', 'cranial sutures open', 320.43208296447443, 'normal', 0.0, 'normal', 0.9959489431691112, 0.9806406063457428, 0.9494798820141842], ['female', 'Casp8', 'c295', datetime.date(2023, 7, 3), 27.05, 'normal', 'T1 not fused, 25th +26th caudal vertebrae fused together, kyphosis', 355.7288724443234, 'normal', 0.0010952692056415, 'normal', 1.015463162036326, 0.9857062117750294, 0.9754912257154044], ['female', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 27.06, 'abnormal', 'T1 not fused, Processus spinosus missing, left C7 rib rudiment, kyphosis, cranial sutures open', 536.4832920068874, 'normal', 0.002382690903501, 'normal', 1.0320149720671434, 1.0124966223225018, 0.9919276934128004], ['male', 'Ccdc18 KO', 'c295', datetime.date(2023, 7, 3), 26.86, 'normal', 'T1 not fused, kyphosis', 492.2262206277485, 'normal', 0.0384497136927865, 'normal', 1.0205241741038544, 0.9980840467464484, 0.9663176284943178], ['male', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 26.68, 'normal', 'pectus excavatum', 391.6771571303771, 'normal', 0.0, 'normal', 1.007144258299178, 0.9774456628053596, 0.9702216309888508], ['female', 'Ccdc18 KO', 'c295', datetime.date(2023, 7, 3), 26.49, 'abnormal', 'cranial sutures open', 564.1004431822913, 'normal', 0.0298989277890934, 'normal', 1.0057346771270763, 0.9907637307279564, 0.9532981880349652], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.07, 'normal', 'scoliotic', 466.7038687237244, 'normal', 0.0008454709657584, 'normal', 1.012481332666333, 0.9899914356258572, 0.9716535834428508], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.53, 'normal', 'T1 not fused, kyphosis', 475.9304100877786, 'normal', 5.764574766534722e-05, 'normal', 0.9986693264875206, 0.9863085233235702, 0.95076617161526], ['female', 'Zim1', 'c295', datetime.date(2023, 7, 3), 26.75, 'abnormal', 'cranial sutures open', 348.25381016640563, 'normal', 0.0004419507321009, 'normal', 1.0042343227450925, 0.9874788194588272, 0.9620906907175372], ['female', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 26.68, 'normal', 'pectus excavatum mild', 1212.6291686052175, 'abnormal', 0.0484032127896698, 'normal', 1.0109415152217405, 0.9963717470214332, 0.9299915046606136], ['female', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 26.92, 'normal', None, 366.0712367350024, 'normal', 0.0, 'normal', 0.998679040094048, 0.9847116593483516, 0.9711844474916338], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.78, 'abnormal', 'cranial sutures open', 368.6980833933336, 'normal', 0.0, 'normal', 0.984551182204544, 0.9769924358010836, 0.9393873011108104], ['male', 'C57Bl/6NCrl', 'c295', datetime.date(2023, 7, 3), 26.55, 'normal', 'kyphosis', 517.1870568566654, 'normal', 0.0152376926328734, 'normal', 0.9915373583338924, 0.983884634062862, 0.9512653653451958], ['female', 'Casp8', 'c295', datetime.date(2023, 7, 3), 26.31, 'abnormal', 'cranial sutures open mild', 434.385693450028, 'normal', 0.0105491718227585, 'normal', 1.0349545886636005, 0.9812893827977218, 0.9749267691755008], ['male', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 26.68, 'normal', 'pectus excavatum', 583.6746429316955, 'normal', 0.0217900926175012, 'normal', 1.0053459742228916, 0.9728764127112048, 0.9465046235993544], ['female', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 26.83, 'normal', 'T1 not fused', 218.46169981024184, 'normal', 0.0, 'normal', 1.0164949285050708, 0.9995643239520748, 0.9886453585789344], ['female', 'Casp8', 'c295', datetime.date(2023, 7, 3), 26.9, 'normal', 'T1 not fused', 584.2586646759852, 'normal', 0.0, 'normal', 1.02540139379494, 0.9967904017241352, 0.9922821677701028], ['female', 'Mroh8', 'c295', datetime.date(2023, 7, 3), 26.11, 'normal', 'T1 not fused, scoliotic, left C7 rib rudiment, L6 = half S0', 1136.201525510978, 'abnormal', 0.0408516198455094, 'normal', 1.0004439001359342, 0.9736369822016564, 0.9473156172117668], ['male', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.18, 'normal', 'pectus excavatum', 582.5520979587442, 'normal', 0.0205795319165289, 'normal', 1.0257531584257318, 0.9866857139597826, 0.9722059544281216], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.45, 'normal', 'T1 not fused', 466.3871403766974, 'normal', 0.0, 'normal', 1.007519405672637, 0.995700610883444, 0.9794222978348378], ['female', 'Cyth4', 'c295', datetime.date(2023, 7, 3), 26.29, 'normal', 'T1 not fused', 464.3567929155461, 'normal', 0.0, 'normal', 1.002031034098843, 0.9818081177266378, 0.9650504205658612], ['female', 'Zim1', 'c295', datetime.date(2023, 7, 3), 25.52, 'normal', 'RHP II. Osteoneogenesis', 442.4129978607694, 'normal', 0.0069559202182852, 'normal', 1.0135081776712342, 0.9893226808314122, 0.9393914451240868]]

[['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 27.14, 'normal', 'kyphosis high; T1 not fused', 447.839389444772, 'normal', 0.006975135467507, 'normal', 1.0325054557308355, 1.0111059276967305, 0.9767336475501164], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 27.97, 'normal', None, 691.5241182525396, 'normal', 0.0079358979285961, 'normal', 1.0222754957290796, 1.000938302806637, 0.9736185152841268], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.66, 'normal', 'scoliotic; T1 not fused', 555.6195940349768, 'normal', 0.0, 'normal', 1.0064045307046523, 1.002010503374481, 0.9712361106897404], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.67, 'normal', None, 667.3493149358719, 'normal', 0.0338380538795588, 'normal', 1.015222478252591, 0.9936386972927096, 0.9471705025553104], ['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.53, 'normal', 'tendon ossification (femoris)', 460.2405966586283, 'normal', 0.002113677414396, 'normal', 1.0308950605380802, 0.9983708446347108, 0.9833917093056784], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.68, 'normal', 'T1 not fused', 623.9352205815828, 'normal', 0.0043426463241228, 'normal', 1.0006830820119443, 0.9791540630655708, 0.952255710775416], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.97, 'normal', 'scoliotic', 394.0237779517788, 'normal', 0.0005188117289881, 'normal', 1.0126141222292864, 1.0046556021584987, 0.9852067528774294], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c254', datetime.date(2022, 9, 5), 26.6, 'normal', 'agouti; tail cut; C7 ribs - T1 rib fusion; T1 not fuse; T2 pr. Spinosus reduction; T12; L1 half T13 - rib; CA18+; lordosis high; scoliotic', 1415.0150044815969, 'abnormal', 0.0322624034433726, 'normal', 1.0221908393217731, 0.9795353108815812, 0.9612819179055851], ['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.96, 'normal', 'rounded back; T1 not fused', 538.8356438385872, 'normal', 0.0078013911840436, 'normal', 1.0075765159411565, 0.9844402088156184, 0.9714287428562776], ['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.48, 'normal', 'T1 not fused', 545.2150945769647, 'normal', 0.0047845970562238, 'normal', 1.005951203221514, 0.995389098904544, 0.9557769765684568], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.65, 'normal', 'L6 half sacral; kyphosis high; T1 not fused', 424.8205242090884, 'normal', 0.0014603589408554, 'normal', 1.0151079713741618, 0.990305212838526, 0.977239492951296], ['female', 'PGC', 'c254', datetime.date(2022, 9, 5), 26.38, 'normal', 'T1 not fused', 406.6740779628848, 'normal', 0.0014603589408554, 'normal', 1.0045166072130671, 0.9896384781344127, 0.9695776749541944], ['female', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.81, 'normal', 'move; Hindpaw: R I. doubled', 550.5528054399955, 'normal', 0.0001345067445524, 'normal', 1.0221171958926896, 1.0023513107795572, 0.989358629538802], ['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.7, 'normal', 'CA23+', 539.9523820066737, 'normal', 0.0070519964643941, 'normal', 1.0237668282000874, 1.0071077337889232, 0.9741884131641236], ['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 27.53, 'normal', 'tail move', 716.7907677358806, 'normal', 0.0039199108412436, 'normal', 1.0192090924964994, 1.0077087533689728, 0.9699022508649476], ['male', 'PGC', 'c254', datetime.date(2022, 9, 5), 27.27, 'normal', 'C4 not fused; C4+5', 603.0244487633246, 'normal', 0.0166211905768417, 'normal', 1.0244596952991902, 1.0096321778742503, 0.966954236454554], ['female', 'Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Dcaf15', 'c254', datetime.date(2022, 9, 5), 26.47, 'normal', 'agouti; forelimb & tail move; L5; T1 not fused', 629.4381235511187, 'normal', 0.0292456093155528, 'normal', 1.0153938976406185, 0.987970587259736, 0.9771044308393676], ['male', 'C57Bl/6NCrl', 'c254', datetime.date(2022, 9, 5), 26.49, 'normal', 'T1 not fused', 365.4211574950367, 'normal', 0.0, 'normal', 1.0176379372763904, 0.9943464012443596, 0.9709312518862075]]
[['male', 'Gak', 'c270', datetime.date(2022, 12, 27), 27.2, 'normal', 'scoliotic mild, T1 not fused, C7 right rib, move', 343.6645226273086, 'normal', 0.0003650897352138, 'normal', 1.044686489175386, 1.007790267463148, 0.9975576701277904], ['female', 'Dach2', 'c270', datetime.date(2022, 12, 27), 25.79, 'abnormal', 'scoliotic, LH II. Osteoneogenesis, cranial sutures open', 1033.1482940742917, 'abnormal', 0.048922024518658, 'normal', 1.006304282187719, 0.952884761151042, 0.937362848227463], ['male', 'Gak', 'c270', datetime.date(2022, 12, 27), 27.36, 'normal', 'scoliotic, move', 515.4165370283405, 'normal', 0.0130471542215902, 'normal', 1.031256772684682, 1.0235133839117343, 0.9836699500149356], ['male', 'Dach2', 'c270', datetime.date(2022, 12, 27), 28.19, 'normal', 'T1 not fused, pectus excavatum', 413.1967924697236, 'normal', 0.0001921524922178, 'normal', 1.032961529565333, 1.0056234631685257, 0.9961082813899488], ['female', 'Dach2', 'c270', datetime.date(2022, 12, 27), 26.71, 'normal', 'T1 not fused', 525.1870946930457, 'normal', 0.0150839706390991, 'normal', 1.0103366658460713, 0.971528905112542, 0.9403810929647026], ['male', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 27.61, 'normal', None, 511.98554324123154, 'normal', 0.0031897313708158, 'normal', 1.0334012628884106, 1.0117631088276389, 1.0003841104602296], ['female', 'Klhl6', 'c270', datetime.date(2022, 12, 27), 26.79, 'normal', 'scoliotic, kyphosis', 698.0721795204162, 'normal', 0.0044002920717881, 'normal', 1.0107242318830878, 0.9862443327608988, 0.9566595357707064], ['male', 'Xrcc5', 'c270', datetime.date(2022, 12, 27), 22.2, 'abnormal', 'scoliotic, tail tip deformed, kyphosis severe, zygomatic arch deformed, cranial sutures open', 1960.367445240011, 'abnormal', 0.9294992506052804, 'abnormal', 1.1535763849525482, 0.930835405653284, 0.815204976923895], ['female', 'Mpp1', 'c270', datetime.date(2022, 12, 27), 26.01, 'normal', 'T1 not fused, 4th + 5th cervical vertebrae fused', 922.7011923732778, 'normal', 0.0111640597978555, 'normal', 0.9813036554871484, 0.9698227746673922, 0.9236435837329264], ['female', 'Ccdc18 KO', 'c270', datetime.date(2022, 12, 27), 26.75, 'normal', None, 769.3419072162245, 'normal', 0.0342800046116598, 'normal', 1.0224403761078311, 1.0009690557899882, 0.9620541511570372], ['male', 'Dach2', 'c270', datetime.date(2022, 12, 27), 27.49, 'normal', None, 408.8628698425087, 'normal', 3.8430498443564814e-05, 'normal', 1.0215530801484602, 1.0137095321521583, 0.9834538873884162], ['male', 'Dach2', 'c270', datetime.date(2022, 12, 27), 27.54, 'normal', None, 494.1479325200486, 'normal', 0.0341262826178855, 'normal', 1.0310426737412997, 0.999662878937942, 0.9857995850610456], ['female', 'Xrcc5', 'c270', datetime.date(2022, 12, 27), 21.55, 'abnormal', 'tail tip deformed, kyphosis severe, cranial sutures open severe', 1992.4606439486292, 'abnormal', 0.6170208677606549, 'abnormal', 0.9069211732852326, 0.8318088121522714, 0.7850290373441106], ['male', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 25.7, 'normal', 'kyphosis', 540.3604935585702, 'normal', 0.0028054263863802, 'normal', 1.0221768897412271, 0.9816051347160764, 0.962057446316253], ['male', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 27.07, 'normal', None, 462.8276568906167, 'normal', 0.0, 'normal', 1.026604244960292, 0.9985820101425846, 0.9923881779009458], ['female', 'Dach2', 'c270', datetime.date(2022, 12, 27), 26.68, 'normal', 'T1 not fused', 880.7972177622502, 'normal', 0.0101072210906575, 'normal', 1.0180866141160252, 0.996612655778364, 0.950022266087033], ['female', 'Mpp1', 'c270', datetime.date(2022, 12, 27), 25.2, 'abnormal', 'cranial sutures open', 695.0061960510327, 'normal', 0.0164866838322893, 'normal', 0.984162211835174, 0.9608573626053905, 0.9223368421034523], ['female', 'Dach2', 'c270', datetime.date(2022, 12, 27), 26.64, 'normal', 'T1 not fused', 412.1569774475792, 'normal', 0.0005764574766534, 'normal', 1.0035639333372302, 0.9982755409246958, 0.968426703910169], ['female', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 24.74, 'abnormal', 'T1 not fused, rostrum malformation, left upper incisor missing', 2949.5685575872835, 'abnormal', 0.2242803889166442, 'abnormal', 1.0077997830865486, 0.9577678416030164, 0.9320181619239724], ['male', 'Mpp1', 'c270', datetime.date(2022, 12, 27), 25.47, 'normal', None, 996.2046660690564, 'abnormal', 0.1263210483839975, 'abnormal', 0.9658779037233703, 0.9480126704050302, 0.8893902626267987], ['female', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 26.8, 'normal', 'scoliotic', 881.0536262851108, 'normal', 0.0429076515122401, 'normal', 1.0202057965397977, 0.997383069266146, 0.9787722879299824], ['female', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 26.1, 'abnormal', 'RH II. Osteoneogenesis, cranial sutures open', 475.01012525159376, 'normal', 0.0, 'normal', 1.007575498692995, 0.9672918863125436, 0.9550148640518236], ['female', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 27.22, 'normal', 'cranial sutures opne mild', 527.6865268297298, 'normal', 0.0012105607009722, 'normal', 1.0300777325732118, 1.0021174230369811, 0.954029120546948], ['male', 'Gak', 'c270', datetime.date(2022, 12, 27), 26.97, 'normal', 'move', 553.9382162653732, 'normal', 0.0137581184427962, 'normal', 1.0157666164699704, 1.0023908974046525, 0.9931631522046982], ['male', 'C57Bl/6NCrl', 'c270', datetime.date(2022, 12, 27), 26.48, 'normal', 'L6=S0', 703.7457384711423, 'normal', 0.0290150263248914, 'normal', 1.0030878451810863, 0.9819221688458978, 0.9716680195931612], ['male', 'Klhl6', 'c270', datetime.date(2022, 12, 27), 26.16, 'normal', 'pectus excavatum', 856.0363830851479, 'normal', 0.0443103647054302, 'normal', 1.0098837034392485, 0.9855149887905488, 0.9614215303938928], ['female', 'Dach2', 'c270', datetime.date(2022, 12, 27), 26.97, 'normal', None, 508.27186803869154, 'normal', 0.0002497982398831, 'normal', 1.001866948746675, 0.9977255161064306, 0.9320021733388052], ['female', 'Klhl6', 'c270', datetime.date(2022, 12, 27), 26.32, 'normal', 'scoliotic', 514.6865057784311, 'normal', 0.0087237231466892, 'normal', 1.008519911184756, 0.97514630765792, 0.9429859466446568], ['male', 'Dach2', 'c270', datetime.date(2022, 12, 27), 25.92, 'normal', None, 699.5324445398516, 'normal', 0.1386956688828254, 'abnormal', 1.03562435423804, 0.9753314086896326, 0.9630594170878866], ['female', 'Dach2', 'c270', datetime.date(2022, 12, 27), 26.66, 'normal', 'T1 not fused', 542.324743516261, 'normal', 0.0107221090657545, 'normal', 1.0034488223622264, 0.9685548777879986, 0.9612971339810324], ['male', 'Xrcc5', 'c270', datetime.date(2022, 12, 27), 21.81, 'normal', 'scoliotic, kyphosis severe, zygomatic arch deformed', 3293.1597554876284, 'abnormal', 0.6199415856423658, 'abnormal', 0.883542936195002, 0.8689612244827251, 0.8043774162924976], ['female', 'Ccdc18 KO', 'c270', datetime.date(2022, 12, 27), 26.61, 'normal', 'T1 not fused', 647.0287685106495, 'normal', 0.0370277852503747, 'normal', 1.0354245528709356, 1.0072625945726632, 0.9763993644897276]]

[['female', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.45, 'abnormal', 'cranial sutures open', 336.46949395422104, 'normal', 0.0, 'normal', 1.0173605550069549, 0.987360636799626, 0.9645726835603172], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.77, 'normal', None, 293.2144466578542, 'normal', 0.000172937242996, 'normal', 1.0028718678840347, 0.9948059081382832, 0.979861655247162], ['male', 'Pcid2', 'c308', datetime.date(2023, 10, 2), 26.55, 'normal', 'T1-T2 transposed, PS doubled, L6 = S0', 390.0232181291128, 'normal', 0.0019983859190653, 'normal', 1.0290357801305814, 1.014888799410836, 0.9838050288274758], ['male', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.66, 'normal', 'kyphosis', 378.7948888966956, 'normal', 0.0026901348910495, 'normal', 1.000350453420639, 0.986642445651862, 0.9650793042341854], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.48, 'abnormal', 'T1 not fused, cranial sutures open', 604.6745046377529, 'normal', 0.0014219284424118, 'normal', 1.004260879273249, 0.9910907320673944, 0.9549239846731902], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.92, 'normal', None, 443.41117888864886, 'normal', 9.607624610891204e-05, 'normal', 1.0191048780696117, 0.998359842359015, 0.9801115174724816], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 27.04, 'abnormal', 'cranial sutures open', 410.0379220288889, 'normal', 0.0008070404673148, 'normal', 1.02251294356454, 1.0066344664398152, 0.9820759301112866], ['male', 'Pcid2', 'c308', datetime.date(2023, 10, 2), 27.46, 'normal', 'T1 not fused', 436.87172927331903, 'normal', 0.0085892164021367, 'normal', 1.0075190435520789, 0.9804353340120832, 0.9642369055230524], ['male', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.19, 'normal', None, 467.4408461453016, 'normal', 0.0008454709657584, 'normal', 1.0061930338353426, 0.9806756483230114, 0.9559082053561708], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 27.07, 'normal', 'T1 not fused', 439.2868465633426, 'normal', 9.607624610891204e-05, 'normal', 1.0205487354208662, 0.9959899738606875, 0.974675995555702], ['female', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.66, 'normal', 'T1 not fused', 437.5299506729342, 'normal', 1.9215249221782407e-05, 'normal', 1.011493666362211, 0.9855180620156664, 0.9655722122397022], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 27.24, 'abnormal', 'T1 not fused, cranial sutures open', 371.4143131179069, 'normal', 0.0004227354828792, 'normal', 1.0159923618573514, 0.9941178751593692, 0.9627379642244748], ['female', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 27.27, 'normal', 'scoliotic', 439.9116205277851, 'normal', 7.686099688712963e-05, 'normal', 0.9969017295518552, 0.9834533199771318, 0.9552000146763928], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 27.35, 'normal', 'pectus excavatum', 343.2169325138227, 'normal', 0.0, 'normal', 1.0050016318675676, 0.984150935884442, 0.9754750833341967], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.75, 'normal', 'T1 not fused, scoliotic', 403.9586530756041, 'normal', 0.0011144844548633, 'normal', 1.0170059949228645, 1.0096208851455095, 0.9598903128832448], ['female', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.84, 'abnormal', 'cranial sutures open', 570.4186962988657, 'normal', 0.009530763614004, 'normal', 1.003491815761136, 0.9922858714776616, 0.9312216226020066], ['female', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.19, 'normal', 'scoliotic mild', 533.9180744709764, 'normal', 0.0002882287383267, 'normal', 0.9850883704659512, 0.9753339334717788, 0.93225637945245], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.65, 'abnormal', 'scoliotic + kyphosis mild (not scored), T1 not fused, pectus excavatum, cranial sutures open', 370.5668447555188, 'normal', 0.0, 'normal', 1.0268377064853964, 0.99736339538552, 0.9838572510814676], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 27.45, 'abnormal', 'cranial sutures open', 1010.8952751179872, 'abnormal', 0.0632373851888859, 'normal', 1.015501279422375, 1.0033619774296472, 0.9574418768499507], ['male', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 27.07, 'abnormal', 'T1 not fused, cranial sutures open', 1042.6514365235826, 'abnormal', 0.1283386495522847, 'abnormal', 0.9954919405253292, 0.9701007198810458, 0.9388571535349696], ['female', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.66, 'normal', 'T1 not fused', 559.553241270738, 'normal', 0.0068982744706198, 'normal', 1.0069783203622644, 0.9750029975182344, 0.966190903879104], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 27.28, 'abnormal', 'cranial sutures open', 445.1158428432399, 'normal', 0.0002690134891049, 'normal', 1.0095756835388547, 0.983629636091357, 0.9422144220444952], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 25.03, 'abnormal', 'scoliotic mild, pectus excavatum, rostrum malformation', 2653.69812440977, 'abnormal', 0.3339994619730217, 'abnormal', 1.0052633052478304, 0.9885338707870142, 0.949643124963562], ['male', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.98, 'abnormal', 'kyphosis, pectus excavatum mild, cranial sutures open', 600.7050683984828, 'normal', 0.031878098458937, 'normal', 1.0198666660522009, 0.9824122126069084, 0.9668858174554122], ['female', 'C57Bl/6NCrl', 'c308', datetime.date(2023, 10, 2), 26.97, 'normal', 'pectus excavatum, LHp II. Osteoneogenesis', 385.4761744668433, 'normal', 0.0, 'normal', 1.0106067351533743, 0.9968842375629372, 0.9707735616328776], ['male', 'Tspan12', 'c308', datetime.date(2023, 10, 2), 26.37, 'normal', 'T1 not fused, scoliotic severe', 500.3904086863603, 'normal', 0.0035740363552515, 'normal', 1.0018683393654606, 0.9736113534680222, 0.957813656702983]]
[['male', 'Zim1', 'c304', datetime.date(2023, 9, 4), 27.04, 'normal', 'T1 not fused, scoliotic, C7 process abnormal', 412.5782915482313, 'normal', 0.0018446639252911, 'normal', 1.018639766495908, 1.0113322232570114, 0.98709567792369], ['female', 'Dcaf5', 'c304', datetime.date(2023, 9, 4), 25.42, 'abnormal', 'scoliotic, kyphosis, Processus spinosus missing, pectus excavatum mild/sternum malformed, cranial sutures open', 1020.714421710321, 'abnormal', 0.0873140924637792, 'normal', 0.9851284968484608, 0.9430079699303796, 0.8956466085292043], ['male', 'Zim1', 'c304', datetime.date(2023, 9, 4), 27.53, 'normal', 'scoliotic mild, pectus excavatum severe', 479.2772863330403, 'normal', 0.007148072710503, 'normal', 1.0596791268172316, 1.0276832448366464, 0.9915912738400732], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 27.01, 'normal', 'left C7 rib rudiment, L6 = half S0, pectus excavatum', 696.4497047551171, 'normal', 0.0270550709042696, 'normal', 1.043551846604193, 1.0159583062879065, 0.9905500051115824], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 25.38, 'abnormal', 'scoliotic, cranial sutures open', 728.9016154268885, 'normal', 0.0067829829752891, 'normal', 1.001574150243767, 0.9837765094709022, 0.9451385944072552], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 27.01, 'normal', 'L6 = half S0', 410.4941615837727, 'normal', 0.0, 'normal', 1.0267294687790582, 1.012321355883783, 0.9974648143676756], ['female', 'Ccdc18 KO', 'c304', datetime.date(2023, 9, 4), 26.08, 'abnormal', 'C7 process abnormal, mild interscapular ossification, tiny T1 process, rostrum malformation', 4259.275730050866, 'abnormal', 0.4057299873179355, 'abnormal', 1.051333064680681, 1.0052645551485715, 0.9293185278175008], ['female', 'Parp1', 'c304', datetime.date(2023, 9, 4), 26.84, 'normal', 'scoliotic, kyphosis', 664.4584270535757, 'normal', 0.0087429383959109, 'normal', 1.0034067243019682, 0.9711128989345328, 0.954059442884068], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.54, 'normal', None, 508.5484733990408, 'normal', 0.0083586334114753, 'normal', 1.0424892980442495, 1.0248798388608025, 0.9746254360931932], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.47, 'normal', 'sternum crooked', 699.2082057224914, 'normal', 0.0007686099688712, 'normal', 1.004260542416595, 1.0025272650324817, 0.9613793142448012], ['male', 'Trex1', 'c304', datetime.date(2023, 9, 4), 26.21, 'normal', 'T1 not fused, kyphosis, scoliotic mild', 626.3395768289611, 'normal', 0.0223665500941547, 'normal', 1.0082014917868858, 0.9638811906048764, 0.9309255853936608], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.92, 'normal', None, 438.0195075165588, 'normal', 0.0032089466200376, 'normal', 1.0213793440847074, 0.9941957317067808, 0.9837832960164395], ['female', 'Trex1', 'c304', datetime.date(2023, 9, 4), 25.35, 'abnormal', 'scoliotic mild, kyphosis, cranial sutures open', 1358.6815117601975, 'abnormal', 0.0852004150493832, 'normal', 0.985539970483486, 0.9543082894030216, 0.9451825596850372], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 27.02, 'normal', 'L6 = half S0', 412.68285004573227, 'normal', 1.9215249221782407e-05, 'normal', 1.0312414428271508, 1.0233384895799085, 0.982114457342765], ['female', 'Tsc1', 'c304', datetime.date(2023, 9, 4), 27.15, 'abnormal', 'T1 not fused, scoliotic mild, cranial sutures open', 411.2932392900998, 'normal', 0.0053994850313208, 'normal', 1.0196881903837078, 1.0034831150424788, 0.9708865032309268], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.4, 'abnormal', 'kyphosis?, cranial sutures open', 509.2158071559664, 'normal', 0.0102032973367664, 'normal', 1.0183105744242142, 0.9525009182589104, 0.950482436815474], ['female', 'Dcaf5', 'c304', datetime.date(2023, 9, 4), 25.37, 'normal', 'Processus spinosus missing, pectus excavatum mild', 915.5551383610808, 'normal', 0.0626224972137888, 'normal', 0.9633875477753336, 0.9245667592859156, 0.8910478871794579], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 27.46, 'normal', None, 515.1889711616187, 'normal', 0.0035932516044733, 'normal', 1.0179754862186714, 1.007154735232665, 0.9788681785438637], ['female', 'Parp1', 'c304', datetime.date(2023, 9, 4), 25.77, 'normal', 'scoliotic', 772.6409595806537, 'normal', 0.0176203835363744, 'normal', 0.9819682405063612, 0.9588206122704294, 0.9118048436209892], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.63, 'abnormal', 'T1 not fused, tendon ossification high, cranial sutures open', 452.815936367852, 'normal', 0.0, 'normal', 1.0068323029946271, 0.9954458037740724, 0.9493113846615192], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.59, 'normal', 'T1 not fused, scoliotic', 462.41025223840495, 'normal', 0.0002882287383267, 'normal', 1.0055367330192988, 0.9868242216012758, 0.97054614115545], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 27.27, 'normal', None, 466.8136684577135, 'normal', 0.0013450674455247, 'normal', 1.043958926072457, 1.0151699725143517, 0.974652006125915], ['male', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 27.22, 'normal', 'T1-T2 transposed, L6 = S0', nan, nan, nan, nan, nan, nan, nan], ['female', 'C57Bl/6NCrl', 'c304', datetime.date(2023, 9, 4), 26.85, 'abnormal', 'pectus excavatum, cranial sutures open', 429.7098910744068, 'normal', 0.0006917489719841, 'normal', 0.997903448317302, 0.9933482341839636, 0.9551194142786312], ['female', 'Tsc1', 'c304', datetime.date(2023, 9, 4), 27.44, 'abnormal', 'T1 not fused, kyphosis, pectus excavatum, cranial sutures open', 583.6589242979837, 'normal', 0.0057645747665347, 'normal', 1.0200202801894094, 0.9947715340910308, 0.9781350777743436]]

[['male', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 27.25, 'normal', 'T1 not fused', 486.0825126522559, 'normal', 0.0007109642212059, 'normal', 1.020129959931897, 0.9873806886137918, 0.9745315247991628], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.54, 'abnormal', 'cranial sutures open', 544.0397059637797, 'normal', 0.0035548211060297, 'normal', 1.0098533327285395, 0.993362490038441, 0.9389055950893148], ['female', 'Prc1', 'c307', datetime.date(2023, 9, 25), 25.97, 'normal', None, 467.3648240882935, 'normal', 0.0017101571807386, 'normal', 0.9862545093329608, 0.9669190601023576, 0.9470792436770424], ['female', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 26.54, 'abnormal', 'cranial sutures open', 529.7572072834458, 'normal', 0.0005956727258752, 'normal', 1.0075407515967896, 0.9983345259914482, 0.967474630828311], ['female', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 26.78, 'abnormal', 'pectus excavatum, cranial sutures open', 733.0789637045483, 'normal', 0.0381807002036816, 'normal', 1.0379784477684062, 1.006228998030177, 0.9932963816157386], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.71, 'normal', 'T1 not fused, pectus excavatum', 984.5532723391864, 'abnormal', 0.0099534990968832, 'normal', 0.9926980848312272, 0.9807060278833304, 0.942506405346651], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.77, 'normal', None, 423.4513531724298, 'normal', 0.000172937242996, 'normal', 1.0201002683274936, 0.9893800675481652, 0.972054362016909], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.42, 'normal', 'T1 not fused', 664.0802926577337, 'normal', 0.0154874908727566, 'normal', 1.0099262156708964, 0.9822834209029216, 0.952846063443872], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.19, 'normal', 'T1 not fused', 565.6576954785071, 'normal', 0.0007686099688712, 'normal', 1.0022082711909848, 0.9859587809790744, 0.962587951998689], ['male', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 25.56, 'abnormal', 'kyphosis, pectus excavatum, rostrum malformation', 2316.121865328332, 'abnormal', 0.2729718304446408, 'abnormal', 1.0582314043014105, 1.0082141010823993, 0.9704422610516796], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.05, 'normal', 'LHp II. Osteoneogenesis', 503.1921492304809, 'normal', 0.0, 'normal', 1.010364064841167, 0.9732797760474878, 0.96335909011385], ['male', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 26.75, 'normal', 'scoliotic, L6 = half S0', 341.36873216999874, 'normal', 0.0012682064486376, 'normal', 1.0250908257974989, 1.0049927883141696, 0.9692750383549978], ['female', 'Prc1', 'c307', datetime.date(2023, 9, 25), 26.34, 'abnormal', 'scoliotic, Processus spinosus tiny, cranial sutures open', 603.7944032190467, 'normal', 0.0041312785826832, 'normal', 1.056418597659602, 0.9687851746121326, 0.94209728568786], ['female', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 27.24, 'normal', 'T1 not fused', 415.62154746253145, 'normal', 5.764574766534722e-05, 'normal', 1.0283537165625256, 1.0135617805362245, 0.99755612465674], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.47, 'abnormal', 'T1 not fused, cranial sutures open', 509.5830132200326, 'normal', 0.0002497982398831, 'normal', 1.0025881107422046, 0.9795070423358871, 0.9716413070548098], ['female', 'Prc1', 'c307', datetime.date(2023, 9, 25), 26.09, 'normal', None, 545.4223223555144, 'normal', 0.0062449559970792, 'normal', 0.9821616511540974, 0.964959229734906, 0.9377248055350283], ['female', 'Prc1', 'c307', datetime.date(2023, 9, 25), 27.21, 'abnormal', 'T1 not fused, LHp II. Osteoneogenesis, cranial sutures open', 556.8262990090501, 'normal', 0.0017101571807386, 'normal', 1.0242629218520507, 1.003086922433282, 0.9804274308306612], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.9, 'normal', None, 686.2534093481096, 'normal', 0.0108374005610852, 'normal', 1.0690875832530098, 1.03483869454949, 0.9633745734326168], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.89, 'normal', 'T1 not fused', 982.5963883936184, 'abnormal', 0.0235386802966834, 'normal', 1.0062671326402692, 0.9789807951365233, 0.9359551514818484], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.75, 'normal', 'T1 not fused', 701.994329898815, 'normal', 0.0044387225702317, 'normal', 1.0264089514996253, 0.988264937021712, 0.965417186582768], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 27.12, 'normal', 'T1 not fused', 396.18284102688017, 'normal', 0.0003650897352138, 'normal', 1.0163600863425652, 1.007920574767179, 0.9795713046662242], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.12, 'normal', None, 904.934533990686, 'normal', 0.0176011682871526, 'normal', 0.9926898387685362, 0.9789628176694932, 0.945731527193424], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.34, 'normal', None, 375.4733035776013, 'normal', 0.0002690134891049, 'normal', 0.9981580200490752, 0.9837134180542128, 0.978706364750335], ['female', 'Prc1', 'c307', datetime.date(2023, 9, 25), 26.15, 'abnormal', 'scoliotic, LHp II. Osteoneogenesis, cranial sutures open mild', 356.92229666525526, 'normal', 0.0, 'normal', 1.0005399763203962, 0.9808583330683016, 0.9516964775155812], ['female', 'Prc1', 'c307', datetime.date(2023, 9, 25), 26.3, 'abnormal', 'scoliotic very mild (non-scored), RHp II. Osteoneogenesis, cranial sutures open', 467.77653624942167, 'normal', 0.001671726682295, 'normal', 0.973794799754431, 0.9706673328024312, 0.9484311818365158], ['female', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 27.36, 'normal', 'scoliotic, kyphosis, pectus excavatum, RHp II. Osteoneogenesis', 640.6352187522044, 'normal', 0.0035740363552515, 'normal', 1.0839011168635817, 1.013896888194, 0.9883536168659416], ['male', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 25.94, 'normal', None, 765.3731540112822, 'normal', 0.0025364128972752, 'normal', 1.0029569847589668, 0.9616641125017276, 0.9544136204952068], ['female', 'Serpinb9', 'c307', datetime.date(2023, 9, 25), 26.86, 'abnormal', 'cranial sutures open', 500.1289529221768, 'normal', 0.0282079858575765, 'normal', 1.052063384715381, 1.0187912122844145, 0.975843964938004], ['male', 'C57Bl/6NCrl', 'c307', datetime.date(2023, 9, 25), 27.01, 'normal', 'T1 not fused, pectus excavatum, RFp missing phalang in IV. Finger', 384.3506873404294, 'normal', 0.0, 'normal', 1.005536667647779, 0.9986913173995556, 0.9723748926096228]]
[['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 27.58, 'normal', None, 355.3828098046379, 'normal', 0.0057453595173129, 'normal', 1.0244863017800063, 0.9977315974715324, 0.987686494692652], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.84, 'normal', 'left C7 rib rudiment, pectus excavatum', 316.364909703836, 'normal', 0.0011529149533069, 'normal', 1.013353119756038, 0.9983192773283934, 0.9879904912953088], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.41, 'normal', None, 651.0125418644279, 'normal', 0.0001345067445524, 'normal', 1.0042375083055044, 0.9709681203308672, 0.9452013023681114], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 25.95, 'normal', None, 666.5358301333825, 'normal', 0.01606394834941, 'normal', 1.015835399189352, 0.9987841849317608, 0.9603288672535066], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.13, 'normal', 'mouse move, T1 not fused', 560.1058633190903, 'normal', 0.0073978709503862, 'normal', 1.0101969864768965, 0.9965382509596904, 0.9752547450200052], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.2, 'abnormal', 'cranial sutures open', 449.7528997783981, 'normal', 0.0004227354828792, 'normal', 1.0045860378991684, 0.9858542964592356, 0.9638917398928142], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.89, 'normal', 'pectus excavatum mild + sternum protuberance', 546.5415910704658, 'normal', 0.0024019061527228, 'normal', 1.021880695646188, 1.001858915737551, 0.9685396731915378], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.23, 'normal', 'T1 not fused, pectus excavatum', 500.814571188092, 'normal', 0.0011144844548633, 'normal', 0.9970912982038304, 0.9889184568596304, 0.960274722569882], ['female', 'C57Bl/6NCrl', 'c299', datetime.date(2023, 7, 31), 26.67, 'abnormal', 'T1 not fused, cranial sutures open', 528.9112335667978, 'normal', 0.0014603589408554, 'normal', 1.0075670046323126, 1.0019764040911057, 0.9960007950054804], ['male', 'C57Bl/6NCrl', 'c299', datetime.date(2023, 7, 31), 26.92, 'normal', 'pectus excavatum, pelvis ossification/protuberance', 458.966438504886, 'normal', 0.0006725337227623, 'normal', 1.0435565090608097, 1.0013129686479094, 0.9743695421150642], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.69, 'normal', None, nan, nan, nan, nan, nan, nan, nan], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.17, 'normal', 'T1 not fused, scoliotic', 478.29073572693625, 'normal', 0.0200799354367626, 'normal', 1.0300482202394772, 1.014941521839254, 0.9795929460353974], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.37, 'normal', 'scoliotic, L6 = half S0, LHp II. Osteoneogenesis', 528.1875221569751, 'normal', 0.001229775950194, 'normal', 1.0151400356678644, 0.9894789612739542, 0.9573931877534962], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.55, 'normal', None, 469.4255881164336, 'normal', 7.686099688712963e-05, 'normal', 0.9856749958123042, 0.972180666586172, 0.961496195415473], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 25.98, 'normal', 'LHp I. Osteoneogenesis', 582.6503046728432, 'normal', 0.0013834979439683, 'normal', 1.0066597185852633, 0.9841801545490174, 0.9746950683388064], ['female', 'C57Bl/6NCrl', 'c299', datetime.date(2023, 7, 31), 26.19, 'normal', 'scoliotic, T1 not fused', 454.6004237830352, 'normal', 0.0019023096729564, 'normal', 1.0149023849786205, 0.987992962234722, 0.9841260253319284], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.07, 'normal', 'Processus spinosus missing', 388.0591782711186, 'normal', 0.0, 'normal', 0.996574665833692, 0.9732066431984628, 0.958030199109271], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.62, 'normal', None, 405.4813421768925, 'normal', 0.0102993735828753, 'normal', 1.0214792099141303, 0.994373008737415, 0.961994325109938], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 25.65, 'abnormal', 'scoliotic, cranial sutures open', 553.3472708746884, 'normal', 0.0014795741900772, 'normal', 1.0102966251862255, 0.982168126113592, 0.9622584893770584], ['male', 'C57Bl/6NCrl', 'c299', datetime.date(2023, 7, 31), 26.6, 'normal', 'pectus excavatum', 351.1281480991764, 'normal', 0.0007109642212059, 'normal', 1.0242625071130296, 0.984810256288136, 0.9825539719378732], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 25.46, 'normal', None, 1639.0358610925955, 'abnormal', 0.2086776065485569, 'abnormal', 0.9654863790940156, 0.9371008592143366, 0.8973941671532707], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.03, 'abnormal', 'cranial sutures open', nan, nan, nan, nan, nan, nan, nan], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 27.12, 'normal', None, 581.7460498590549, 'normal', 0.0142577149225625, 'normal', 1.0187607037067057, 0.9895127196766808, 0.9738350603003608], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 27.25, 'normal', 'kyphosis', 602.2407157152323, 'normal', 0.0002113677414396, 'normal', 1.0190146219131195, 1.0000704545040129, 0.9890157961537758], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.31, 'normal', 'scoliotic mild, RHp IV. Nail missing', 451.0180763352912, 'normal', 0.0001152914953306, 'normal', 0.998660466368712, 0.9767002824134424, 0.9537688915345384], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 25.14, 'normal', '25 caudal vertebrae', 970.6973392256826, 'normal', 0.027900541870028, 'normal', 0.9898159669827304, 0.9737707383280616, 0.9464305712390564], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 25.93, 'abnormal', 'kyphosis, cranial sutures open', 595.0005297501698, 'normal', 0.0005956727258752, 'normal', 0.9869102856831928, 0.9754641466636396, 0.9426052116154104], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 27.36, 'normal', 'T1 not fused', 602.8528368639032, 'normal', 0.0017101571807386, 'normal', 1.008882590389397, 1.002622337043377, 0.9578293199853324], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.15, 'normal', None, 531.8791592254813, 'normal', 0.0009607624610891, 'normal', 1.0130648378234484, 0.9915061477302076, 0.9767817584498714], ['male', 'C57Bl/6NCrl', 'c299', datetime.date(2023, 7, 31), 27.16, 'normal', 'T1 not fused', 456.475546064657, 'normal', 0.001229775950194, 'normal', 1.029989554994354, 0.9973841625183508, 0.9767303586150272], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.13, 'normal', None, 385.9417359478761, 'normal', 0.0035932516044733, 'normal', 1.0214726896610502, 1.0002796837680343, 0.9928063018397704], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.96, 'normal', 'pectus excavatum', 882.2805558293071, 'normal', 0.0422159025402559, 'normal', 1.038751148252944, 1.0118719851350382, 0.9892755829884108], ['male', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.77, 'normal', 'kyphosis', 323.2287472374384, 'normal', 0.0024403366511663, 'normal', 1.0430381824749428, 1.000730796816547, 0.9920363095607836], ['male', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.51, 'normal', 'T1 not fused', 483.8742557662632, 'normal', 9.607624610891204e-05, 'normal', 1.0132607286291246, 0.9917677817126412, 0.977417316793173], ['female', 'Mpl', 'c299', datetime.date(2023, 7, 31), 26.18, 'normal', None, 579.2278215454393, 'normal', 0.0044579378194535, 'normal', 1.0247108627990444, 1.0069997887861866, 0.9648046472268162], ['female', 'C57Bl/6NCrl', 'c299', datetime.date(2023, 7, 31), 26.04, 'abnormal', 'T1 not fused, RHP I. Broken finger, cranial sutures open', 603.339882003728, 'normal', 0.0190423119787863, 'normal', 0.9968005584953494, 0.9849560128278338, 0.9351479572885364], ['female', 'Dpp9', 'c299', datetime.date(2023, 7, 31), 26.4, 'normal', 'T1 not fused', 469.328717993614, 'normal', 0.0006341032243188, 'normal', 1.0022890767146244, 0.9830716055518678, 0.9762068742964484]]

[['female', 'Gpatch4', 'c289', datetime.date(2023, 5, 22), 25.99, 'normal', '5 sacral vertebrae, kyphosis, lordosis, mild tendon ossification', 738.0175628831105, 'normal', 0.032761999923139, 'normal', 0.985776169961384, 0.9655080598537648, 0.9427675210293462], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 25.83, 'normal', '5 sacral vertebrae, pectus excavatum mild', 495.9336518343781, 'normal', 0.0087621536451327, 'normal', 1.0213107208652945, 0.9984253703857272, 0.9712148304636544], ['female', 'Gpatch4', 'c289', datetime.date(2023, 5, 22), 25.14, 'normal', '5 sacral vertebrae', 1176.4974973540673, 'abnormal', 0.0285730755927904, 'normal', 0.9674052459948896, 0.9549645670787844, 0.895854298393847], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.15, 'normal', 'pectus excavatum', 569.0667691833535, 'normal', 0.0044195073210099, 'normal', 1.0101615355894489, 0.9724397781281756, 0.9595786673493412], ['female', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.12, 'abnormal', 'cranial sutures open', 695.2227671982713, 'normal', 0.0247876714960993, 'normal', 1.006398218218901, 0.984635160848169, 0.9724162432668948], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.78, 'abnormal', '5 sacral vertebrae, pectus excavatum severe, cranial sutures open severe', 990.9852129127072, 'abnormal', 0.1213250835863341, 'abnormal', 1.0157270667916587, 0.9835986026727456, 0.963489225491835], ['male', 'Gpatch4', 'c289', datetime.date(2023, 5, 22), 26.16, 'normal', 'kyphosis', 920.3625231635036, 'normal', 0.0877944736943238, 'normal', 1.0093567436207604, 0.968767034339652, 0.9459928987515588], ['male', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 26.69, 'normal', 'T1 not fused, pectus excavatum', 499.9861791971852, 'normal', 0.0105491718227585, 'normal', 1.03333765948678, 0.9793704083019874, 0.9673238369273484], ['female', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 25.96, 'normal', None, 445.3303711829943, 'normal', 0.0018254486760693, 'normal', 0.9990033376034512, 0.974359260767681, 0.951851534651218], ['female', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.18, 'normal', '5 scral vertebrae, tendon ossification', 485.75650524466215, 'normal', 0.0050536105453287, 'normal', 1.0216226320213797, 1.0006396063086875, 0.9843716830236748], ['male', 'Trak1 KO', 'c289', datetime.date(2023, 5, 22), 26.99, 'normal', 'pectus excavatum mild, kyphosis', 394.7300291236244, 'normal', 0.0007686099688712, 'normal', 1.024568449080344, 0.9946528182453636, 0.9619197676609094], ['male', 'Cobl', 'c289', datetime.date(2023, 5, 22), 26.81, 'normal', 'pectus excavatum mild', 327.5930716663401, 'normal', 3.8430498443564814e-05, 'normal', 1.012570386751802, 0.994878103453599, 0.9633064396562826], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.23, 'abnormal', 'kyphosis, tendon ossification, cranial sutures open', 777.216483515262, 'normal', 0.0432919564966757, 'normal', 0.9982140429167864, 0.9754637381524872, 0.9659297360290438], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.52, 'normal', None, 539.553869300344, 'normal', 0.0132585219630298, 'normal', 0.99262099346211, 0.9802532883483068, 0.9641163009321324], ['male', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 26.84, 'normal', None, 463.879245674307, 'normal', 0.0708466238807117, 'normal', 1.0215490443560702, 0.9652549089916236, 0.9635031810088808], ['female', 'Pgf', 'c289', datetime.date(2023, 5, 22), 25.95, 'abnormal', 'T1 not fused, 5 sacral vertebrae, kyphosis, cranial sutures open severe', 889.3840581182429, 'normal', 0.0256715729603012, 'normal', 1.022299888818282, 0.9643414982144414, 0.9487354362543536], ['female', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 25.8, 'normal', None, 512.3444968864021, 'normal', 0.0015564351869643, 'normal', 0.981448235866076, 0.9731103164315908, 0.9291186341672588], ['male', 'Cobl', 'c289', datetime.date(2023, 5, 22), 26.11, 'normal', 'pectus excavatum, kyphosis', 389.0284515827219, 'normal', 0.0, 'normal', 0.997260427089256, 0.9960241022343796, 0.983656787791048], ['female', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 26.34, 'normal', None, 496.4748595542867, 'normal', 0.0412551400791668, 'normal', 1.0380159068206831, 0.9583998586120832, 0.9456710675105738], ['female', 'Pgf', 'c289', datetime.date(2023, 5, 22), 25.93, 'normal', 'T1 not fused, 5 sacral vertebrae', 584.9546794860589, 'normal', 0.0115867952807347, 'normal', 0.99692114438513, 0.957073840764939, 0.9452150752978068], ['female', 'Trpv4 tm1b', 'c289', datetime.date(2023, 5, 22), 26.76, 'abnormal', 'T1 not fused, cranial shape abnormal, frontal + parietal bone soft + open sutures, enamel missing!!', 1905.7505286317732, 'abnormal', 0.1229775950194074, 'abnormal', 0.9974795206961592, 0.9578862402637252, 0.9561843010813558], ['female', 'Pgf', 'c289', datetime.date(2023, 5, 22), 25.93, 'normal', '5 sacral vertebrae', 575.8565906444381, 'normal', 0.0139694861842358, 'normal', 0.9975681907348948, 0.9748058746130708, 0.9168132443822212], ['female', 'Pgf', 'c289', datetime.date(2023, 5, 22), 25.75, 'abnormal', '5 sacral vertebrae, kyphosis mild, cranial sutures open', 596.814496419649, 'normal', 0.0077437454363783, 'normal', 1.0053915276784886, 0.9720117071647332, 0.9525912914345104], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.22, 'normal', 'scoliotic, kyphosis severe, pectus excavatum', 630.6848432423567, 'normal', 0.0064563237385188, 'normal', 1.00563709978098, 0.9927036691495162, 0.9652181396551878], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 26.2, 'normal', 'pectus excavatum, lower enamel', 818.1171331176912, 'normal', 0.0345298028515429, 'normal', 1.0178833468364783, 1.0033153514751565, 0.9691681650742718], ['male', 'Cobl', 'c289', datetime.date(2023, 5, 22), 26.89, 'abnormal', 'cranial sutures open', 485.4371003790897, 'normal', 0.0086084316513585, 'normal', 1.0182507086880976, 0.988649730539602, 0.96946074574271], ['female', 'Trak1 KO', 'c289', datetime.date(2023, 5, 22), 26.43, 'normal', None, 559.7484393256145, 'normal', 0.0024595519003881, 'normal', 1.013057935000221, 0.9966928568522324, 0.982555520144485], ['female', 'Gpatch4', 'c289', datetime.date(2023, 5, 22), 26.2, 'normal', 'T1 not fused, 5 sacral vertebrae, kyphosis, lordosis', 907.2767491087004, 'normal', 0.0945390261711694, 'normal', 1.017344851700242, 0.9939983736899044, 0.9351267961608898], ['female', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 27.29, 'normal', 'scoliotic, kyphosis', 456.290848654909, 'normal', 1.9215249221782407e-05, 'normal', 1.0454551372687215, 1.006794602881481, 0.982040100844264], ['female', 'Gpatch4', 'c289', datetime.date(2023, 5, 22), 23.82, 'abnormal', 'T1 not fused, L6 = S0, kyphosis mild, rostrum malformation, cranial sutures open mild', 3115.273613078397, 'abnormal', 0.3139195265362591, 'abnormal', 1.0054832468371302, 0.9396694738830969, 0.9181825780151612], ['male', 'C57Bl/6NCrl', 'c289', datetime.date(2023, 5, 22), 26.83, 'normal', 'kyphosis', 502.03838665184094, 'normal', 0.0053994850313208, 'normal', 1.0085408793644786, 0.9916619364036428, 0.9727279204245174], ['female', 'Gpatch4', 'c289', datetime.date(2023, 5, 22), 26.12, 'abnormal', 'T1 not fused, cranial sutures open', 489.7446399383568, 'normal', 0.0, 'normal', 1.0084171111564386, 0.9839547052487402, 0.954284897368326], ['male', 'Pgf', 'c289', datetime.date(2023, 5, 22), 25.89, 'normal', None, 529.8521904471427, 'normal', 0.0217516621190576, 'normal', 0.9620265672880876, 0.9403708398912756, 0.9236089118428508], ['female', 'Cobl', 'c289', datetime.date(2023, 5, 22), 26.9, 'normal', None, 607.1779096871212, 'normal', 0.0044387225702317, 'normal', 1.0167242913351469, 1.008021236147114, 0.9551958970307308]]
[['female', 'Ccdc18 KO', 'c303', datetime.date(2023, 8, 28), 26.27, 'abnormal', 'Cranium: sutures open; T1 not fused', 837.2780189505431, 'normal', 0.0402559471196341, 'normal', 1.0476742806157704, 0.9990280981052578, 0.9690489340360358], ['male', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 26.93, 'normal', 'T1 not fused', 614.3938523765739, 'normal', 0.0314169324776142, 'normal', 1.1074702835870167, 1.0150561910474538, 0.9895648441554908], ['female', 'Gcnt1', 'c303', datetime.date(2023, 8, 28), 26.9, 'normal', 'T1 not fused', 614.8872473826075, 'normal', 0.0046500903116713, 'normal', 1.0526104285815736, 1.0061253727155992, 0.9759004256988856], ['male', 'Gcnt1', 'c303', datetime.date(2023, 8, 28), 26.86, 'abnormal', 'Cranium: low splacho-neurocranial angle', 620.1602583799472, 'normal', 0.0097229161062218, 'normal', 1.0227686128055615, 0.989305547250994, 0.95360408095328], ['male', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 27.03, 'normal', 'C7 rib rudiment; T1 rib malformation; T1 not fused', 691.8785060438352, 'normal', 0.0528803658583451, 'normal', 1.0318504715217671, 1.0108063384593178, 0.9994970263198812], ['female', 'Gcnt1', 'c303', datetime.date(2023, 8, 28), 26.83, 'normal', 'Cranium: sutures open; T1 not fused', 618.8990769766375, 'normal', 0.0032281618692594, 'normal', 1.0687634999714204, 0.9886634820315195, 0.9833510633807367], ['male', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 26.63, 'normal', None, 672.1678157832488, 'normal', 0.0080704046731486, 'normal', 1.066136590624694, 0.9937072619693518, 0.97704315443154], ['female', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 26.58, 'abnormal', 'Cranium: sutures open; T1 not fused', 1077.6470747570286, 'abnormal', 0.0788017370585296, 'normal', 1.0652173533560023, 1.0245663684012236, 0.9801890603734338], ['female', 'Ccdc18 KO', 'c303', datetime.date(2023, 8, 28), 26.92, 'normal', 'T1 not fused', 583.6822106667901, 'normal', 0.0211559893931824, 'normal', 1.02159310296859, 1.002195874168476, 0.9616645345457112], ['female', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 26.56, 'abnormal', 'Cranium: sutures open, neucranium rounded', 722.2197910268793, 'normal', 0.024633949502325, 'normal', 1.06212113253567, 0.9920976509132884, 0.9663980494233118], ['male', 'Ccdc18 KO', 'c303', datetime.date(2023, 8, 28), 26.44, 'normal', None, 827.7928389447022, 'normal', 0.0650436186157334, 'normal', 1.0262729510013795, 0.9982277455787144, 0.9818315509755968], ['female', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 26.38, 'abnormal', 'Cranium: sutures open; lordosis low; T1 not fused', 500.0593561910535, 'normal', 0.0, 'normal', 1.0328581407308477, 0.9844135401798808, 0.9780027163422969], ['female', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 26.55, 'normal', 'T1 not fused', 403.7587691309352, 'normal', 0.0031128703739287, 'normal', 0.9877145463060656, 0.98097263048751, 0.9668209633000788], ['male', 'C57Bl/6NCrl', 'c303', datetime.date(2023, 8, 28), 28.03, 'normal', 'lordosis low; C7 rib; C7+T1 rib fusion; T1 not fused', 651.5114457547489, 'normal', 0.0146035894085546, 'normal', 1.0455158534352214, 1.011029076071849, 0.9783991087975245]]
[['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.34, 'normal', None, 495.7977962323879, 'normal', 0.00830098766381, 'normal', 1.0106074800552014, 0.9854865975650368, 0.9446401453606236], ['female', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.16, 'abnormal', 'move, T1 not fused, cranial sutures open', 1025.364833956469, 'abnormal', 0.0691172514507513, 'normal', 0.9961957449160894, 0.9748957075515322, 0.9314240233989808], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.35, 'abnormal', 'LHP II. Osteoneogenesis, cranial sutures open', 543.7288515788723, 'normal', 0.0056108527727604, 'normal', 1.00214507357059, 0.993625023028022, 0.9347358912023666], ['female', 'Cpm', 'c279', datetime.date(2023, 2, 27), 27.06, 'normal', 'C4+C5 fused', 502.3357148901059, 'normal', 0.0019791706698435, 'normal', 1.0209175229001304, 0.9949652247649023, 0.969132197321348], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.8, 'normal', 'move', 463.0148264979019, 'normal', 0.0043618615733446, 'normal', 1.0139521387520485, 0.9964307481664122, 0.9651595864875314], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 27.35, 'abnormal', 'cranial sutures open', 510.71683723216313, 'normal', 0.007859036931709, 'normal', 0.9794175972578308, 0.9779407558983596, 0.934198287634824], ['male', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 25.99, 'normal', None, 401.8540989018891, 'normal', 5.764574766534722e-05, 'normal', 0.994755032471462, 0.9788029258134576, 0.9604501790649144], ['female', 'Casp8', 'c279', datetime.date(2023, 2, 27), 25.83, 'normal', 'move, tail tip malformed', 596.9739827298342, 'normal', 0.0002497982398831, 'normal', 0.9847107170348812, 0.9610498046503326, 0.9400455121817274], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 27.04, 'normal', 'T1 not fused, left C7 rib rudiment, L6 = half S0', 737.3299585803417, 'normal', 0.0349909688328657, 'normal', 1.0004483059446752, 0.9950521119498476, 0.9526532207357992], ['male', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.31, 'normal', 'T1 not fused', 422.1511466896592, 'normal', 0.0006341032243188, 'normal', 1.0122713450323355, 0.9864673906785408, 0.9721555737110976], ['male', 'Cpm', 'c279', datetime.date(2023, 2, 27), 26.06, 'normal', 'T1 not fused', 389.8442888308524, 'normal', 0.0002305829906613, 'normal', 0.9996855255616202, 0.9979906635279436, 0.9734979664737404], ['female', 'C57Bl/6NCrl', 'c279', datetime.date(2023, 2, 27), 26.62, 'normal', 'T1 not fused', 407.8694253861765, 'normal', 0.0, 'normal', 0.998803848063443, 0.9832640711973102, 0.9264389428091504], ['female', 'C57Bl/6NCrl', 'c279', datetime.date(2023, 2, 27), 26.52, 'normal', 'T1 not fused', 553.3531610421852, 'normal', 0.0015372199377425, 'normal', 1.0076514032989308, 1.0039907819352665, 0.9657383813755016], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.71, 'abnormal', 'move, T1 not fused, cranial sutures open', 604.48560908203, 'normal', 0.0019023096729564, 'normal', 1.0067039978325067, 0.9835224389512304, 0.9580038037230504], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.8, 'normal', 'T1 not fused', 385.8328805217332, 'normal', 0.0013066369470812, 'normal', 1.0282456378612377, 0.9911732943787418, 0.9681577066061796], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.93, 'normal', 'T1 not fused', 514.5335693876146, 'normal', 0.0003650897352138, 'normal', 1.0362150422125302, 1.014253607857695, 0.9872254411041193], ['male', 'C57Bl/6NCrl', 'c279', datetime.date(2023, 2, 27), 26.88, 'normal', None, 364.0999655612831, 'normal', 0.0011529149533069, 'normal', 1.034216953326929, 0.9976943523801822, 0.976575574318954], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.68, 'normal', None, 556.9931311557203, 'normal', 0.0021905384112831, 'normal', 1.010408264923832, 0.972915322874405, 0.9629193437063638], ['female', 'Cpm', 'c279', datetime.date(2023, 2, 27), 26.59, 'normal', None, 308.4507842801475, 'normal', 0.0012682064486376, 'normal', 1.0099205233511792, 1.0006230345445728, 0.9680532629991988], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 27.13, 'normal', 'pectus excavatum mild', 358.5570866185303, 'normal', 0.0055916375235386, 'normal', 1.0203218102760414, 1.00176844909451, 0.9738055426442456], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.87, 'normal', 'T1 not fused, tail tip malformed, LHP II. osteoneogenesis', 401.7118480641268, 'normal', 0.0004803812305445, 'normal', 1.0444870084180409, 0.9902638522435948, 0.977208285552978], ['male', 'C57Bl/6NCrl', 'c279', datetime.date(2023, 2, 27), 26.9, 'normal', 'T1 not fused', 1012.4556314232522, 'abnormal', 0.0862188232581376, 'normal', 1.042690609347012, 1.0149713565387526, 0.9762156889728908], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.63, 'normal', None, 580.2855561534014, 'normal', 0.0049959647976634, 'normal', 1.0026451456363998, 0.9832033158557296, 0.9588164430531464], ['male', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.27, 'normal', 'T1 not fused, C4+C5 fused', 452.3359206556236, 'normal', 0.0090503823834595, 'normal', 1.0048553292846358, 1.0011965333495647, 0.96359257269199], ['female', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.82, 'normal', 'move, T1 not fused', 613.4083715316664, 'normal', 0.0015180046885208, 'normal', 0.9933895579697092, 0.9799577985722596, 0.9779517771588212], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 27.59, 'normal', 'T1 not fused, LHP II. Osteoneogenesis', 429.0610442348151, 'normal', 0.0070519964643941, 'normal', 1.0279577110926197, 1.004904557621434, 0.9909724154966094], ['male', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.45, 'normal', 'T1 not fused', 519.7075946411867, 'normal', 0.0012682064486376, 'normal', 0.9886216770491636, 0.9745926072806556, 0.9584184893846932], ['male', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.11, 'normal', 'T1-T2 transposed + T1 not fused', 824.2055984082783, 'normal', 0.054744245032858, 'normal', 1.0160860986630005, 0.9911357070462994, 0.938854436692675], ['female', 'C57Bl/6NCrl', 'c279', datetime.date(2023, 2, 27), 26.86, 'abnormal', 'T1 not fused, LH II. Osteoneogenesis, cranial sutures open mild', 432.1998550140927, 'normal', 0.0, 'normal', 1.0404181387949825, 1.0097477087238664, 0.9891768980006972], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 25.83, 'normal', 'T1 not fused', 389.1426515288466, 'normal', 0.0014795741900772, 'normal', 0.987935938131509, 0.9803633564181908, 0.9554846084504872], ['male', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 26.6, 'normal', 'pectus excavatum', 425.0491023854761, 'normal', 0.0002305829906613, 'normal', 1.0170202912458508, 0.9977992864425606, 0.9701134635850224], ['female', 'Cngb3', 'c279', datetime.date(2023, 2, 27), 25.89, 'normal', None, 422.0389570651722, 'normal', 0.0006725337227623, 'normal', 0.9928681676034798, 0.9762288005535086, 0.9588948805487004], ['female', 'Casp8', 'c279', datetime.date(2023, 2, 27), 26.23, 'normal', None, 575.4564947841011, 'normal', 0.0019791706698435, 'normal', 0.9998798077077048, 0.9791472300202868, 0.9473637471824852]]

[['female', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 25.86, 'normal', 'scoliotic, T1 not fused,', 519.2599906861775, 'normal', 0.0254794204680834, 'normal', 0.9994695652920697, 0.9803239362434504, 0.9376557679224704], ['female', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.36, 'normal', 'pectus excavatum, kyphosis', 361.47086598011816, 'normal', 0.0, 'normal', 0.9932885398657224, 0.9857675972030876, 0.9614100814105984], ['male', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 27.48, 'normal', 'T1-T2 transposed, left + right C7 rib rudiment, L6 = half S0, pectus excavatum mild, kyphosis', 593.3603429245338, 'normal', 0.0072057184581684, 'normal', 1.0317265713053625, 0.997120356081898, 0.9882246500072416], ['male', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 26.93, 'normal', 'Processus spinosus missing, T1 not fused + extra process, left C7 rib rudiment', 774.2061654862852, 'normal', 0.0235386802966834, 'normal', 1.0260990338779652, 0.9673435010521582, 0.9442019974949926], ['female', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 26.94, 'abnormal', 'T1 not fused, Processus spinosus missing, left C7 rib rudiment, tail tip cut off-24 caudal vertebrae, cranial sutures open', 535.7060331963766, 'normal', 0.0064563237385188, 'normal', 1.011596084516426, 1.0043833575361487, 0.9601442759422736], ['female', 'Mlkl', 'c309', datetime.date(2023, 10, 9), 26.51, 'normal', 'T1 not fused', 609.3124310371095, 'normal', 0.004054417585796, 'normal', 1.0082950346977977, 0.9852770381684552, 0.9634082778879972], ['female', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.35, 'abnormal', 'T1 not fused + extra process, kyphosis, cranial sutures open', 541.0790610194509, 'normal', 0.0022481841589485, 'normal', 0.993071581211358, 0.9682469223498228, 0.9336674510152834], ['male', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.91, 'normal', None, 425.5973184617495, 'normal', 0.0011144844548633, 'normal', 1.0162435437719457, 0.9994173629124888, 0.9784203262220292], ['female', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 27.19, 'abnormal', 'Processus spinosus missing, T1 not fused + extra process, left C7 rib rudiment + right C7 process abnormal, cranial sutures open', 525.6155362690224, 'normal', 0.0005956727258752, 'normal', 1.0353123128968589, 1.0019795062090813, 0.9802836801475492], ['female', 'Mlkl', 'c309', datetime.date(2023, 10, 9), 26.05, 'abnormal', 'RHp II. Osteoneogenesis, cranial sutures open mild', 424.0855148525401, 'normal', 0.0, 'normal', 1.0058491055610437, 0.9798211417123248, 0.9502022288995065], ['male', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.52, 'normal', 'T1 not fused + extra process, left C7 rib rudiment, kyphosis severe', 357.80662271698145, 'normal', 0.0002305829906613, 'normal', 1.030441540115685, 1.0010280779467005, 0.9633913914003046], ['female', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.42, 'abnormal', 'Processus spinosus missing, scoliotic, cranial sutures open', 515.86467070126, 'normal', 0.0004035202336574, 'normal', 1.0012471414007955, 0.9938437232966072, 0.9773940508219984], ['male', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.51, 'normal', 'scoliotic', 465.2192292785644, 'normal', 0.0043618615733446, 'normal', 1.0448173840117188, 1.0017609189216872, 0.9731693278819974], ['male', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 27.27, 'normal', 'pectus excavatum, kyphosis', 399.5799815088152, 'normal', 0.0001921524922178, 'normal', 1.0148501506634455, 0.981481806836174, 0.971773841756434], ['male', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 27.12, 'normal', 'T1-T2 transposed, left + right C7 rib rudiment,', 674.7901047101452, 'normal', 0.0184850697513546, 'normal', 1.0352840240148735, 1.0139912077793864, 0.9604987800359046], ['female', 'Mlkl', 'c309', datetime.date(2023, 10, 9), 27.38, 'abnormal', 'T1 not fused, cranial sutures open', 794.4554684739644, 'normal', 0.0, 'normal', 1.0514492129383042, 1.0116053877411977, 0.9895004414817068], ['female', 'Mlkl', 'c309', datetime.date(2023, 10, 9), 26.53, 'normal', 'T1 not fused, Processus spinosus missing, pectus excavatum', 438.0111413464448, 'normal', 0.0038046193459129, 'normal', 1.0171667088217229, 0.9936749685020534, 0.9825614391130127], ['male', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 27.41, 'normal', 'C6+C7 not fused, left C7 rib rudiment + C7 process abnormal, T1-T2 transposed, pectus excavatum, kyphosis', 727.0239812699475, 'normal', 0.02878444333423, 'normal', 1.0124898860595055, 0.991412184806058, 0.9567074412684], ['male', 'Wnt3a', 'c309', datetime.date(2023, 10, 9), 27.01, 'normal', 'scoliotic, kyphosis, T1-T2 transposed, right C7 rib rudiment', 506.6052800774781, 'normal', 0.0287075823373429, 'normal', 1.0344223978476383, 0.9963381118951032, 0.9779605789585912], ['female', 'C57Bl/6NCrl', 'c309', datetime.date(2023, 10, 9), 26.84, 'normal', None, 462.79518834426233, 'normal', 0.000345874485992, 'normal', 1.0481581411973897, 1.0018032614406265, 0.9755488332034364]]
[['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.01, 'normal', 'kyphosis, LHP II. Osteoneogenesis', nan, nan, nan, nan, nan, nan, nan], ['female', 'Mta1', 'c298', datetime.date(2023, 7, 24), 26.66, 'normal', None, 622.152013994619, 'normal', 0.0034010991122554, 'normal', 0.9978411283037586, 0.9734655058975448, 0.9476157350254224], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 27.94, 'abnormal', 'T1 not fused, cranial sutures open', 465.2503481979984, 'normal', 0.0054955612774297, 'normal', 1.0376504685516377, 1.01982299070461, 0.997426795950301], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), 27.32, 'normal', 'T1 not fused', 463.6433133922507, 'normal', 0.040179086122747, 'normal', 1.036869632449779, 1.0127257761563866, 0.987031542321364], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), 27.2, 'normal', 'T1 not fused, left C7 rib rudiment, L6 = half S0', 560.1194757463579, 'normal', 0.0005380269782099, 'normal', 1.0481531953053689, 1.0154030216180157, 0.9919853371951054], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.95, 'abnormal', 'cranial sutures open', 491.141122641517, 'normal', 0.0012489911994158, 'normal', 1.0106206442715695, 0.9895648343493836, 0.9722436988229168], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 27.26, 'abnormal', 'cranial sutures open', 619.0097299253741, 'normal', 0.0030552246262634, 'normal', 1.012300741748658, 1.0032028065621874, 0.9524817892777668], ['female', 'Mta1', 'c298', datetime.date(2023, 7, 24), 27.27, 'normal', 'T1 not fused', 443.62548192530994, 'normal', 0.0002305829906613, 'normal', 1.0358689089632556, 1.0105970684821657, 0.990999033954564], ['female', 'Cobl', 'c298', datetime.date(2023, 7, 24), 26.52, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 394.728409849772, 'normal', 0.0009799777103109, 'normal', 0.9974795804461312, 0.9768812391990828, 0.9403738960047368], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.44, 'normal', 'T1 not fused', 538.3794292779198, 'normal', 0.0005956727258752, 'normal', 1.0165144464400824, 0.9975554750152656, 0.9745761136783232], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.57, 'normal', 'scoliotic', 441.2927895545544, 'normal', 0.0020368164175089, 'normal', 0.9992537424134776, 0.9956130056545908, 0.962562442709705], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 25.86, 'abnormal', 'cranial sutures open', 555.1036143681015, 'normal', 0.0001345067445524, 'normal', 0.9813851650296228, 0.9787105715316756, 0.9308648012586548], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), 27.35, 'normal', 'scoliotic mild, L6 = half S0', 524.6595817029762, 'normal', 0.0040352023365743, 'normal', 1.0534493262017113, 0.9999029995342368, 0.9878480949691568], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), nan, 'normal', 'scoliotic severe, kyphosis, sternum crooked', 566.0030543246837, 'normal', 0.0006725337227623, 'normal', 1.0347249629854307, 1.0182017405924686, 0.9975742314471092], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 27.48, 'normal', None, 448.4717064556831, 'normal', 0.0013450674455247, 'normal', 1.024156635994816, 0.9958980407591556, 0.9797411375339008], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), 27.73, 'normal', 'T1 not fused', 558.265726363996, 'normal', 0.0064947542369624, 'normal', 1.0605329398189982, 1.0383331529349145, 1.004246132002958], ['female', 'Cobl', 'c298', datetime.date(2023, 7, 24), 27.91, 'normal', None, 605.4425541643835, 'normal', 0.0369701395027093, 'normal', 1.0050721395000637, 0.9900810234465208, 0.9307813358087562], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.84, 'normal', 'scoliotic, LHp II. Osteoneogenesis', 638.6243677548856, 'normal', 0.0077437454363783, 'normal', 1.0021345392785157, 0.995972997630156, 0.9669239056009724], ['female', 'Cer1', 'c298', datetime.date(2023, 7, 24), 26.82, 'abnormal', 'T1 not fused, C7 process abnormal, cranial sutures open', 462.074800641937, 'normal', 1.9215249221782407e-05, 'normal', 1.0293667533734716, 1.0146571079630846, 0.9821116308885424], ['female', 'Cer1', 'c298', datetime.date(2023, 7, 24), 27.0, 'abnormal', 'T1 not fused, cranial sutures open', 616.7471995969531, 'normal', 0.0092617501248991, 'normal', 1.0383613823482436, 1.0108569015497983, 1.002118423897986], ['female', 'Mta1', 'c298', datetime.date(2023, 7, 24), 26.91, 'normal', 'T1 not fused', 491.3234235613783, 'normal', 0.0004803812305445, 'normal', 1.0337773529510317, 1.0209898380056386, 0.998858320397602], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 27.14, 'normal', None, 440.07308640318354, 'normal', 0.0, 'normal', 1.0221375968444295, 1.009996716362329, 0.9797114015838322], ['female', 'Mta1', 'c298', datetime.date(2023, 7, 24), 26.19, 'normal', 'kyphosis', 561.4672894781612, 'normal', 0.0066484762307367, 'normal', 1.0180194916256968, 0.9713172784108112, 0.9640454318753556], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.58, 'normal', None, 498.7538423469258, 'normal', 0.0004803812305445, 'normal', 1.0071475312809592, 0.9855087204891224, 0.9526498037547966], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 27.16, 'normal', 'T1 not fused', 370.9249746751564, 'normal', 0.0, 'normal', 1.0354765324235926, 0.9996204678704868, 0.985870765571246], ['female', 'Mta1', 'c298', datetime.date(2023, 7, 24), 26.9, 'normal', 'T1 not fused', 456.4830119697641, 'normal', 0.0020176011682871, 'normal', 1.022630520729994, 0.9956159561380468, 0.970945071629682], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), 27.12, 'normal', 'T1 not fused', 520.8145897093406, 'normal', 0.0004035202336574, 'normal', 1.0342823005091712, 1.0157666496474982, 0.9766533279059054], ['female', 'Cer1', 'c298', datetime.date(2023, 7, 24), 27.09, 'normal', 'pectus excavatum', 560.4879591459606, 'normal', 0.0028630721340455, 'normal', 1.046118234344891, 1.0105008232343635, 0.9930229305313468], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.27, 'normal', None, 460.4659573546864, 'normal', 0.0014411436916336, 'normal', 0.9964876506389636, 0.9830441396725864, 0.9525933768125008], ['male', 'Mta1', 'c298', datetime.date(2023, 7, 24), 26.86, 'normal', '23 caudal vertebrae (tail tip cut off)', 445.85236945738944, 'normal', 0.0001152914953306, 'normal', 1.048197473258218, 1.0122869705323447, 0.9874383069517638], ['male', 'Cer1', 'c298', datetime.date(2023, 7, 24), 28.63, 'normal', 'T1 not fused, pectus excavatum', 502.12934412107467, 'normal', 0.0141424234272318, 'normal', 1.0173397723252904, 0.9863884532490804, 0.9641705030595872], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.98, 'abnormal', 'T1 not fused, scoliotic, kyphosis, cranial sutures open', 357.1029144711863, 'normal', 0.3627262595595865, 'abnormal', 1.0977438026084718, 1.0022740892462738, 0.94375303514787], ['female', 'Mta1', 'c298', datetime.date(2023, 7, 24), 26.52, 'normal', 'L6 = half S0', 545.6791781860475, 'normal', 0.0010376234579762, 'normal', 1.0242303534287205, 0.9937013769059264, 0.9656447457848596], ['male', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 26.16, 'normal', 'kyphosis', 372.6618545663573, 'normal', 0.0027477806387148, 'normal', 0.9996264646681288, 0.9632619710624382, 0.9511039603836532], ['female', 'C57Bl/6NCrl', 'c298', datetime.date(2023, 7, 24), 28.78, 'normal', None, 340.6633635312565, 'normal', 0.0, 'normal', 1.018711297156721, 1.004390711152381, 0.9743643024692802]]

[['male', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 27.11, 'normal', 'T1-T2 transposed, left C7 rib rudiment, lordosis', 623.7793601810238, 'normal', 0.015891011106414, 'normal', 1.023192311548032, 1.0126790503208811, 0.966593210782188], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.09, 'abnormal', 'T1 not fused, cranial sutures open', 499.3853803001271, 'normal', 0.0, 'normal', 1.0242718680312648, 0.9909373620099388, 0.9638004739390136], ['female', 'Gzmb', 'c301', datetime.date(2023, 8, 14), 26.18, 'abnormal', 'LHp II. Osteoneogenesis mild, cranial sutures open', 610.1978250166, 'normal', 0.0054187002805426, 'normal', 1.0037061040034403, 0.9677165048411024, 0.9484658882707862], ['female', 'Gzmb', 'c301', datetime.date(2023, 8, 14), 26.94, 'abnormal', 'T1 not fused, cranial sutures open', 615.6183237035254, 'normal', 0.0007686099688712, 'normal', 0.9970609237703498, 0.989339322381298, 0.9346817759294572], ['male', 'Gzmb', 'c301', datetime.date(2023, 8, 14), 25.79, 'normal', 'lordosis', 774.9215232739901, 'normal', 0.0083202029130317, 'normal', 0.9969467721981116, 0.9539382214888724, 0.913324530972178], ['female', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 26.9, 'abnormal', 'cranial sutures open', 406.3160695552028, 'normal', 9.607624610891204e-05, 'normal', 1.0116398079305615, 0.9853914020547172, 0.9726189180154692], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.49, 'normal', 'T1 not fused', 599.5498642621076, 'normal', 0.0126436339879328, 'normal', 1.0157016060133062, 0.9638893592905048, 0.9358916510591622], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.0, 'normal', 'T1 not fused, Processus spinosus missing, pectus excavatum mild, LHp II. Osteoneogenesis', 482.199923576148, 'normal', 5.764574766534722e-05, 'normal', 1.0082114217388258, 0.9925000522436114, 0.974519899092898], ['female', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 26.84, 'abnormal', 'T1 not fused, cranial sutures open', 431.3725315858354, 'normal', 0.0024403366511663, 'normal', 1.0148910594864906, 1.000506602380623, 0.9724784100304396], ['male', 'Gzmb', 'c301', datetime.date(2023, 8, 14), 25.98, 'abnormal', 'T1 not fused, scoliotic, RHp II. Osteoneogenesis, cranial sutures open, I1/ enamel defect?', 550.4951651359868, 'normal', 0.002382690903501, 'normal', 1.0046065139223832, 0.971056267009792, 0.944141462116112], ['male', 'Pla2g5', 'c301', datetime.date(2023, 8, 14), 27.27, 'normal', None, 838.4099038704775, 'normal', 0.0733446062795434, 'normal', 1.054377905422667, 1.02632729220687, 0.982279180759504], ['male', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 26.93, 'normal', None, 554.244992812932, 'normal', 0.0017485876791821, 'normal', 1.0414009075560668, 0.9866922479042914, 0.963370574567123], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.39, 'normal', 'T1 not fused, scoliotic mild', 560.8437542122181, 'normal', 9.607624610891204e-05, 'normal', 1.0007114893107198, 0.9745552418794968, 0.9499981294363404], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.26, 'normal', 'T1-T2 transposed, pectus excavatum mild', 452.5376690740684, 'normal', 0.0033626686138119, 'normal', 1.0083247489805347, 1.003913042464036, 0.9810677672158276], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.25, 'abnormal', 'scoliotic mild, cranial sutures open', 522.9694192745324, 'normal', 0.0029591483801544, 'normal', 1.0337346589577217, 0.9851185653910292, 0.95219546464788], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.14, 'normal', 'T1 not fused', 535.3292814518751, 'normal', 0.0001921524922178, 'normal', 0.982242112793007, 0.9691080691590764, 0.9364171527641691], ['male', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 28.15, 'normal', 'T1 + T2 fused together', 383.82689768229415, 'normal', 0.0029399331309327, 'normal', 1.0397910850785672, 1.0013283707185452, 0.98766150668553], ['female', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 26.28, 'abnormal', 'T1 not fused, left + right C7 rib rudiment, cranial sutures open', 807.5594474107833, 'normal', 0.01218246800661, 'normal', 0.9969946631729836, 0.9584434792805512, 0.9289496233335685], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.08, 'normal', 'pectus excavatum, lordosis', 665.0254218270092, 'normal', 0.0036893278505822, 'normal', 1.0025829519956448, 0.9716609360236416, 0.9256794961517472], ['male', 'Gzmb', 'c301', datetime.date(2023, 8, 14), 28.09, 'normal', 'I1/ enamel defect?, pectus excavatum', 302.7278502614455, 'normal', 0.0, 'normal', 1.0123478198620477, 0.9915459908215476, 0.9692874213098884], ['male', 'Gzmb', 'c301', datetime.date(2023, 8, 14), 27.1, 'normal', 'T1 not fused, I1/ enamel defect?', 360.9091423576092, 'normal', 0.0007686099688712, 'normal', 1.023350132979167, 0.980228205934424, 0.9742021686221618], ['female', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 27.29, 'normal', None, 367.5103119071573, 'normal', 0.0073786557011644, 'normal', 1.0141071074450247, 0.9959608662272996, 0.9774487739075632], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.08, 'normal', 'T1 not fused, scoliotic', 568.8289205667094, 'normal', 0.0060528035048614, 'normal', 1.0229286179326298, 0.9860749755482078, 0.9857213285183948], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.87, 'normal', None, 355.9143360044308, 'normal', 0.0, 'normal', 1.0214532366054667, 1.0027386587420843, 0.9751082188417628], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.39, 'normal', 'T1 not fused', 394.61466159617225, 'normal', 0.0005572422274316, 'normal', 0.994664513726532, 0.9890823676878772, 0.9531518156118256], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.51, 'normal', 'T1 not fused', 366.3777132037632, 'normal', 0.0006725337227623, 'normal', 1.0033713592437583, 0.9694127629074644, 0.9533988407184572], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 27.71, 'normal', 'pectus excavatum', 375.388924259332, 'normal', 0.0003650897352138, 'normal', 1.0054028986005776, 0.9987302275821254, 0.976277038417551], ['male', 'C57Bl/6NCrl', 'c301', datetime.date(2023, 8, 14), 26.77, 'normal', None, 506.96128572256566, 'normal', 0.0011144844548633, 'normal', 1.0201355144804949, 1.000728368875232, 0.985759884007338], ['male', 'Pla2g5', 'c301', datetime.date(2023, 8, 14), 28.12, 'normal', None, 638.407791639875, 'normal', 0.0004035202336574, 'normal', 1.0284499508256049, 1.010262391579432, 0.9936747300489353], ['male', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.54, 'normal', None, 508.7307447698725, 'normal', 0.0, 'normal', 1.0105690699724048, 0.990111520816373, 0.9600187459609278], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.18, 'normal', None, 496.2795453030964, 'normal', 0.0363552515276123, 'normal', 1.0012725722372906, 0.9584341204288844, 0.9254350432948564], ['female', 'Cd52', 'c301', datetime.date(2023, 8, 14), 26.75, 'normal', 'T1 not fused', 1162.9190368235525, 'abnormal', 0.0153721993774259, 'normal', 0.9905192826225662, 0.982763645331448, 0.9160744045926515]]
[['male', 'Mroh8', 'c274', datetime.date(2023, 1, 23), 27.03, 'normal', 'T1 not fused, pectus excavatum', 337.7239629956841, 'normal', 0.0008262557165366, 'normal', 1.0134098273965768, 0.9802138601888192, 0.9695266870751792], ['male', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 27.12, 'normal', 'T1 not fused', 502.0560950949143, 'normal', 0.000787825218093, 'normal', 1.0147803208169934, 0.9865328487827648, 0.969943048825267], ['female', 'Parp1', 'c274', datetime.date(2023, 1, 23), 26.19, 'normal', None, 553.0329044235356, 'normal', 0.0092233196264555, 'normal', 1.0164799209528126, 0.9678124909926556, 0.9566727686612622], ['male', 'Mroh8', 'c274', datetime.date(2023, 1, 23), 26.49, 'normal', 'scoliotic, left T1 rib abnormal shape', 330.99060999159656, 'normal', 0.0011913454517505, 'normal', 1.008835587742665, 0.9786501278945552, 0.9703609670149428], ['male', 'Parp1', 'c274', datetime.date(2023, 1, 23), 26.38, 'normal', 'scoliotic, left C7 rib', 567.8596970804283, 'normal', 0.0039967718381307, 'normal', 1.0056416279036628, 0.963074992706637, 0.94583684947129], ['male', 'Mroh8', 'c274', datetime.date(2023, 1, 23), 25.67, 'normal', 'scoliotic', 472.95316447341816, 'normal', 0.0011336997040851, 'normal', 0.9994033421906516, 0.9793382552757808, 0.9557114397429934], ['male', 'Parp1', 'c274', datetime.date(2023, 1, 23), 26.06, 'normal', 'tail tip deformed, T1 not fused, kyphosis', 477.7186763799514, 'normal', 0.0014603589408554, 'normal', 0.997230625161858, 0.9576594092012244, 0.9481381618512644], ['male', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 26.17, 'normal', 'T1 not fused, 13th right rib shorter', 452.6597399633408, 'normal', 0.002555628146497, 'normal', 1.002622208544964, 0.9818797160759964, 0.9670711878921584], ['female', 'Mroh8', 'c274', datetime.date(2023, 1, 23), 27.21, 'normal', 'T1 not fused', 470.45604610407946, 'normal', 0.0, 'normal', 1.0158126872701845, 1.0049614735795191, 0.9950804360537664], ['female', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 26.34, 'normal', 'T1 not fused, left C7 rib', 620.9832398592051, 'normal', 0.0044195073210099, 'normal', 1.0017918397547303, 0.9832947126753578, 0.9592417288739248], ['male', 'Parp1', 'c274', datetime.date(2023, 1, 23), 25.78, 'normal', None, 716.9472548902862, 'normal', 0.0095115483647822, 'normal', 0.9957629574656184, 0.9775207644147886, 0.9463060630501298], ['male', 'Parp1', 'c274', datetime.date(2023, 1, 23), 25.94, 'normal', None, 542.5134467667624, 'normal', 0.0053226240344337, 'normal', 0.9979360513869352, 0.9807706680598176, 0.9547522810776916], ['female', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 27.08, 'normal', 'T1 not fused', 460.8764587093714, 'normal', 0.0002497982398831, 'normal', 1.021777094320639, 0.9840345652719368, 0.9796008532365992], ['male', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 25.85, 'normal', 'T1-T2 transposed, pectus excavatum, LH II. Osteoneogenesis', 542.5894643988648, 'normal', 0.0039006955920218, 'normal', 1.0110982953923373, 0.9851218930985776, 0.9619170645154572], ['female', 'Parp1', 'c274', datetime.date(2023, 1, 23), 26.18, 'normal', '5+6th cervical vertebrae fused together', 567.4376352304158, 'normal', 0.0023058299066138, 'normal', 1.006663076977212, 0.9836789723089324, 0.9611819919640284], ['male', 'Parp1', 'c274', datetime.date(2023, 1, 23), 26.53, 'normal', None, 655.259793851687, 'normal', 0.0142000691748971, 'normal', 1.009012616281371, 0.9943292485066572, 0.9430770007002665], ['female', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 26.96, 'normal', 'T1 not fused', 506.8093587189957, 'normal', 0.0013066369470812, 'normal', 1.0124995915261965, 0.999430086182332, 0.9743248663386064], ['female', 'Parp1', 'c274', datetime.date(2023, 1, 23), 25.96, 'normal', 'LH II. Osteoneogenesis', 726.3816804163349, 'normal', 0.0021905384112831, 'normal', 1.0074638988183622, 0.9792756619146316, 0.9469599202665652], ['male', 'C57Bl/6NCrl', 'c274', datetime.date(2023, 1, 23), 26.11, 'normal', 'processus spinosus missing, C7 process abnormal', 438.7111360469192, 'normal', 0.0033818838630337, 'normal', 1.0171787042911349, 0.9814096354875051, 0.9585387621832384]]
[['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.68, 'abnormal', 'RHp I. Osteoneogenesis, cranial sutures open', 355.3525727542107, 'normal', 0.0018062334268475, 'normal', 1.001240907104203, 0.9712947261789368, 0.9378209544384796], ['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 25.63, 'normal', 'T1 not fused', 481.8347989208706, 'normal', 0.007148072710503, 'normal', 0.977465522376644, 0.9700893730448904, 0.9332405212768284], ['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 25.53, 'normal', None, 548.6866415966518, 'normal', 0.0, 'normal', 0.9722670004242322, 0.9559241516860372, 0.9485006646142528], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.59, 'normal', 'T1-T2 transposed, left C7 rib rudiment', 501.0238625786952, 'normal', 0.0044771530686753, 'normal', 1.039160094266462, 1.0229333953924669, 0.977762136081344], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.26, 'normal', 'L6 = half S0', 340.8233781710502, 'normal', 7.686099688712963e-05, 'normal', 1.0005721198207371, 0.991453037495797, 0.961952306823214], ['female', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.38, 'normal', 'T1 not fused', 436.6733442137049, 'normal', 0.0, 'normal', 1.0059656536882993, 0.9817571015420048, 0.9535895991682676], ['female', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 25.98, 'normal', 'scoliotic, lordosis', 590.3639609960514, 'normal', 0.0120479612620575, 'normal', 0.9923001125266582, 0.9674900086724768, 0.9525206921871004], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.79, 'normal', None, 534.2844124309427, 'normal', 0.0001537219937742, 'normal', 0.9906193216779972, 0.9724065386713374, 0.954822220808182], ['female', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.7, 'normal', 'T1 not fused', 501.6940593094553, 'normal', 0.0, 'normal', 1.001865651471405, 0.9941484525809536, 0.9651711680546866], ['male', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.53, 'normal', 'T1 not fused', 507.3681238355206, 'normal', 0.0066869067291802, 'normal', 1.0105435026308467, 0.9659277742767576, 0.9369405451654708], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.76, 'normal', None, 493.17808903260425, 'normal', 0.0107413243149763, 'normal', 1.0582301247154642, 0.9916846663948228, 0.9634720750728608], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.76, 'normal', 'T1 not fused, Processus spinosus missing, right incisors abnormal', 581.8700938179676, 'normal', 0.0428307905153529, 'normal', 1.0721531804551525, 1.0384805515845943, 0.9911958848730252], ['male', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.75, 'normal', None, 691.3469580862786, 'normal', 0.0201375811844279, 'normal', 1.0033388357635598, 0.9942900718040408, 0.9468998805846782], ['male', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 27.11, 'normal', 'kyphosis', 540.8789727901677, 'normal', 0.0024595519003881, 'normal', 1.057193412678348, 1.016029113260565, 0.9843778651482538], ['female', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.6, 'abnormal', 'kyphosis, pectus excavatum, cranial sutures open', 358.8189267843248, 'normal', 0.0001345067445524, 'normal', 1.0051946357769854, 0.9907122618772072, 0.9682393797019032], ['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.11, 'normal', 'tail cut off & broken (18 caudal vertebrae)', 512.848551167426, 'normal', 0.0004419507321009, 'normal', 1.0219552827015286, 0.9951433335684484, 0.9613631539039104], ['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.51, 'normal', 'T1 not fused', 455.46368349245466, 'normal', 0.0036701126013604, 'normal', 1.0023785547461708, 0.9891028365411988, 0.9601546695017495], ['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.89, 'normal', None, 615.0442922363413, 'normal', 0.0121632527573882, 'normal', 1.0096140182663091, 0.9998242671571712, 0.9679340511402966], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 26.17, 'normal', None, 655.4255487582313, 'normal', 0.0080127589254832, 'normal', 0.9883262820998522, 0.9821781823323784, 0.9488601437915648], ['female', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 27.26, 'abnormal', 'LHp II. Osteoneogenesis, cranial sutures open', 439.9009833552463, 'normal', 0.0002882287383267, 'normal', 0.9964027584535452, 0.9787775646821766, 0.9614151865094348], ['male', 'C57Bl/6NCrl', 'c306', datetime.date(2023, 9, 18), 27.17, 'normal', 'T1 not fused, kyphosis', 410.4544830497426, 'normal', 0.002824641635602, 'normal', 1.0304593975452103, 0.9729482356132404, 0.9647742952614012], ['female', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.3, 'normal', None, 343.0239811645683, 'normal', 0.000172937242996, 'normal', 0.9946921749145268, 0.982336723679688, 0.9685927992905708], ['female', 'Pcsk9', 'c306', datetime.date(2023, 9, 18), 26.66, 'normal', None, 447.56125899535294, 'normal', 0.0008839014642019, 'normal', 1.031823788589696, 0.9994414617993068, 0.9881659565579326]]

[['female', 'Enpp1', 'c288', datetime.date(2023, 5, 15), 25.86, 'abnormal', 'fusion of cervical ,hyperosification: thoracical vert., interscapular, tendon, costal cartilages + sternum , vibrissae follicles,snout , ears, digits', 957.1420402734768, 'normal', 0.0104723108258714, 'normal', 1.014287944551277, 0.9779761659775424, 0.9549638374859138], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 27.7, 'normal', 'pectus excavatum severe', 709.2995758794409, 'normal', 0.0404673148610737, 'normal', 1.0483726672835754, 1.0272081456182325, 0.9938558788583898], ['male', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 26.48, 'normal', 'pectus excavatum severe', 685.0133919501335, 'normal', 0.0275162368855924, 'normal', 1.0590324506835844, 1.0354454654539151, 0.9939902095514872], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.94, 'abnormal', 'T1 not fused, cranial sutures open', 690.5666332785868, 'normal', 0.0698282156719572, 'normal', 1.052590600567261, 1.0045432967693215, 0.9747916206170876], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.71, 'normal', 'T1 not fused, pectus excavatum, kyphosis', 483.8134796513479, 'normal', 0.0, 'normal', 1.0263399973334304, 1.0168515335167545, 0.9698199379706282], ['female', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 24.0, 'abnormal', 'T1 not fused, malocclusion, rostrum malformation, cranial sutures open', 3132.6667059827887, 'abnormal', 0.3102878444333423, 'abnormal', 0.992462277579515, 0.9347552322455456, 0.8720762014040567], ['female', 'Enpp1', 'c288', datetime.date(2023, 5, 15), 25.67, 'abnormal', 'fusion of cervical ,hyperosification: thoracical vert., interscapular, tendon, costal cartilages + sternum , vibrissae follicles,snout , ears, digits', nan, nan, nan, nan, nan, nan, nan], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 27.0, 'abnormal', 'T1 not fused, pectus excavatum mild, cranial sutures open mild', 592.194163767176, 'normal', 0.0014603589408554, 'normal', 1.0331272288441022, 1.00146250034149, 0.976288202718736], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.77, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open mild', 441.10175756981295, 'normal', 7.686099688712963e-05, 'normal', 1.0374870579470157, 0.9988509230517346, 0.981576012114206], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.54, 'normal', 'pectus excavatum mild, kyphosis', 561.1191339322806, 'normal', 0.0014219284424118, 'normal', 1.005519234139688, 0.9940435264988354, 0.9597244144174032], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.59, 'abnormal', 'T1 not fused, L6 = half S0, pectus excavatum mild, kyphosis, LHp II. Osteoneogenesis, cranial sutures open', 574.7296366525974, 'normal', 0.0024787671496099, 'normal', 1.0143922310493148, 0.9921894209709508, 0.9571051468828672], ['male', 'Gnl2', 'c288', datetime.date(2023, 5, 15), 27.46, 'normal', 'T1 not fused', 564.2964604055402, 'normal', 0.0004227354828792, 'normal', 1.018372127993178, 0.9889101081642468, 0.9779410005784696], ['male', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 27.17, 'normal', 'pectus excavatum severe', 531.9710558832468, 'normal', 0.0020560316667307, 'normal', 1.04911608034582, 1.030427328271465, 0.9931620010065844], ['male', 'Enpp1', 'c288', datetime.date(2023, 5, 15), 26.41, 'abnormal', 'fusion of cervical ,hyperosification: thoracical vert., interscapular, tendon, costal cartilages + sternum , vibrissae follicles,snout , ears, digits', nan, nan, nan, nan, nan, nan, nan], ['female', 'Gak', 'c288', datetime.date(2023, 5, 15), 26.57, 'normal', 'T1 not fused, kyphosis, pectus excavatum', 391.0815270264541, 'normal', 0.002555628146497, 'normal', 1.0335103698276458, 0.9833461201340836, 0.9604676017423096], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.45, 'normal', 'scoliotic, pectus excavatum mild', 535.877839903978, 'normal', 0.0034587448599208, 'normal', 1.016587803283825, 1.0085944719131328, 0.9985604005554692], ['female', 'Vsx1', 'c288', datetime.date(2023, 5, 15), 26.26, 'normal', None, nan, nan, nan, nan, nan, nan, nan], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 27.08, 'abnormal', 'T1 not fused, cranial sutures open', 515.5032617485813, 'normal', 0.0137965489412397, 'normal', 1.0388048113577226, 1.0047692207784773, 0.9661158125717628], ['female', 'Enpp1', 'c288', datetime.date(2023, 5, 15), 25.55, 'abnormal', 'fusion of cervical ,hyperosification: thoracical vert., interscapular, tendon, costal cartilages + sternum , vibrissae follicles,snout , ears, digits', 1995.9171703232864, 'abnormal', 0.0477306790669075, 'normal', 1.020249041472379, 0.9728718190547418, 0.940435129695766], ['male', 'Enpp1', 'c288', datetime.date(2023, 5, 15), 26.86, 'abnormal', 'fusion of cervical ,hyperosification: thoracical vert., interscapular, tendon, costal cartilages + sternum , vibrissae follicles,snout , ears, digits', 1574.8726755162352, 'abnormal', 0.0565504784597056, 'normal', 1.0111203451574624, 0.9959464379411298, 0.9815843846419264], ['female', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 26.67, 'abnormal', 'T1 not fused, cranial sutures open', 479.2375093385535, 'normal', 0.0003650897352138, 'normal', 1.0081659676020454, 0.9634153906931484, 0.9566392388105291], ['female', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 25.74, 'normal', 'kyphosis, RHp II. Osteoneogenesis', 1073.204387881579, 'abnormal', 0.0982667845201952, 'normal', 0.9769525400156552, 0.9540694547455048, 0.8951768420826812], ['female', 'Vsx1', 'c288', datetime.date(2023, 5, 15), 26.93, 'normal', 'pectus excavatum', 469.1348226854095, 'normal', 5.764574766534722e-05, 'normal', 1.0120070627232374, 1.009337657127434, 0.9834571757326476], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 27.4, 'abnormal', 'pectus excavatum mild, cranial sutures open', 392.2692021543844, 'normal', 0.0112601360439644, 'normal', 1.0521892036577158, 0.9974095921894915, 0.9895644170820024], ['female', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.38, 'normal', None, 604.1416545352267, 'normal', 0.0, 'normal', 1.0064013847875886, 1.0047827712700144, 0.9651701315175588], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.4, 'normal', 'T1 not fused, pectus excavatum mild', 483.6236666353085, 'normal', 0.0019599554206218, 'normal', 1.0027622427801193, 0.9789514514289094, 0.9500197017427056], ['female', 'Vsx1', 'c288', datetime.date(2023, 5, 15), 26.58, 'normal', 'T1 not fused', 431.13209409387497, 'normal', 0.0120287460128357, 'normal', 1.0117473058252455, 0.9937220797297586, 0.9593758450979308], ['male', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 26.26, 'normal', None, 1271.3074004693592, 'abnormal', 0.1175012489911994, 'abnormal', 0.9906354918882286, 0.9743589566991148, 0.9490271279911606], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.96, 'normal', 'pectus excavatum mild', 514.5087366877041, 'normal', 0.0017485876791821, 'normal', 1.0737278501479186, 1.014490722336715, 0.985308983603702], ['female', 'Gak', 'c288', datetime.date(2023, 5, 15), 26.74, 'abnormal', 'T1 not fused, pectus excavatum, cranial sutures open', 622.4747842575322, 'normal', 0.0016140809346297, 'normal', 1.0244557779826624, 1.0031518864753628, 0.9886261866146326], ['female', 'Gak', 'c288', datetime.date(2023, 5, 15), 26.4, 'abnormal', 'scoliotic, kyphosis, pectus excavatum mild, cranial sutures open', 733.3415969927984, 'normal', 0.0178125360285922, 'normal', 1.0308101012461095, 0.9999020514260644, 0.9898381735048672], ['male', 'Trak1 KO', 'c288', datetime.date(2023, 5, 15), 26.29, 'normal', 'kyphosis severe', 479.664555656308, 'normal', 0.0391991084124361, 'normal', 1.020890351159104, 0.9716489799720852, 0.9536553464495168], ['female', 'Gak', 'c288', datetime.date(2023, 5, 15), 26.21, 'abnormal', 'cranial sutures open', 519.2030937325718, 'normal', 0.0243457207639983, 'normal', 1.028816991657863, 0.9967371624744285, 0.99264568591045], ['male', 'C57Bl/6NCrl', 'c288', datetime.date(2023, 5, 15), 26.29, 'normal', 'scoliotic, kyphosis', 740.3162742722532, 'normal', 0.0427923600169094, 'normal', 1.0532819765588508, 0.9809532035768233, 0.9667232074989444]]
[['female', 'C57Bl/6NCrl', 'c255', datetime.date(2022, 9, 12), 27.12, 'abnormal', 'cranial sutures open', 387.2880542609993, 'normal', 0.0009031167134237, 'normal', 1.0149652881271076, 1.00086742380877, 0.9817156333853616], ['female', 'Nfe2l2', 'c255', datetime.date(2022, 9, 12), 27.03, 'normal', None, 575.0782541772667, 'normal', 0.0006341032243188, 'normal', 1.0040658745245916, 0.9996051532512612, 0.9640272894572794], ['female', 'Fam161b', 'c255', datetime.date(2022, 9, 12), 27.09, 'normal', None, 1571.3626923397958, 'abnormal', 0.0388148034280004, 'normal', 1.020329834475974, 0.968429590801239, 0.9546681769860196], ['female', 'Nfe2l2', 'c255', datetime.date(2022, 9, 12), 26.12, 'normal', 'T1 not fused', 598.022311664091, 'normal', 3.8430498443564814e-05, 'normal', 0.99135818536143, 0.9780846356568772, 0.9584696853318057], ['male', 'Fam161b', 'c255', datetime.date(2022, 9, 12), 25.68, 'normal', 'pectus excavatum', 2021.890364425965, 'abnormal', 0.9997886322585604, 'abnormal', 1.2288499242659503, 0.9720371115345976, 0.7474177903732214], ['male', 'Fam161b', 'c255', datetime.date(2022, 9, 14), 26.08, 'normal', None, 2914.211758507655, 'abnormal', 0.1216709580723262, 'abnormal', 1.0469316677961336, 0.9836660993832124, 0.9480004103533392], ['female', 'Fam161b', 'c255', datetime.date(2022, 9, 12), 26.19, 'abnormal', 'cranial sutures open', 8819.333134530885, 'abnormal', 0.0577418239114561, 'normal', 1.0138259854464828, 0.9742609385900798, 0.8956266829760663], ['female', 'C57Bl/6NCrl', 'c255', datetime.date(2022, 9, 12), 27.4, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open', 412.2235334686933, 'normal', 0.0005188117289881, 'normal', 1.0396496263812127, 1.0144377161175484, 0.9901806230120864], ['male', 'C57Bl/6NCrl', 'c255', datetime.date(2022, 9, 12), 27.0, 'normal', 'scoliotic mild', 383.7676154678708, 'normal', 0.000345874485992, 'normal', 1.0434501740934223, 1.016702614329858, 1.004526600246033], ['female', 'Syngr1', 'c255', datetime.date(2022, 9, 12), 25.67, 'normal', None, 815.6106895844433, 'normal', 0.004938319049998, 'normal', 1.002648425380091, 0.9633336560235723, 0.921804139152824], ['male', 'Fam161b', 'c255', datetime.date(2022, 9, 12), 24.89, 'normal', None, 234757.73467081648, 'abnormal', 0.997694170093386, 'abnormal', 1.2443550676698352, 0.6954690746535568, 0.5307864477224524], ['male', 'Syngr1', 'c255', datetime.date(2022, 9, 14), 27.49, 'normal', None, 356.7789458159639, 'normal', 0.0007301794704277, 'normal', 1.03347653032623, 1.0073875610885186, 0.9755818199792816], ['male', 'Rnf34 tm1b', 'c255', datetime.date(2022, 9, 14), 26.89, 'normal', None, 432.36012457695927, 'normal', 0.0069367049690634, 'normal', 1.0359233241654309, 1.0087114763930205, 0.9706384329611571], ['female', 'Nfe2l2', 'c255', datetime.date(2022, 9, 12), 26.13, 'normal', 'scoliotic', 604.4948585906034, 'normal', 0.0041120633334614, 'normal', 0.99156970887219, 0.979788219630666, 0.9594397521679198], ['female', 'Syngr1', 'c255', datetime.date(2022, 9, 12), 26.26, 'normal', None, 656.9050009417953, 'normal', 0.0045347988163406, 'normal', 1.0092341336137325, 0.9723862263137416, 0.938921218773046], ['male', 'Syngr1', 'c255', datetime.date(2022, 9, 14), 26.27, 'normal', None, 612.2463937502889, 'normal', 0.0143537911686714, 'normal', 0.9934414986296968, 0.9746892889840222, 0.944452184160488], ['female', 'C57Bl/6NCrl', 'c255', datetime.date(2022, 9, 12), 27.42, 'normal', 'RH II. Osteoneogenesis', 431.9526693267131, 'normal', 0.0, 'normal', 1.0201500384422562, 0.9976379389947876, 0.9952719226040267], ['female', 'Syngr1', 'c255', datetime.date(2022, 9, 12), 27.1, 'normal', None, 525.2312292761351, 'normal', 0.0028054263863802, 'normal', 1.019434813871661, 1.0125763041534488, 0.9741283651591376]]
[['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.46, 'abnormal', 'tail move, kyphosis, cranial sutures open mild', 397.2559567372083, 'normal', 0.0, 'normal', 0.9925490787268751, 0.9836227707431812, 0.9638121514696748], ['female', 'Ism1', 'c314', datetime.date(2023, 11, 14), 28.12, 'abnormal', 'T1 not fused, cranial sutures open + shorter rostrum', 598.622916137255, 'normal', 0.0024403366511663, 'normal', 1.027193025076777, 1.0068433697882164, 0.9739567697315584], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.07, 'abnormal', 'tail tip deformed, cranial sutures open', 691.6791160354383, 'normal', 0.0117981630221743, 'normal', 1.040119962730911, 1.0011913002055073, 0.9765119461019142], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.64, 'abnormal', 'T1 not fused, tail move, cranial sutures open', 562.29670074506, 'normal', 0.0130471542215902, 'normal', 1.011224075105907, 0.9657103737045204, 0.9519010831113242], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.33, 'abnormal', 'tail move, T1 extra process, scoliotic mild, kyphosis, cranial sutures open', 878.931632189381, 'normal', 0.022693209330925, 'normal', 1.04646660389865, 1.0191307223885435, 0.9601393580359188], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.34, 'abnormal', 'kyphosis mild, cranial sutures open mild', 246.75296583045733, 'normal', 0.0, 'normal', 1.0044359454662162, 0.9727173836986712, 0.9558959853376324], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 25.75, 'abnormal', 'cranial sutures open', 529.7191000827509, 'normal', 0.0005572422274316, 'normal', 1.02429684110471, 0.989858448771733, 0.9639568308181334], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.73, 'normal', 'kyphosis', 359.59801763858815, 'normal', 0.000345874485992, 'normal', 1.0207032099995628, 0.9997273557737472, 0.9816553659485048], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.49, 'normal', None, 525.5305200746162, 'normal', 3.8430498443564814e-05, 'normal', 1.0423272386076925, 1.013150431682568, 0.9788476791764368], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.25, 'normal', 'T1 not fused, pectus excavatum', 497.8564488382837, 'normal', 0.0077053149379347, 'normal', 1.0159910161928227, 0.9882876663143132, 0.9578676953677818], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.34, 'abnormal', 'cranial sutures open mild', 470.0950720981866, 'normal', 0.0067445524768456, 'normal', 1.0080763190020716, 1.0017360051583388, 0.9477081984821798], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 27.11, 'normal', None, 497.0868129473686, 'normal', 0.0042850005764574, 'normal', 1.0307348757067485, 1.0061269297794266, 0.9875008078706768], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.75, 'normal', 'pectus excavatum', 346.84939593868563, 'normal', 0.0, 'normal', 1.026754370231174, 1.0132543519348682, 0.9848153518671084], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 25.92, 'normal', 'T1 not fused, pectus excavatum', 518.0250358486388, 'normal', 0.0097421313554436, 'normal', 1.0246379478099643, 0.989490779496393, 0.971204066839942], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.14, 'normal', None, 452.0315824703088, 'normal', 0.0, 'normal', 1.0036353917010217, 0.9876084998951764, 0.939788925327864], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.48, 'abnormal', 'tail tip deformed, cranial sutures open mild', 388.1403278970042, 'normal', 0.0, 'normal', 1.0096005098786502, 0.999167178721781, 0.9800465334344046], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.6, 'normal', 'lordosis', 344.74218973342533, 'normal', 0.0, 'normal', 1.0139754224552715, 0.9787405558502408, 0.963487539397501], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 27.01, 'normal', 'pectus excavatum severe', 510.4992478295917, 'normal', 0.002824641635602, 'normal', 1.0263635149759145, 0.9896305018508568, 0.9761433914996052], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 27.01, 'normal', None, 330.9410906109058, 'normal', 0.0027477806387148, 'normal', 1.0360312299927412, 1.0025379653951625, 0.9792345582773678], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.53, 'abnormal', 'tail move, kyphosis mild, cranial sutures open mild', 477.9471098623092, 'normal', 0.0046885208101149, 'normal', 0.9922741941420624, 0.977110627371902, 0.9486611826760796], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.4, 'normal', 'T1 not fused', 283.00174173220387, 'normal', 0.0004035202336574, 'normal', 1.0044302618227978, 0.9855635751429496, 0.9531518250163816], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.69, 'normal', 'kyphosis', 380.78467107039097, 'normal', 0.0, 'normal', 1.0082369951688162, 0.9985788044230846, 0.9693604089537456], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.59, 'normal', 'T1 not fused', 432.9576237994485, 'normal', 0.0015564351869643, 'normal', 1.0203045833101123, 0.9905895843640832, 0.9758589400364138], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.32, 'abnormal', 'tail tip deformed, cranial sutures open', 530.4559516229698, 'normal', 0.0018638791745128, 'normal', 1.0231653458737917, 0.9983705871458796, 0.970661345592736], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 25.54, 'normal', 'tail move', 435.2344903794337, 'normal', 0.0, 'normal', 0.983730979435027, 0.9693618461663132, 0.9489577228137672], ['female', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 26.31, 'normal', None, 502.8728799352591, 'normal', 0.0086276469005803, 'normal', 1.0279809012571484, 1.010912109598843, 0.980320476433721], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 27.06, 'normal', None, 296.4359346372504, 'normal', 0.0116636562776219, 'normal', 1.0190708810251894, 1.0036698219511313, 0.9845119252674408], ['male', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.84, 'normal', 'T1 not fused', 569.4278785321895, 'normal', 0.0019215249221782, 'normal', 1.000749424237836, 0.9849408408136866, 0.9515290332021128], ['female', 'nc02f09Rik', 'c314', datetime.date(2023, 11, 14), 26.02, 'normal', None, 386.15563637648233, 'normal', 3.8430498443564814e-05, 'normal', 0.9985712950666632, 0.994885188001655, 0.9464495844615476], ['male', 'C57Bl/6NCrl', 'c314', datetime.date(2023, 11, 14), 28.11, 'normal', 'L6 = half S0, pectus excavatum', 617.1606455956728, 'normal', 0.0107221090657545, 'normal', 1.0072032534511786, 0.99087118448644, 0.9739240958549992]]

[['female', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 25.65, 'abnormal', 'kyphosis, mildly scoliotic, rostrum rounded, cranial sutures open mild', 2322.643223775982, 'abnormal', 0.2280657930133353, 'abnormal', 1.047431033871185, 1.0317557087010556, 0.9228074604354292], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.94, 'normal', 'T1 not fused', 360.746028722889, 'normal', 0.0003074439875485, 'normal', 1.0175146170320015, 0.9897368440187244, 0.9665910185305836], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.9, 'abnormal', 'pectus excavatum, cranial sutures open', 398.24520927560457, 'normal', 0.0, 'normal', 1.013544543920334, 0.9942393253680204, 0.9623108361477564], ['male', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 27.2, 'normal', 'C4+C5 fused,', 637.8403159138524, 'normal', 0.0484416432881134, 'normal', 1.0490856921588472, 1.010124419500147, 0.9843442065973336], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.38, 'normal', 'T1 not fused, pectus excavatum mild', 428.9008655227205, 'normal', 0.0011336997040851, 'normal', 1.0219362783758748, 1.009246595479275, 0.996046863688694], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.0, 'abnormal', 'T1 not fused, cranial sutures open, pectus excavatum', 551.8046342960907, 'normal', 0.0012874216978594, 'normal', 1.0089171621636392, 0.9960303370384896, 0.9436404122045317], ['male', 'Pamr1', 'c311', datetime.date(2023, 10, 23), 26.8, 'normal', None, 453.8282710194992, 'normal', 0.0014027131931901, 'normal', 0.9866636674838992, 0.9770646297320972, 0.9657772522463336], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.51, 'normal', 'T1 not fused', 394.86591024151056, 'normal', 0.0044579378194535, 'normal', 1.0209257160992615, 0.9909109171809216, 0.9672404496961128], ['male', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 27.07, 'abnormal', 'cranial sutures open, pectus excavatum', 659.9632147614873, 'normal', 0.0030744398754851, 'normal', 1.0366438546784538, 1.0082915547290707, 0.9747261460377382], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.52, 'abnormal', 'scoliotic mild, T1 not fused, kyphosis, cranial sutures open', 687.4072818876075, 'normal', 0.0164674685830675, 'normal', 1.0011961170927324, 0.992327784105252, 0.9565937359805158], ['female', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 27.64, 'normal', 'sternum crooked,', 419.47216856895335, 'normal', 0.0042657853272356, 'normal', 1.0410991119507638, 1.025899455387294, 0.9976116700684604], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.71, 'abnormal', 'T1 not fused, kyphosis, cranial sutures open mild', 352.7369452152828, 'normal', 0.0, 'normal', 0.999348262803552, 0.988584065536708, 0.9736305883017732], ['female', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 26.11, 'abnormal', 'cranial sutures open', 498.1801377239327, 'normal', 0.0, 'normal', 0.993869575119886, 0.9759091201970428, 0.9517192226426116], ['male', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 28.08, 'normal', 'kyphosis, pectus excavatum, processus xiphoideus malformed,', 653.8738284794512, 'normal', 0.0699435071672879, 'normal', 1.1218506682981737, 1.045692307479575, 0.998156394179331], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.64, 'abnormal', 'cranial sutures open severe + microphtalmia R', 665.1821267227562, 'normal', 0.0204642404211982, 'normal', 1.0216905155943183, 1.001065090436272, 0.9476728636000356], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.19, 'normal', 'T1 not fused', 352.9748779192863, 'normal', 0.0, 'normal', 1.0048702398867286, 0.9921653926996572, 0.9775880663768692], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.08, 'abnormal', 'kyphosis, L3 malformed, cranial sutures open', 437.7116096154148, 'normal', 0.0008454709657584, 'normal', 1.0232574077687024, 1.0208878230995106, 0.9720963996545788], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.0, 'normal', 'T1 not fused, pectus excavatum, processus xiphoideus malformed,', 676.2745964343386, 'normal', 0.0063986779908535, 'normal', 1.0295517768204503, 0.9999149453902402, 0.9660254145829305], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.29, 'normal', 'T1 not fused', 472.7939993837354, 'normal', 0.0020944621651742, 'normal', 1.0286092093020451, 1.0074357203379871, 0.9952430279662824], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 28.54, 'normal', 'pectus excavatum severe', 361.6133366796744, 'normal', 3.8430498443564814e-05, 'normal', 1.031020044720618, 1.004168043076299, 0.9843524070077992], ['male', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.08, 'normal', 'T1 not fused, pectus excavatum', 486.0752215163871, 'normal', 0.0002882287383267, 'normal', 0.995796417342484, 0.9943249395632588, 0.9652689689527426], ['male', 'Pamr1', 'c311', datetime.date(2023, 10, 23), 27.2, 'normal', 'pectus excavatum', 473.1360481560188, 'normal', 0.0007109642212059, 'normal', 0.997426406122032, 0.9810429782534894, 0.9682690143402868], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 26.8, 'normal', 'T1 not fused, pectus excavatum', 397.4013501862342, 'normal', 0.0018446639252911, 'normal', 1.0259089665426806, 1.006030997746746, 0.9745217970446524], ['male', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 27.66, 'normal', 'scoliotic mild, kyphosis', 527.5188320656516, 'normal', 0.0013450674455247, 'normal', 1.0338595149226184, 1.0111763727349443, 1.0062051887725731], ['female', 'C57Bl/6NCrl', 'c311', datetime.date(2023, 10, 23), 27.51, 'abnormal', 'cranial sutures open mild', 532.8369554043124, 'normal', 0.0004035202336574, 'normal', 1.0147579170668968, 1.0039985261048927, 0.99087222261378], ['female', 'Sord', 'c311', datetime.date(2023, 10, 23), 27.09, 'normal', 'T1 not fused', 380.0581977705328, 'normal', 0.0, 'normal', 1.0099362646797894, 0.9937096683233502, 0.9694502509136892]]
[['female', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 23.54, 'abnormal', 'scoliotic mild, T1 not fused, barrel chest + sternum crooked, rostrum malformation + cranial sutures open', 3096.6581255436945, 'abnormal', 0.2923023711617539, 'abnormal', 0.9971144152695391, 0.9420658997175873, 0.8667744738668344], ['male', 'Ptprz1', 'c276', datetime.date(2023, 2, 6), 26.69, 'normal', 'pectus excavatum', 484.972886544524, 'normal', 0.0039583413396871, 'normal', 1.0117205174319188, 0.9955774173915176, 0.9753153044975176], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 25.7, 'normal', None, 550.6004561059601, 'normal', 0.0, 'normal', 0.9865634404385104, 0.9861934048683552, 0.941660725654096], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.64, 'normal', 'T1 not fused', 439.62313454153326, 'normal', 0.0007686099688712, 'normal', 1.013125782990372, 0.9880755470399032, 0.9540043807942185], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.46, 'normal', None, 278.1028129911826, 'normal', 0.0, 'normal', 1.001145030653407, 0.991008101667138, 0.9682966130383645], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 28.39, 'normal', None, 477.5070383317029, 'normal', 0.0019215249221782, 'normal', 1.0503873146630496, 1.022075639041946, 0.9962389393082248], ['male', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 26.1, 'normal', None, 472.1463948946771, 'normal', 0.0017101571807386, 'normal', 1.0340282634550246, 0.9799810239983948, 0.9627496500910038], ['male', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 27.02, 'normal', 'pectus excavatum', 424.0473748776853, 'normal', 0.0029015026324891, 'normal', 1.0281354568269985, 0.9983942758168602, 0.9961707473070242], ['female', 'Ptprz1', 'c276', datetime.date(2023, 2, 6), 25.4, 'normal', 'T1 not fused, scoliotic, kyphosis', 1394.411255098611, 'abnormal', 0.1167710695207716, 'abnormal', 1.0411308248722486, 0.9777201690099776, 0.9459847578142776], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.26, 'normal', None, 744.4647105879267, 'normal', 0.0064563237385188, 'normal', 0.9921991063512022, 0.970437139206965, 0.9592851995714844], ['male', 'Mmp13', 'c276', datetime.date(2023, 2, 6), 26.46, 'normal', 'T1 not fused, pectus excavatum, kyphosis', 757.704204434145, 'normal', 0.0435417547365589, 'normal', 1.0244897959568695, 1.0078634818505512, 0.9485025665421408], ['female', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 25.47, 'abnormal', 'scoliotic severe, interscapular ossification, scapuli deformed, barrel chest, hindpaw fingers gnarled but not broken, rostrum malformation + cranial sutures open mild', 2036.4918123526077, 'abnormal', 0.5491141770108758, 'abnormal', 1.0039839785821023, 0.9560730012989836, 0.9065991064839608], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 27.41, 'normal', None, 462.5264689756831, 'normal', 0.0009031167134237, 'normal', 1.0144901970357547, 1.000315646746022, 0.983864104190911], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.8, 'normal', 'pectus excavatum', 548.3329520438585, 'normal', 0.0, 'normal', 1.0425835463160094, 0.9938664134696324, 0.9859436434967694], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.13, 'normal', None, 459.67424365230016, 'normal', 0.0071672879597248, 'normal', 1.0165899370371156, 1.00601028159647, 0.9735678659607068], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 25.76, 'normal', 'T1 not fused', 616.88423344347, 'normal', 0.003439529610699, 'normal', 0.9859269758675664, 0.981681649097472, 0.9569092039381206], ['male', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 27.87, 'normal', None, 323.7852790926218, 'normal', 0.0063986779908535, 'normal', 1.0400508616502244, 1.0273255665979848, 0.9928383947039646], ['male', 'Ptprz1', 'c276', datetime.date(2023, 2, 6), 26.61, 'normal', None, 455.64135192551504, 'normal', 0.0019983859190653, 'normal', 1.039957718774676, 1.018627457326034, 0.9821733927973684], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.5, 'normal', 'T1 not fused', 553.5868100399226, 'normal', 0.0085700011529149, 'normal', 1.0071339306541174, 1.0010792977522571, 0.998694388040036], ['female', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 26.01, 'abnormal', 'cranial sutures open mild', 464.93722447722, 'normal', 0.0006917489719841, 'normal', 1.0076688729454135, 0.9876312612057272, 0.9717450969222912], ['female', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 26.23, 'normal', 'RH II. Osteoneogenesis', 501.9819537420095, 'normal', 0.009530763614004, 'normal', 0.9994641637011838, 0.98660503541856, 0.9696804562575824], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 25.73, 'normal', None, 844.0235587216878, 'normal', 0.0332231659044617, 'normal', 1.0068602182325848, 0.9755803147959086, 0.9536517356248158], ['male', 'Agpat2', 'c276', datetime.date(2023, 2, 6), 24.05, 'normal', 'T1 not fused, pectus excavatum, hindpaw fingers gnarled', 1238.1638530855998, 'abnormal', 0.1269551516083163, 'abnormal', 0.9820251835978664, 0.9544575806282748, 0.8949334965247707], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 28.31, 'normal', 'scoliotic, L6 = half S0', 365.8804855071134, 'normal', 0.0015180046885208, 'normal', 1.0108985653125104, 0.9947960530166322, 0.9883605438367128], ['male', 'Mmp13', 'c276', datetime.date(2023, 2, 6), 26.41, 'normal', 'kyphosis', 625.7456712668588, 'normal', 0.0224626263402636, 'normal', 1.0164010761569011, 0.9848690721539896, 0.9610375546848976], ['female', 'Ptprz1', 'c276', datetime.date(2023, 2, 6), 26.32, 'abnormal', 'scoliotic, cranial sutures open', 689.5703401029862, 'normal', 0.0125475577418239, 'normal', 1.0231903735292165, 0.9926607742538232, 0.9573848858565136], ['male', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.86, 'normal', None, 407.5675328525925, 'normal', 0.0, 'normal', 1.0126962983394976, 0.988236568119403, 0.9711910800682376], ['female', 'C57Bl/6NCrl', 'c276', datetime.date(2023, 2, 6), 26.49, 'abnormal', 'T1-T2 transposed, cranial sutures open', 554.5636621082936, 'normal', 0.0008454709657584, 'normal', 1.0221852490821006, 0.998233076024499, 0.9741637597608476]]

[['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.89, 'normal', 'pectus excavatum', 265.46843060101264, 'normal', 0.000345874485992, 'normal', 1.012125904685709, 1.0037398068693364, 0.9766037335384056], ['female', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 26.7, 'normal', 'T1 not fused', 340.7195783285061, 'normal', 7.686099688712963e-05, 'normal', 1.0284354604055228, 1.002275848791426, 0.96911945643199], ['male', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 25.52, 'normal', 'L6 = S0, pectus excavatum severe,', 543.1074383720097, 'normal', 0.0112793512931862, 'normal', 0.9967047635034144, 0.9720828136698793, 0.9395152253046636], ['male', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 26.77, 'normal', 'T1 not fused, pectus excavatum', 222.32347766756865, 'normal', 0.0, 'normal', 1.012702395890692, 0.9895702691584498, 0.9794308958819588], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 25.85, 'abnormal', 'T1 not fused, cranial sutures open', 1078.8275077559692, 'abnormal', 0.0598939318242957, 'normal', 1.027248116759364, 0.999887039299322, 0.94086063878506], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.13, 'abnormal', 'T1 not fused, kyphosis severe, cranial sutures open mild', 556.1348452879906, 'normal', 0.0034203143614772, 'normal', 1.0350920857199977, 1.019238691987925, 0.9668012729641932], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 27.02, 'abnormal', 'T1 not fused, cranial sutures open mild', 588.5069823527735, 'normal', 0.0070135659659505, 'normal', 1.0234836550393334, 1.0046322095162137, 0.9546287838219276], ['female', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 25.95, 'normal', None, 530.3214760412094, 'normal', 0.0008839014642019, 'normal', 0.9828049077205592, 0.9803144779902876, 0.947600564728516], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 25.78, 'abnormal', 'kyphosis, cranial sutures open mild', 743.884824799915, 'normal', 0.0009031167134237, 'normal', 0.9951841233968678, 0.9864148746995473, 0.9350789672738956], ['female', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 26.34, 'normal', 'pectus excavatum', 410.98586000390674, 'normal', 3.8430498443564814e-05, 'normal', 1.0165895197604933, 0.9941037500649592, 0.9613710944419704], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.66, 'normal', 'kyphosis', 451.7238803243284, 'normal', 0.0010184082087544, 'normal', 1.0559983428834658, 1.0275481724209656, 0.9757968134239644], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.23, 'abnormal', 'LHP II. Osteoneogenesis mild, cranial sutures open', 297.57646048368684, 'normal', 0.0013066369470812, 'normal', 1.0235578801912573, 0.9934976315220796, 0.969720911539014], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.58, 'abnormal', 'kyphosis, cranial sutures open mild', 568.0260428595507, 'normal', 0.0069943507167287, 'normal', 1.0190596889010146, 1.0053806950400137, 0.9772943405785032], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.9, 'normal', 'T1 not fused', 651.3408958219177, 'normal', 0.0031897313708158, 'normal', 1.0389322745783955, 0.9975253667889562, 0.987590008584084], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.54, 'abnormal', 'T1 not fused, tail move, cranial sutures open', 454.13327410075226, 'normal', 0.0039967718381307, 'normal', 1.0099856184559393, 0.995027370597852, 0.9603995407594762], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.03, 'normal', None, 485.2958318786045, 'normal', 0.0012874216978594, 'normal', 1.0067028583586293, 0.9830739079009284, 0.964092041918466], ['male', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 26.3, 'normal', 'L6 = half S0, kyphosis, pectus excavatum mild,', 400.4179798384002, 'normal', 0.0035548211060297, 'normal', 1.0150313425760562, 0.9963979062820708, 0.9574373714419436], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 25.72, 'abnormal', 'cranial sutures open', 686.2605199813319, 'normal', 0.0604127435532838, 'normal', 1.0568316577415628, 0.9820511320875284, 0.9532854023245556], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.49, 'normal', 'tail move,', 643.9995292430235, 'normal', 0.0365281887706083, 'normal', 1.054853488208617, 1.0178295614207695, 0.9485013201556266], ['male', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.88, 'normal', 'T1 not fused', 497.1918654608478, 'normal', 0.0080896199223703, 'normal', 1.0667059846354576, 1.024745579863514, 0.9704695247522988], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 24.96, 'abnormal', 'kyphosis, rostrum malformation, cranial sutures open', 3126.6435862400817, 'abnormal', 0.3100380461934591, 'abnormal', 1.017993831752578, 1.0012001283866376, 0.9622653169284422], ['female', 'Ssu2', 'c313', datetime.date(2023, 11, 6), 26.16, 'abnormal', 'cranial sutures open', 901.0409189349306, 'normal', 0.0407171131009569, 'normal', 1.030944402229235, 1.0098605862731298, 0.9377361112327938], ['male', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 26.24, 'normal', 'pectus excavatum', 362.676440192162, 'normal', 0.0, 'normal', 1.0141114384454923, 0.9833070801946584, 0.96514922473894], ['female', 'C57Bl/6NCrl', 'c313', datetime.date(2023, 11, 6), 26.64, 'normal', 'T1 not fused, pectus excavatum mild', 698.2214976626609, 'normal', 0.0161984550939625, 'normal', 1.0226224655582012, 0.9885967790593152, 0.9633771402205902]]

In [41]:
res_df = pd.DataFrame(data,index=indexes,columns=['GENDER','STRAIN','COHORT_ID','DATE','CraniumLength','SkullShape','Comment'] + list(file_analysis.columns))

In [42]:

res_df.to_excel(output_file)

#res_df.to_csv(output_file)

/usr/local/lib/python3.8/dist-packages/pandas/compat/_optional.py:149: UserWarning: Pandas requires version '1.2.2' or newer of 'xlsxwriter' (version '1.1.2' currently installed).
  warnings.warn(msg, UserWarning)

In [43]:
file_analysis.columns

Index(['proc_dist', 'abn_distance', 'area99perc', 'abn_perc', 's_x', 's_y',
       's_z'],
      dtype='object')

In [44]:
db_df

,SPECIMEN_ID,STRAIN,GENDER,COHORT_ID,DATE,SkullShape,CraniumLength,Comment
0,064-EPJ77,"Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Nub1",female,c004,2016-11-10,normal,26.58,None
1,064-EPJ81,"Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Nub1",male,c004,2016-11-10,normal,26.65,None
2,064-EPJ82,"Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Nub1",male,c004,2016-11-10,normal,26.21,None
3,064-EPJ85,"Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Nub1",female,c004,2016-11-09,normal,25.98,None
4,064-EPJ86,"Gt(ROSA)26Sor(ACTB-Cre,-EGFP)lcs x Nub1",female,c004,2016-11-09,normal,26.26,None
...,...,...,...,...,...,...,...,...
9592,E83-F2740,Fam161b,male,c137,2020-05-06,normal,26.56,stretched
9593,E83-F2743,Fam161b,female,c137,2020-05-06,normal,26.37,tendon ossification
9594,E83-F2749,Fam161b,female,c136,2020-05-11,normal,26.52,None
9595,E83-F2750,Fam161b,female,c136,2020-05-11,abnormal,25.31,None
9596,E83-F2757,Fam161b,male,c137,2020-05-06,abnormal,23.89,nose move; stretched; cranium sutures open; C7...

In [45]:
res_df

,GENDER,STRAIN,COHORT_ID,DATE,CraniumLength,SkullShape,Comment,proc_dist,abn_distance,area99perc,abn_perc,s_x,s_y,s_z
Adam7_F_E64-CD965,female,Adam7,c290,2023-05-29,26.88,abnormal,cranial sutures open mild,554.169133,normal,0.015699,normal,1.026359,0.992808,0.956010
wt_M_82Z-13214,male,C57Bl/6NCrl,c290,2023-05-29,26.69,normal,kyphosis,473.284425,normal,0.008897,normal,1.016556,0.997176,0.967508
Cd209c_F_E64-CE021,female,Cd209c,c290,2023-05-29,27.06,abnormal,"T1 not fused, pectus excavatum, cranial suture...",353.555476,normal,0.000000,normal,1.026131,1.002799,0.991982
wt_F_82Z-13253,female,C57Bl/6NCrl,c290,2023-05-29,26.87,normal,"T1 not fused, left C7 rib rudiment, pectus exc...",450.354123,normal,0.001114,normal,1.020436,0.995576,0.965687
Adam7_F_E64-CD970,female,Adam7,c290,2023-05-29,26.39,abnormal,cranial sutures open,548.089089,normal,0.000038,normal,1.030566,1.003992,0.986610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ssu2_M_E64-CF733,male,Ssu2,c313,2023-11-06,26.88,normal,T1 not fused,497.191865,normal,0.008090,normal,1.066706,1.024746,0.970470
Ssu2_F_E64-CF731,female,Ssu2,c313,2023-11-06,24.96,abnormal,"kyphosis, rostrum malformation, cranial suture...",3126.643586,abnormal,0.310038,abnormal,1.017994,1.001200,0.962265
Ssu2_F_E64-CF724,female,Ssu2,c313,2023-11-06,26.16,abnormal,cranial sutures open,901.040919,normal,0.040717,normal,1.030944,1.009861,0.937736
wt_M_82Z-14771,male,C57Bl/6NCrl,c313,2023-11-06,26.24,normal,pectus excavatum,362.676440,normal,0.000000,normal,1.014111,0.983307,0.965149
wt_F_82Z-14775,female,C57Bl/6NCrl,c313,2023-11-06,26.64,normal,"T1 not fused, pectus excavatum mild",698.221498,normal,0.016198,normal,1.022622,0.988597,0.963377